### ISSUE TITLE
Invalid return type (PassportInterface) with authenticate function generated by make:auth 

### ISSUE THREAD

**Issue by mdeherder** [symfony/maker-bundle#1011]
After :

>     symfony console make:auth
>
>        Login form authenticator
>        AppAuthenticator
>        SecurityController
>        yes

I need to replace

`public function authenticate(Request $request): PassportInterface`

by

`public function authenticate(Request $request): Passport`

in the file `src/Security/AppAuthenticator.php` created by the command

**Comment by stof** [comment]
Are you using the latest (1.36.0) release of maker-bundle ? This should already be fixed by https://github.com/symfony/maker-bundle/pull/1010

**Comment by mdeherder** [comment]
Sorry, I was still in 1.35.0

**Comment by weaverryan** [comment]
Haha, that's ok - I think I released 1.36.0 about 2 hours after you opened this :)
