### ISSUE TITLE
Class "Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator" does not exist

### ISSUE THREAD

**Issue by 537mfb** [symfony/maker-bundle#1018]
Testing `Symfony 6.0-RC1`, I get the following output when I do `symfony console make:auth`:

```
 What style of authentication do you want? [Empty authenticator]:
  [0] Empty authenticator
  [1] Login form authenticator
 > 1

 The class name of the authenticator to create (e.g. AppCustomAuthenticator):
 > AppAuthenticator

 Choose a name for the controller class (e.g. SecurityController) [SecurityController]:
 > 

 Do you want to generate a '/logout' URL? (yes/no) [yes]:
 > 

In MakeAuthenticator.php line 411:

  Class "Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator" does not exist  

make:auth [--firewall-name [FIREWALL-NAME]] [--entry-point [ENTRY-POINT]] [--] <authenticator-type> <authenticator-class> <controller-class> <user-class> <username-field> <logout-setup>

exit status 1
```
I thought the `Guard Authenticator` had been deprecated an a new authentication mechanism had been implemented in `Symfony 5.3`

**Comment by Neyo03** [comment]
Problem's solved ? 

I have the same problem but i cant resolve him

**Comment by weaverryan** [comment]
Yup, we're not coding carefully enough here: https://github.com/symfony/maker-bundle/blob/0f40c826c0725208c254ddcd3481690e6c7e5047/src/Maker/MakeAuthenticator.php#L411

That should be an easy fix - I'm not sure why the tests didn't catch it, but we'll need to check that too :)

**Comment by BretonLud** [comment]
Hello, i have the same issue. 

I solved it by changing `$reflectionMethod = new \ReflectionMethod(AbstractFormLoginAuthenticator::class, 'onAuthenticationSuccess'); ` to  `$reflectionMethod = new \ReflectionMethod(AbstractLoginFormAuthenticator::class, 'onAuthenticationSuccess');`
