### ISSUE TITLE
Confusing message in the output of make:auth for LoginFormAuthenticator

### ISSUE THREAD

**Issue by php4fan** [symfony/maker-bundle#1020]
### Symfony version(s) affected

5.4.0

### Description

When you run `bin/console make:auth`, and you choose a login form authenticator, at the end you get this message:

```
 Success! 
           

 Next:
 - (...)
 - Check the user's password in App\Security\LoginFormAuthenticator::checkCredentials().  
 - (...)
```

That, to me, means that I should expect to find a method called `checkCredentials()` in `LoginFormAuthenticator`, hopefully with some comment telling me exactly where I should add the code to check the password.

But there's no such method.

Perhaps the message is outdated and refers to an old obsolete method that got superseded by `authenticate()`? If that's not it, I'm confused.

### How to reproduce

```
bin/console make:auth
```

**Comment by xabbuh** [comment]
@php4fan FYI, I have move your issue as the `make:auth` command is provided by the MakerBundle.

**Comment by weaverryan** [comment]
Yup, we added support for the new authenticator system - but I think we didn't make this message smart enough to handle both systems (Maker still supports Guard and the new system). That needs to be fixed.
