### ISSUE TITLE
unable to create a new symfony project with symfony command

### ISSUE THREAD

**Issue by BigMichi1** [symfony/maker-bundle#1022]
when i try to run the `symfony new` command it fails with following output

```
 michaelcramer@p52  ~/ttttt  symfony new --webapp --dir gfw                                              
* Creating a new Symfony project with Composer
  (running /home/michaelcramer/bin/composer create-project symfony/skeleton /home/michaelcramer/ttttt/gfw  --no-interaction)

* Setting up the project under Git version control
  (running git init /home/michaelcramer/ttttt/gfw)

  (running /home/michaelcramer/bin/composer require webapp --no-interaction)

exit status 2
Using version ^1.0 for symfony/webapp-pack
./composer.json has been updated
Running composer update symfony/webapp-pack
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/maker-bundle[1.0.0, ..., v1.22.0] require php ^7.1.3 -> your php version (8.0.13) does not satisfy that requirement.
    - symfony/maker-bundle[v1.0.1, ..., v1.16.0] require php ^7.0.8 -> your php version (8.0.13) does not satisfy that requirement.
    - symfony/maker-bundle[v1.23.0, ..., v1.29.2] require symfony/config ^3.4|^4.0|^5.0 -> found symfony/config[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but the package is fixed to v6.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/maker-bundle[v1.30.0, ..., v1.34.1] require symfony/config ^4.0|^5.0 -> found symfony/config[v4.0.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but the package is fixed to v6.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/maker-bundle[v1.35.0, ..., v1.36.3] require symfony/deprecation-contracts ^2.2 -> found symfony/deprecation-contracts[v2.2.0, v2.4.0, v2.4.1, v2.5.0] but the package is fixed to v3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/webapp-pack v1.0.0 requires symfony/maker-bundle ^1.0 -> satisfiable by symfony/maker-bundle[1.0.0, ..., v1.36.3].
    - Root composer.json requires symfony/webapp-pack ^1.0 -> satisfiable by symfony/webapp-pack[v1.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require symfony/webapp-pack:*" to figure out if any version is installable, or "composer require symfony/webapp-pack:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

                                                                                  
  unable to run /home/michaelcramer/bin/composer require webapp --no-interaction  
                                                                                  
Error reported as #153ea1cf8e9b44978e8c09e0572d506c
```

**Comment by weaverryan** [comment]
This will be fixed by #1023, which I am to tag today :)

**Comment by weaverryan** [comment]
Try 1.36.4. There may still be some other dependency issues (the test suite on Symfony 6 is still having some problems - but those may be unrelated to Maker), but this issue should be resolved :)

**Comment by netteria** [comment]
And it's 2022 and I still have this problem.
unable to run / usr / local / bin / composer create-project symfony / skeleton / var / www / cms / symnewsletter 6.1. * --no-interaction

**Comment by jdelauney** [comment]
Same here today

>   [InvalidArgumentException]
>   Could not find package webapp.
> 
>   Did you mean one of these?
>       peej/tonic
>       leafs/leaf
>       link/link
>       symfony/webapp-pack
>       symfony/webapp-meta

**Comment by jdelauney** [comment]
Same here today with :

> symfony new --webapp myFolder


>   [InvalidArgumentException]
>   Could not find package webapp.
> 
>   Did you mean one of these?
>       peej/tonic
>       leafs/leaf
>       link/link
>       symfony/webapp-pack
>       symfony/webapp-meta

**Comment by piyuesh-dev** [comment]
> Same here today With the command : _symfony new --webapp myFolder_
> 
> > [InvalidArgumentException]
> > Could not find package webapp.
> > Did you mean one of these?
> > peej/tonic
> > leafs/leaf
> > link/link
> > symfony/webapp-pack
> > symfony/webapp-meta
> > Error reported as #d58ecdd7ad3343d3acd7a76ecb639ea2

I has same issue, updated composer to latest and it worked.

**Comment by LucasWarlopTwa** [comment]
I encountered the same problem. I was able to fix it by simply changing the creation folder name (parent).
In my case (on Mac) it seems that creating a new Symfony project in a folder whose name is composed of special characters ([parent folder]) leads to an error of this type.

**Comment by LucasWarlop** [comment]
I encountered the same problem. I was able to fix it by simply changing the creation folder name (parent).
In my case (on Mac) it seems that creating a new Symfony project in a folder whose name is composed of special characters ([parent_folder]) leads to an error of this type.

**Comment by pieterdt** [comment]
I have this problem as well (on osX) and I think it might be due to the presence of a different than expected flex binary that is in the path:

`pdt@MacBook-Pro-5 Code % flex -h     
Usage: flex [OPTIONS] [FILE]...
Generates programs that perform pattern-matching on text.

Table Compression:
  -Ca, --align      trade off larger tables for better memory alignment
  -Ce, --ecs        construct equivalence classes
  -Cf               do not compress tables; use -f representation
  -CF               do not compress tables; use -F representation
  -Cm, --meta-ecs   construct meta-equivalence classes
  -Cr, --read       use read() instead of stdio for scanner input
  -f, --full        generate fast, large scanner. Same as -Cfr
  -F, --fast        use alternate table representation. Same as -CFr
  -Cem              default compression (same as --ecs --meta-ecs)
`

That doesn't seem to be the flex that gets installed with symfony-cli

which basically means that it is not a maker bundle issue, but I thought I would post my finding here given other people end up here with the same problem. Not sure how to get around this though.

**Comment by wouterj** [comment]
Symfony flex doesn't use `flex` command.

**Comment by RogerBytes** [comment]
Same problem here :
```bash
❯ symfony new ~/Local/Git/Pizzeria --version="6.0.*" --webapp
* Creating a new Symfony 6.0.* project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton /home/harry/Local/Git/Pizzeria 6.0.* --no-interaction)

* Setting up the project under Git version control
  (running git init /home/harry/Local/Git/Pizzeria)

  (running /usr/local/bin/composer require webapp --no-interaction)

./composer.json has been updated
Running composer update symfony/webapp-pack
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/framework-bundle[v6.0.0, ..., v6.0.19] require ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
    - Root composer.json requires symfony/framework-bundle 6.0.* -> satisfiable by symfony/framework-bundle[v6.0.0, ..., v6.0.19].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-xml` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require symfony/webapp-pack:*" to figure out if any version is installable, or "composer require symfony/webapp-pack:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

                                                                         
  unable to run /usr/local/bin/composer require webapp --no-interaction  
                                                                         

 󰌽   ~ 
❯ 
```

I still have `unable to run /usr/local/bin/composer require webapp --no-interaction` error.

Any suggestion to fix this ?

**Comment by Crayzo** [comment]
@RogerBytes OMG Thanks!!

**Comment by jrushlow** [comment]
I'm going to lock this just to encourage folks to create a new issue in `symfony/symfony` for problems with the Symfony Binary. Since @weaverryan fixed the OP's original problem back in 2021, the subsequent comments appear to be unrelated to MakerBundle.
