### ISSUE TITLE
[RFC] Add ability to override templates

### ISSUE THREAD

**Issue by gnito-org** [symfony/maker-bundle#1029]
Here's a wall I've banged my head against a few times.

Sometimes I need to make many copies of the same type of thing. For example, if the app has many entities and you want to generate a zenstruck factory for each of entities. Afterwards I normally have to edit each one and change it to the layout and content that I prefer (which is still standard across all my factories).

It would be super helpful if one could save your own templates in, say, ``templates/factory``, and have maker use those templates.

Maker would then need an extra ``--template``  argument. In the [generate step](https://github.com/symfony/maker-bundle/blob/716eee9c8b10b33e682df1b7d80b9061887e9691/src/Generator.php#L61) it would replace the standard (symfony-, zenstruck-supplied) template with your own template.

The major constraint would be that your custom template must have the same variables as the vendor template. If the template needs more than that, then one would need to create your own custom maker.

I understand that creating your own custom maker is easy, but if the need is simply to use a slightly different template, creating an entirely new maker is an overkill.

**Comment by weaverryan** [comment]
Hey @gnito-org!

This is also discussed on #33 - it's a long-standing issue. But I think the need is legitimate. My concern is that I don't want MakerBundle to need to guarantee that certain template variables won't change. Not needing to guarantee that allows us to iterate faster. That being said, I'm not against this.

Btw, I did comment on a potential implementation: https://github.com/symfony/maker-bundle/pull/562#discussion_r406178516. However, sometimes we generate code NOT from templates, but from PHP code (this is usually when we're updating an existing file). I wish we would have a uniform (works the same everywhere) system for overriding stuff, but that would require some reorganization inside Maker to make things more consistent.
