### ISSUE TITLE
Flex dependency

### ISSUE THREAD

**Issue by fpalluel** [symfony/maker-bundle#103]
Hello,
I'm currently using this bundle with Symphony 3.4 to create custom makers.
According to the documentation, this bundle depends on Flex, and I had to remove the Flex dependency check to make it run.

If I understand correctly, the Flex dependency is there because the default makers (controllers, entities, ...etc.) make use of the new Flex file structure. But in the case of custom makers, it's a shame that one can not use this bundle with "Flexless" Symfony 3.4...
Wouldn't it be enough to show a warning message like "Beware, default makers will only work in a Flex environment" ?
Or have I missed anything ?

Thanks in advance ;-)

**Comment by javiereguiluz** [comment]
I'm not sure about the Flex dependency details ... but I know that this bundle only works in apps following the Flex directory structure. So maybe we should keep this dependency.

**Comment by javiereguiluz** [comment]
Closing as fixed by #107.
