### ISSUE TITLE
Error to deploy

### ISSUE THREAD

**Issue by pakolkf** [symfony/maker-bundle#1055]
Hi! I am trying to send a development to the main branch and it is impossible for me since it does not pass the tests. 
I have seen that this error has been going on for some time. 
The error is as follows "To use Doctrine entity attributes you'll need PHP 8, doctrine/orm 2.9, doctrine/doctrine-bundle 2.4 and symfony/framework-bundle 5.2.". 
Any ideas?

**Comment by wouterj** [comment]
Hi!

Seems like your environment doesn't fulfill all conditions that are described in the error message.

However, this is not related to the MakerBundle. You can use one of the support channels (https://symfony.com/support) to get help from the community.

**Comment by pakolkf** [comment]
I'm sorry but right now I don't get it. I work with a docker environment and this bundle works without problems. I have the problem when uploading it to the main branch of github since it does not pass the tests for the previously mentioned dependencies.

All the best,
Thanks a lot

**Comment by pakolkf** [comment]
I'm sorry but right now I don't get it. I work with a docker environment and this bundle works without problems. I have the problem when uploading it to the main branch of github since it does not pass the tests for the previously mentioned dependencies.

All the best,
Thanks a lot

**Comment by pakolkf** [comment]
J

**Comment by pakolkf** [comment]
I'm sorry but right now I don't get it. I work with a docker environment and this bundle works without problems. I have the problem when uploading it to the main branch of github since it does not pass the tests for the previously mentioned dependencies.

All the best,
Thanks a lot
