### ISSUE TITLE
Generate controllers in subdirectories

### ISSUE THREAD

**Issue by Echabeto** [symfony/maker-bundle#106]
maker-bundle can not generate controllers in subdirectories, or at least it is not in the documentation of how to do it.

I already tried the following options
1.- `People:ProfessionController`
2.- `People\ProfessionController`
3.- `People/ProfessionController`

If somehow this option is not created, it would be good to enable it for all bundle commands. And apply it with the first option.

**Comment by javiereguiluz** [comment]
@Echabeto you are right. It's not possible (yet) to generate controllers (and other elements) in subdirectories/subnamespaces. The good news is that we're working on it (see #94) so it will be possible in the near future.

I'm closing this one as duplicate then. Thanks!

**Comment by NgatiaFrankline** [comment]
### Update
Am using Symfony 5.1.5 and php 7.4.10 and am having a subfolder with name `Api` in `src\Controller` therefore my namespace is `namespace App\Controller\Api`. I can now create a controller inside the `Api` subfolder with this command:
```
php bin/console make:controller Api\\UserDetailsController
```
Its a shorthand if u don't want the dialog, otherwise when you are prompted input `Api\\UserDetailsController`

**Comment by noubicastel** [comment]
Use command :
`php bin/console make:controller Api\UserDetailsController`

**Comment by JoseGonzalez84** [comment]
> Use command : `php bin/console make:controller Api\UserDetailsController`

This doesn't work. This make this result:

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class ApiUserDetailsController extends AbstractController
{
    #[Route('/api/user/details', name: 'app_api_user_details')]
    public function index(): JsonResponse
    {
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/ApiUserDetailsController.php',
        ]);
    }
}
```

The appropriate action would be:

`php bin/console make:controller Api\\UserDetailsController`

It makes this:

```php
<?php

namespace App\Controller\Api;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class UserDetailsController extends AbstractController
{
    #[Route('/api/user/details', name: 'app_api_user_details')]
    public function index(): JsonResponse
    {
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/Api/UserDetailsController.php',
        ]);
    }
}

```
