### ISSUE TITLE
make:controller did not generate template file

### ISSUE THREAD

**Issue by ngkung** [symfony/maker-bundle#1066]
I am using Symfony 6.0 and make bundle 1.36. No matter how hard I tried. No template files were generated.

_bin/console make:controller

 Choose a name for your controller class (e.g. GentlePopsicleController):
 > AdminUserController

 created: src/Controller/AdminUserController.php

           
  Success! 
           

 Next: Open your new controller class and add some pages!_

It seems to me it was by default using --no-template option. However, there is not options for forcing templates to be generated. Is that my issue only?

**Comment by jrushlow** [comment]
Hmm interesting, can you create a simple reproducer app that we can poke around in? Thank you in advance

**Comment by jrushlow** [comment]
Stale

**Comment by jrushlow** [comment]
Howdy @damhuonglan - I've just added additional tests to ensure that twig templates are generated with `make:controller` (locally, the tests pass & twig templates are generated)

The only way `make:controller` does _not_ generate twig templates is if:
a) the `--no-template` option is passed to `make:controller`
or
b) the `TwigBundle` is _not_ installed

To ensure the `TwigBundle` is installed, run `composer require symfony/twig-bundle`. This is installed by default when creating a new Symfony project with the Symfony CLI tool and passing `--webapp` (previously `--full`) to the `new` command. e.g. `symfony new --webapp ./my-app`

Please let me know if you're still having problems with `make:controller` not creating twig template. And if you managed to get it working, let us know the solution. Thank you!

**Comment by damhuonglan** [comment]
Thank you. After I installed `TwigBundle`, I was able to create template with `make:controller`.
