### ISSUE TITLE
[verify-email] use "user_class_name" rather than UserInterface

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#1072]
Hi,
I think it would be nice to use the real user class for `EmailVerifier`.
Example : a variable `$user_class_name` instead of `UserInterface`.

It could autocomplete in IDE.

https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php#L26
https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php#L52

What do you think ?

**Comment by jrushlow** [comment]
Howdy @seb-jean - this has been completed in https://github.com/symfony/maker-bundle/pull/1519 and will make the next release (`v1.59.0`)
