### ISSUE TITLE
Remove question mark when the property is not nullable on getter

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#1074]
Hi,

I'm wondering whether to prefix the type name with a question mark when the property is not nullable on getter.

Here is an example of the code of the entity generated by the maker-bundle:

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
    
    #[ORM\Column(type: 'string', length: 255)]
    private $lastName;
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }
}
```

Shouldn't we generate the code below instead:
```php
public function getLastName(): string
{
    return $this->lastName;
}
```

Thanks 😄

**Comment by jrushlow** [comment]
There were "bugs" in `ORM` && `Symfony` related to typed properties in PHP 7.4 that required the properties to be nullable for doctrine. 

What I do not know, is if we remove the `?` from properties that are not nullable, will this cause any conflicts with earlier supported symfony / doctrine versions. 

From a different issue (copy and pasted)
Doctrine & Symfony have fixed the bugs which did not allow to proxy a doctrine entity with uninitialized properties. See https://github.com/doctrine/orm/issues/8030 & https://github.com/symfony/symfony/pull/36332

**Comment by thsmrtone1** [comment]
@seb-jean In your example, the getter _should_ be nullable. See this case:

```php
$user = new User();
dump($user->getLastName()); // null
```

If getLastName() is called before setLastName() is called, and/or before the entity is persisted to the database, then the value will be null regardless what the column definition says.

**Comment by weaverryan** [comment]
> @seb-jean In your example, the getter should be nullable. See this case:

Yup, exactly right :).

One thing we DO need to do still is start adding property types to generated code. In this case, the property would be generated as `private ?string $lastName;`.
