### ISSUE TITLE
Migrations created as root user are not readable/writeable

### ISSUE THREAD

**Issue by PythooonUser** [symfony/maker-bundle#1083]
## Summary
When creating a migration, the containing folder is created as root user without write permissions for group. This results in git to not being able to create the file when checking out branches, merging branches.

```
$ git merge
error: unable to create file src/Migrations/2022/03/Version20220308140950.php: Permission denied

$ ll
drwxr-xr-x 2 root  root  4096 Mär 11 16:00 03/
```

Updating the group permissions doesn't help. I deleted the folder and re-created it manually.
```
drwxrwxr-x 2 felix felix 4096 Mär 14 08:41 03/
```

Then it works.

## Resolve
It would be great when maker bundle would create files and folders as the actual user, not root. I think that would solve the problem?!

## System
Ubuntu, maker-bundle (v1.38.0)

**Comment by jrushlow** [comment]
Howdy! Are you sure you're not running `bin/console make:migration` as `root`? All generated files by MakerBundle use the `user` which issued the command to set the files `owner:group`.

**Comment by PythooonUser** [comment]
I think you are right @jrushlow, I actually run these commands inside a Docker container, and that executes stuff as `root`. 

However, I still need to run `$ chmod 0777 path` on the created folder, as it's created with `drwxr-xr-x`. Could that be related?

**Comment by jrushlow** [comment]
In you `Dockerfile`, set the user & group to a non-privileged account (`1000:1000` || `user:user`). E.g:

https://github.com/rushlow-development/docker-php-base/blob/main/fpm/Dockerfile#L49

Then when you rebuild your container and execute `make:a-maker` - the command will be run as a regular user.

> I still need to run $ chmod 0777 path on the created folder, as it's created with drwxr-xr-x. 

The file permissions that are set by MakerBundle are correct. `0755` on a _folder_ allows the `owner` to Read|Write|Execute, the `group` to `Read|Execute`, and `others` to `Read|Execute`. Meaning anyone can read the contents of the folder but only the `owner` (in this case root) can write to it. The subsequent files created within that folder are usually `0744` where the `group` and `others` cannot execute - only read.

When you chmod `0777` - you're allowing the `owner`, `group`, & `others` to Read|Write|Execute which is not a very good idea. Anywho, adding in the `user 1000:1000` to the bottom of your dockerfile should clear things up.
