### ISSUE TITLE
make:entity repository add/remove method signature

### ISSUE THREAD

**Issue by JB-oclock** [symfony/maker-bundle#1086]
Hi,

i'm happy to have this two new method: it's easier to use Repository than EntityManagerInterface in Controller.

But i'm not sure that the flush parameter with default value to `true` is a good choice.

https://github.com/symfony/maker-bundle/blob/a9b817d9cc94f42dd195c633404408140bf78bd3/src/Resources/skeleton/doctrine/Repository.tpl.php#L32

I see datamapper as a "transaction" use of the database, so using flush by default and not using "transaction" was not what i expect.

I just want to know your vision of the default value to `true`
This issue is more a discussion.

**Comment by hhamon** [comment]
> But i'm not sure that the flush parameter with default value to true is a good choice.

I also agree that flushing the transaction should not be triggered implicitely. By default, the developer should `->flush()` explicitely or pass `true` explicitely to this method.
