### ISSUE TITLE
make:test ApiTestCase Example fails

### ISSUE THREAD

**Issue by HerHde** [symfony/maker-bundle#1091]
### Symfony version(s) affected

6.0.x

### Description

Generating a new `ApiTestCase` via cli fails, when using the `make:test [<type> [<name>]]` syntax with the error

```
 [ERROR] Missing package: to use the make:test command, run:                                                            
                                                                                                                        
         composer require api
```

even when the package IS installed and although the interactive command works.

### How to reproduce

run

```shell
symfony new --dir .
composer require symfony/maker-bundle symfony/test-pack --dev
composer require api
php bin/console make:test ApiTestCase ExampleTest
```

### Additional Context

PHP 8.1.3
Symfony CLI version 5.4.7

**Comment by jrushlow** [comment]
Howdy @HerHde - I'm reviewing the code for `make:test` and if `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase::class` or `ApiPlatform\Symfony\Bundle\Test\ApiTestCase::class` do not exist, the error you described is thrown. Can you confirm that you have

1) composer require api
2) cleared the cache (`bin/console cache:clear`)
3) Do either of those 2 classes exist?

**Comment by jrushlow** [comment]
Howdy @HerHde - I'm reviewing the code for `make:test` and if `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase::class` or `ApiPlatform\Symfony\Bundle\Test\ApiTestCase::class` do not exist, the error you described is thrown. Can you confirm that you have

1) composer require api
2) cleared the cache (`bin/console cache:clear`)
3) Do either of those 2 classes exist?

**Comment by HerHde** [comment]
Hey @jrushlow, yes, I can confirm 1 and 2. Regarding 3 I can confirm, that `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase` exists as mentioned in #1092.

**Comment by weaverryan** [comment]
@HerHde gave us a very easy way to reproduce this. But, I can't replicate it on API Platform 3 or 2.7. So, this may have been resolved already.

Cheers!
