### ISSUE TITLE
Is there a 'no go' to put Symfony\Bundle\MakerBundle\MakerBundle::class => ['all' => true]

### ISSUE THREAD

**Issue by mcambois** [symfony/maker-bundle#1094]
I have a specific case where I need it, just asking, what kind of risks it occur to do that ?

**Comment by jrushlow** [comment]
You _could_ do that, but i wouldn't recommend it. MakerBundle is used to generate code for a developer to work review, modify, then implement. Allowing the use of MakerBundle in a production environment means you're developing and application in production which in of itself goes against several develop principles / best practices. 

Using MakerBundle in production also means you would be installing `-dev` dependencies in your environment which may conflict with your code base dependencies, dependencies may be unstable (if not now - possibly in the future), and generally add additional bloat to your application.

From a security standpoint, it would open up several potential attack vectors to your application / infrastructure. E.g. `bin/console make:user` chained with `bin/console make:auth` could allow unauthorized access to your app. Granted that example is a bit far fetched, but you get the idea...

Another consideration to be made is the templates/code generated by MakerBundle can, and more often than not, does change between `minor` releases. See https://github.com/symfony/maker-bundle#backwards-compatibility-promise

This doesn't cover all of the reasons you shouldn't , but covers a few of the major ones that come to mind. Your best bet would be to replicate whatever functionality you're attempting to use in a production environment in your own code base.

Feel free to reach out if you any additional details on your use case. We may be able to point you in a better direction. Thanks!
