### ISSUE TITLE
This worked for me also :

### ISSUE THREAD

**Issue by medhashas** [symfony/maker-bundle#1103]
This worked for me :
1. Edit `composer.json` to change `doctrine/orm` version
```
...
    "require": {
        ...
        "doctrine/orm": "^2.11",
        ...
    }
    ...
    "conflict": {
        "symfony/symfony": "*",
        "doctrine/orm": "2.12.0"
    },
...
```
2. Update dependencies : `composer update`
3. Enjoy !

_Originally posted by @lionelkimbs in https://github.com/symfony/maker-bundle/issues/1090#issuecomment-1104180673_

**Comment by jrushlow** [comment]
I'm not sure what the issue is here.
