### ISSUE TITLE
Subdirectory for entity and repository

### ISSUE THREAD

**Issue by mrWodoo** [symfony/maker-bundle#111]
Hello,
let's say I keep my entities in ./src/Entity/ but I want to organize it better, so I've decided to split entities into other directories, for example ./src/Entity/Shop/ and other in ./src/Entity/Auth/ 
how do I achieve this using php bin/console make:entity? Is there a way to do this?

**Comment by javiereguiluz** [comment]
Thanks for proposing this idea. You are right and this is something that we could provide. Others asked for this before, so we are working on this idea in #94. So, I'm closing it as duplicate. Thanks!

**Comment by FACHINA** [comment]
Just make this:

On windows
`php bin/console make:entity  EntitySubFolder\MyEntity`
On linux
`php bin/console make:entity  EntitySubFolder\\MyEntity`

**Comment by ZaneCEO** [comment]
@FACHINA method works, thanks! To expand on it: if you want to use an arbitrary path, just use its namespace: `symfony console make:entity \\App\\SubComponent\\Entity\\MyEntity`
