### ISSUE TITLE
make:crud missing: use Doctrine\ORM\EntityManagerInterface

### ISSUE THREAD

**Issue by yanickmorza** [symfony/maker-bundle#1131]
I am currently testing the maker-bundle 1.43 of symfony 6.
Class: EntityManagerInterface::class is missing from variable: $useStatements on line 156 in MakeCrud.php
This causes the missing: use Doctrine\ORM\EntityManagerInterface in the controllers.

**Comment by jrushlow** [comment]
Howdy @yanickmorza Thanks for giving us a heads up on the problem. Unfortunately, I'm unable to reproduce this issue in either fresh Symfony `6.0` || `6.1` app's. Ensure you have updated your dependencies with `composer upgrade`. 

- Can you provide your `composer.lock` file _or_ the output of `composer show`.
- Does the error happen when running `make:crud`?
- Does your entity have a `#[ORM\Entity(repositoryClass: SomeRepo::class)]` attribute?
- Can you provide the exact error message you are seeing.
- A simple reproducer app available on Github would aid in figuring out the problem.

Thanks in advanced!

**Comment by jrushlow** [comment]
No worries, I'm glad you were able to sort it out.
