### ISSUE TITLE
Collection adder use ->add() instead of [] to add item

### ISSUE THREAD

**Issue by HKandulla** [symfony/maker-bundle#1134]
Hi,

the following code is generated for properties of type collection:

```php
public function addAd(Ad $ad): self
{
    if (!$this->ads->contains($ad)) {
        $this->ads[] = $ad;
        $ad->setUser($this);
    }

    return $this;
}
```

This causes the following error in PHPStan:

```
    Doctrine\Common\Collections\ArrayCollection<*NEVER*, *NEVER*> does  not accept App\Entity\Ad. 
```

Wouldn't it make more sense to use the method `add()` of the collection instead of `[]`. Example:
```php
public function addAd(Ad $ad): self
{
    if (!$this->ads->contains($ad)) {
        $this->ads->add($ad);
        $ad->setUser($this);
    }

    return $this;
}
``` 
If yes, I am happy to create a PR.

Best, Hannes

**Comment by lyrixx** [comment]
And with the new version, PHPStan is OK
If yes, I'm not against this change

**Comment by HKandulla** [comment]
Yes, PHPStan is ok when using ->add() instead of []. Great, I will prepare a PR.

**Comment by HKandulla** [comment]
@lyrixx thanks for approving the PR https://github.com/symfony/maker-bundle/pull/1136

**Comment by jrushlow** [comment]
Merged in 1136
