### ISSUE TITLE
Repository template - rename add method to save 

### ISSUE THREAD

**Issue by MrYamous** [symfony/maker-bundle#1138]
Hi, 

Few times ago, PR #939 added new `add` and `remove` methods in repository template

I recently had the opportunity to use them, and when i made a method to edit a resource in my controller i was like "where is the method to edit ?" and then i realize `add` can do the job but i think it's a confusing name.

What would you think about rename this `add` method to something more generic like `save` ?

**Comment by MrYamous** [comment]
Hi @bdaler 
As contributor of the concerned PR, do you have any advice about this ?

**Comment by bdaler** [comment]
Hi @MrYamous 
Sounds reasonable and I don't mind. Fill free to make PR
