### ISSUE TITLE
Support for "doctrine:generate:form" ?

### ISSUE THREAD

**Issue by perice** [symfony/maker-bundle#114]
Hi,

how can I generate a form type class based on an existing entity class, like in the old generator bundle:

doctrine:generate:form

http://symfony.com/doc/current/bundles/SensioGeneratorBundle/commands/generate_doctrine_form.html

Can this be done with the Maker bundle?

**Comment by weaverryan** [comment]
I agree :). The `make:form` should probably be enhanced to ask you if you want to generate a form for an entity or not, and then generate a more complete class.
