### ISSUE TITLE
Create entity class without maker

### ISSUE THREAD

**Issue by butachan** [symfony/maker-bundle#1144]
Hello, I have a projet that includes many entities and their controller and crud, etc

I want to reuse them in another projet. So I want to copy paste the files.

But I already have a problem at entity creation:
The cmd shows that `make: entity` creates the entity class and the repository class (and nothing else) .So I copy paste these two to the new projet but they are ignored: 
When I try `make:migration`  I got _No database changes were detected._ When I try `make:entity` and type the name of the entity class (Taxe), I got _Cannot find the entity manager for class "App\Entity\Taxe" _. and `make:controller` with Taxe return _ Entity "Taxe" doesn't exist;_ .

So globally, how to create entity without the maker ? How can I reuse my entities/controllers/etc from another project pls?

**Comment by jrushlow** [comment]
Howdy @butachan! Have a look at https://symfony.com/doc/current/doctrine.html specifically the `Configuration` & `Creating an Entity Class` sections. It sounds like your doctrine configuration is not set up correctly, but I can't be for certain without seeing a re-producer example. 

There are a number of ways you can re-use code from one project in another, the simplest is to just copy the code over & make any necessary changes. The folks that are active in the Symfony Slack channel may have a few more ideas for you as well. https://symfony.com/community#community-support

Hope this helps!
