### ISSUE TITLE
[RFC] Update or refresh entities with make:entity

### ISSUE THREAD

**Issue by shakaran** [symfony/maker-bundle#115]
In old behaviour with doctrine when you add or remove some attribute, the new entity is updated and you dont have to delete it and recreate it again.

Currently the behaviour is a warning message saying that the entity file already exists and it doesn't update the new parameters. Even if probably this could be done via doctrine migrations, probably at initial stages when you build you anemic model, you don't have clear all the attributes and it is needed to update frequenly the entity.

**Comment by weaverryan** [comment]
Hi there!

To make sure I understand, do you want the ability to add properties to existing entities? If so, there is a pull request already open to add this :). Or do you want the ability to generate getters and setters for an entity that *you* have updated? The same PR adds that too :)

**Comment by shakaran** [comment]
@weaverryan yes, I think that this issue probably is a dupe of PR #104 (so closing) I am praising that you get your PR updated and merged to master ;)
