### ISSUE TITLE
ClassSourceManipulator::addSetter(): Argument #2 ($type) must be of type string, null given

### ISSUE THREAD

**Issue by mklewitz** [symfony/maker-bundle#1166]
https://github.com/symfony/maker-bundle/commit/ffc80c4d9b4eab6f86d07c33b90e6b9d4f030359 added ```string``` as type hint for ```Symfony\Bundle\MakerBundle\Util\ClassSourceManipulator::addSetter()```'s ```$type```.

However, ```ClassSourceManipulator::addEntityField()``` will call ```addSetter()``` with ```$type == null``` for all custom defined types and even for builtin type ```blob```.

That results in a type error when (re)generating entities: ```TypeError: Symfony\Bundle\MakerBundle\Util\ClassSourceManipulator::addSetter(): Argument #2 ($type) must be of type string, null given```

**Comment by sandoba** [comment]
Can confirm, this creates problems at the moment for the types "binary", "blob" and "ascii_string". All of these will crash the entity creation process. All other types seem to be ok.

The error message above continues:
`called in ...\vendor\symfony\maker-bundle\src\Util\ClassSourceManipulator.php on line 144`

**Comment by vladdnepr** [comment]
Same issue

**Comment by jrushlow** [comment]
Fixed in #1204
