### ISSUE TITLE
Error while generating entity

### ISSUE THREAD

**Issue by mesolaries** [symfony/maker-bundle#1173]
Symfony version: 4.4
Maker bundle version: 1.39.0
Doctrine ORM version: 2.13.1

```
In DoctrineHelper.php line 180:

  Class Doctrine\Persistence\Mapping\Driver\AnnotationDriver does not exist 
```

**Comment by weaverryan** [comment]
Hi!

Does `Doctrine\Persistence\Mapping\Driver\AnnotationDriver` exist in your project or not? 

Cheers!

**Comment by jrushlow** [comment]
Howdy @mesolaries - I'm closing as this appears to be stale, if you are still having problems, please feel free to open another issue. Thanks!
