### ISSUE TITLE
Error while making blob in entity

### ISSUE THREAD

**Issue by adsazad** [symfony/maker-bundle#1174]
I am making an entity using `php bin/console make:entity`. all other fields work fine but when I make a field `blob` maker bundle return this error.
```
Symfony\Bundle\MakerBundle\Util\ClassSourceManipulator::addSetter(): Argume  
  nt #2 ($type) must be of type string, null given, called in /home/arashdeep  
  /www/raagfinderweb/vendor/symfony/maker-bundle/src/Util/ClassSourceManipula  
  tor.php on line 144  
```

**Comment by weaverryan** [comment]
That’s legit - probably the argument should allow null

**Comment by mdoutreluingne** [comment]
I opened a [PR](https://github.com/symfony/maker-bundle/pull/1176) for fix this issue. I also think that we should allow null for the argument.
