### ISSUE TITLE
 RFE: improvement for default crud

### ISSUE THREAD

**Issue by omgslinux** [symfony/maker-bundle#1177]
Every time a controller class is created by make:, though it works, I need to customize more things than expected, when there could be a single "point of failure". For this, I create a local constant name PREFIX containing the common prefix for naming. So, if I create an example controller named "Company", and do the mentioned work, the diff (using annotations, but it's not very different with attributes) is like this:

```
14c14                                     
<  * @Route("/company", name="app_company_")                                                                                                                             
---                                       
>  * @Route("/company")                                                                                                                                                  
18d17
<     const PREFIX = 'app_company_';
20c19
<      * @Route("/", name="index", methods={"GET"})
---
>      * @Route("/", name="app_company_index", methods={"GET"})
30c29
<      * @Route("/new", name="new", methods={"GET", "POST"})
---
>      * @Route("/new", name="app_company_new", methods={"GET", "POST"})
41c40
<             return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>             return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
51c50
<      * @Route("/{id}", name="show", methods={"GET"})
---
>      * @Route("/{id}", name="app_company_show", methods={"GET"})
61c60
<      * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
---
>      * @Route("/{id}/edit", name="app_company_edit", methods={"GET", "POST"})
71c70
<             return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>             return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
81c80
<      * @Route("/{id}", name="delete", methods={"POST"})
---
>      * @Route("/{id}", name="app_company_delete", methods={"POST"})
89c88
<         return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>         return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);

```

Then, going a bit further, I usually extend this to the templates, by passing an extra PREFIX variable with <code>self::PREFIX</code> as value to every template that has a link to 'app_X_y' in any path (replacing every ocurrence of <code>path('app_X_y')</code> with <code>path(PREFIX ~ 'y')</code>).

This way, there's a single "point of failure", where just setting at the start of the controller class the same value for the constant than the defined name in the router, nothing else has to be changed along the crud files, what is a headache and a lot of work. So, if you find this useful, I'd ask to change the skeleton of the make: generator to produce this result.

Thanks in advance.

**Comment by weaverryan** [comment]
Hi!

I think this is a valid way of doing this. However, it's subjective, and I would not do it this way personally. There are two main reasons. One, the routes are no longer easily "grepable" in my app (e.g. `git grep app_company_delete`) and if I rename a route (e.g. `app_company_index` to `app_company_list`, I'll still break my app, which lessens the benefit of the constants. Second, I'm not sure that tools like PhpStorm's symfony plugin will understand this syntax, which is not the worst, but unfortunate to lose autocomplete on routes, etc.

If I were to use constants, I would 100% use constants for EVERY route name - not just the prefix (and you could even reference the constant inside the `#[Route]` attribute - e.g. `name: self::ROUTE_INDEX`). However, it still wouldn't be very useful in Twig, where at least half of your route references exist.

So, it's a nice idea - but not for maker bundle.

Cheers!
