### ISSUE TITLE
MakeEntity is not compatible with api-platform 3.0

### ISSUE THREAD

**Issue by werwolf666** [symfony/maker-bundle#1198]
Api-platform 3.0 use ApiPlatform\Metadata\ApiResource class instead ApiPlatform\Core\Annotation\ApiResource, but MakerEntity still use it.

**Comment by weaverryan** [comment]
I thought we had fixed this, but apparently not! PR welcome - especially now that API Platform 3 is relased!

**Comment by yobrx** [comment]
Good evening!

I found the problem. https://github.com/symfony/maker-bundle/blob/main/src/Maker/MakeEntity.php use old namespace of ApiResource (≤2.7). 

I can create a PR tomorrow, except if an insomniac is motivated 😉

**Comment by yobrx** [comment]
@weaverryan https://github.com/symfony/maker-bundle/pull/1199 :)

Need help to run the tests locally.
