### ISSUE TITLE
The make: command doesn't run correctly when an entity with annotations has been found.

### ISSUE THREAD

**Issue by tamsirgueye** [symfony/maker-bundle#1212]
Hi
I don't speak english very well, so i write comment in French.

Je travaille sur un nouveau projet avec api-platform. Après avoir mis en place le système d'authentification par le biais de lexik/LexikJWTAuthenticationBundle, j'ai voulu implémenté un système de rafraîchissement de token avec markitosgv/JWTRefreshTokenBundle. Ce bundle génére une entité qui utilise les annotations. Mais cette entité empêche le maker-bundle de fonctionner correctement.

**Comment by weaverryan** [comment]
Google translation, for my sake and others :)

> I am working on a new project with api-platform. After setting up the authentication system through lexik/LexikJWTAuthenticationBundle, I wanted to implement a token refresh system with markitosgv/JWTRefreshTokenBundle. This bundle generates an entity that uses annotations. But this entity prevents the maker-bundle from working properly.

> This bundle generates an entity that uses annotations

If you're using PHP 8 and a new enough DoctrineBundle, it should generate attributes, not annotations. If you are using a new project, I would expect that everything would be "new enough" to use attributes. What version of PHP and Symfony are you using?

> But this entity prevents the maker-bundle from working properly.

Do you get an error?

**Comment by tamsirgueye** [comment]
Google translation
>
First of all thank you for your quick response.
>
> If you're using PHP 8 and a new enough DoctrineBundle, it should generate attributes, not annotations. If you are using a new project, I would expect that everything would be "new enough" to use attributes. What version of PHP and Symfony are you using?
> 
I am using php 8.1 and symfony 6.1.4
> 
> Do you get an error?
>
Yes I get the following error after a make:user
![make command error](https://user-images.githubusercontent.com/96585853/192594348-97727832-ee5c-467c-bb29-80a07179f9c5.png)
>
Here is the incomplete User class generated by the command
```php
  <?php
  
  namespace App\Entity;
  
  use App\Repository\UserRepository;
  use Doctrine\ORM\Mapping as ORM;
  
  #[ORM\Entity(repositoryClass: UserRepository::class)]
  class User
  {
      #[ORM\Id]
      #[ORM\GeneratedValue]
      #[ORM\Column]
      private ?int $id = null;
  
      public function getId(): ?int
      {
          return $this->id;
      }
  }
```
>
The repository is correctly generated
>
If I remove the RefreshToken class generated by the bundle, everything works fine. Here is its content
```php
  <?php
  
  namespace App\Entity;
  
  use Doctrine\ORM\Mapping as ORM;
  use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;
  
  /**
   * @ORM\Entity
   * @ORM\Table("refresh_tokens")
   */
  class RefreshToken extends BaseRefreshToken
  {
  }
```

**Comment by weaverryan** [comment]
Hi!

> But if I completely replace the annotations with attributes I see the error

So if you make `RefreshToken` only use attributes:

```
  namespace App\Entity;
  
  use Doctrine\ORM\Mapping as ORM;
  use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;
  
  #[ORM\Entity]
  #[ORM\Table('refresh_tokens')]
  class RefreshToken extends BaseRefreshToken
  {
  }
```

Then you DO get an error in this situation? Is this the same error that you posted above in the screenshots?

Also, you mentioned:

> If I remove the RefreshToken class generated by the bundle

What command did you run to generate this `RefreshToken` class? There is no support in MakerBundle to generate an entity for this bundle.

**Comment by tamsirgueye** [comment]
Hi, thank you for your feedback 👍 
>
>So if you make RefreshToken only use attributes:
> Then you DO get an error in this situation? Is this the same error that you posted above in the screenshots?
>
Yes of course, and I believe it is due to the parent class using the annotations
>
>What command did you run to generate this RefreshToken class? There is no support in MakerBundle to generate an entity for this bundle.
>
The class is generated with the recipe when installing the bundle
This entity allows you to create the table that will keep the refresh tokens
>
When I add the attributes in addition to the annotations like this, everything works fine
>
```php
  <?php
  
  namespace App\Entity;
  
  use Doctrine\ORM\Mapping as ORM;
  use Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken as BaseRefreshToken;
  
  /**
   * @ORM\Entity
   * @ORM\Table("refresh_tokens")
   */
  #[ORM\Entity]
  #[ORM\Table('refresh_tokens')]
  class RefreshToken extends BaseRefreshToken
  {
  }
```

**Comment by diam** [comment]
Same problème here while migrating a projet from sf2.8->sf3.4->sf4.4 (then I could switch php to php-8.1) and trying to go for sf5.4.
The project make use of old annotation system and the `symfony console make:user`  generate new php annotation.

For helping (the user of) google to find the present issue, I add the error message which only appear here in a screenshot:

`    Cannot find the entity manager for class "App\Entity\User"`

**Comment by cklm** [comment]
I had the same problem (symfony 5.4 on php 8.1) - in my case I'm using a trait from a bundle in an entity which uses annotations. Its not possible to mix annotations and attributes - annotations will be ignored, if there are attributes.

The solution to use the maker-bundle is to have one attribute somewhere in an entity. One attribute is enough to point doctrine to the `App\Entity`-namespace. Then `php bin/console make:user` runs through and the attributes can be removed again.

**Comment by jrushlow** [comment]
I'm going to go ahead and close this - annotation support was dropped a few releases ago. 

For help upgrading entities to use attributes, see the comments in https://github.com/symfony/maker-bundle/issues/1294
