### ISSUE TITLE
Make twig extension with runtime

### ISSUE THREAD

**Issue by 94noni** [symfony/maker-bundle#1222]
Hello

Just an rfc issue regarding using https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions

the idea is that i may imagine the extension the dev is making need as it is described in the doc, some services injected (« basic » extension are already covered)

idea: we can add question to ask for extension/runtime generation and generates 2 files? wdyt?

i can provide a PR if you think this can be usefull
Otherwise feel free to close here

cyao!

**Comment by weaverryan** [comment]
I think this is a better way of doing things, yes :)
