### ISSUE TITLE
Same problème here while migrating a projet from sf2.8->sf3.4->sf4.4 (then I could switch php to php-8.1) and trying to go for sf5.4.

### ISSUE THREAD

**Issue by jrushlow** [symfony/maker-bundle#1229]
Same problème here while migrating a projet from sf2.8->sf3.4->sf4.4 (then I could switch php to php-8.1) and trying to go for sf5.4.
The project make use of old annotation system and the `symfony console make:user`  generate new php annotation.

For helping (the user of) google to find the present issue, I add the error message which only appear here in a screenshot:

`    Cannot find the entity manager for class "App\Entity\User"`

_Originally posted by @diam in https://github.com/symfony/maker-bundle/issues/1212#issuecomment-1261900452_

**Comment by jrushlow** [comment]
@diam I created this as a new issue because I believe you're seeing this problem for a different reason than the user in #1212 

Migrating from `2.8` up through `5.4` is an awesome move! But, doing that with `MakerBundle` is definitely going to be a bit problematic. 

> `Cannot find the entity manager for class "App\Entity\User"`

Is almost always caused by a configuration issue with Doctrine. I would suggest giving the docs a good once over https://symfony.com/doc/current/doctrine.html and make sure your entities and configuration line up with what is detailed in the documentation. 

Ensure your flex recipes are up to date -> https://symfony.com/doc/current/setup/upgrade_minor.html#3-updating-recipes In some cases it may be helpful to force the recipe to be regenerated -> resolve any conflicts -> commit

Another spot in the docs to review would be https://symfony.com/doc/current/security.html#the-user Symfonys security system has changed drastically since Symfony `2.8` 

If you're still having issues, let us know and we can try to help you get this issue resolved!

**Comment by jrushlow** [comment]
Awesome news! One thing I keep forgetting to mention - checkout https://github.com/rectorphp/rector when doing upgrades between symfony / doctrine / php versions.. It comes in really handle to catch alot of the subtle differences between releases. I actually use it in my CI for a couple of projects to give me a heads up if something is likely to change in the future.. of course, everyones mileage may vary...

**Comment by diam** [comment]
Yes, I made use of [rector](https://github.com/rectorphp/rector) a lot, and it was very helpfull for me. But sometime it breaks some special multiline formating (some function call, etc...). So I mainly use it as readonly tool.
