### ISSUE TITLE
Simplify dependency configuration for makers

### ISSUE THREAD

**Issue by sadikoff** [symfony/maker-bundle#123]
Hi all.
The idea is to hide DependencyBuilder from Maker and simplify dependency configuration.
### Exapmle
Now we have:
```php
public function configureDependencies(DependencyBuilder $dependencies)
{
    $dependencies->addClassDependency(
        Route::class,
        'annotations'
    );
}
```
After:
```php
public function getDependencies(): array
{
    return [
        Route::class => ['package' => 'annotations']
    ];
}
```
I understand that it's BC break, but we have #120 which is already a BC break, and we can combine it if community and @weaverryan doesn't mind

**Comment by weaverryan** [comment]
Hey @sadikoff!

What’s the advantage of your proposal? The current implementation allows us to add other methods in the future for different situations. And I like the auto completion :)

**Comment by sadikoff** [comment]
@weaverryan just an idea. For example I have 6 dependencies  in make:crud and I need 6 times to write `$dependencies->addClassDependency(...)` may be we can find better way to simplify it. My initial idea was to write something like:
```php
public function configureDependencies(DependencyBuilder $dependencies)
{
    $dependencies->addClassDependencies([
        [Route::class, 'annotations'],
        [Route::class, 'annotations'],
        [Route::class, 'annotations'],
        [Route::class, 'annotations'],
    ]);
}
```
Or may be we can make `add(...)` like in FormBuilder
```php
public function configureDependencies(DependencyBuilder $dependencies)
{
    $dependencies
        ->addClass(Route::class, 'annotations')
        ->addClass(Route::class, 'annotations')
        ->addClass(Route::class, 'annotations')
        ->addClass(Route::class, 'annotations')
        ->addClass(Route::class, 'annotations')
    ;
}
```

The main advantage is that we will write less code :)

**Comment by javiereguiluz** [comment]
@sadikoff I tend to agree with Ryan here. Even if your proposal is more concise, it could limit us in the future (this is an hypothesis, I don't have specific examples of what else we could do here). Also, the existing config is annoying mostly for the CRUD generator, whose complexity is an edge case. All the other makes are (a lot) simpler. Let's close for now as "won't fix". Thanks!
