### ISSUE TITLE
make:registration-form only works with YAML config (not PHP, XML)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/maker-bundle#1231]
When running `php bin/console make:registration-form`, I'm getting:

> [ERROR] The file "config/packages/security.yaml" does not exist. This command needs that file to accurately build your 
         registration form.

I did the configuration in PHP, so I do have `config/packages/security.php`.

**Comment by jrushlow** [comment]
Howdy @ThomasLandauer - When running `make:registration-form`, maker grabs some configuration values from the `security` config to determine which authentication system the application is running. In your case, that config data exists, but maker doesnt support config file formats other than `yaml`. 

Do you experience the same error when working with other `make:` commands? e.g. `make:authenticator` || `make:reset-password`, etc..

**Comment by ThomasLandauer** [comment]
Yes, `make:auth` gives the same error.
If supporting PHP&XML isn't planned for the next time, then I'd say the error message should explain this:

> [ERROR] The file "config/packages/security.yaml" does not exist. **PHP & XML configuration formats are currently not supported.**

Should I create a PR for this?

**Comment by jrushlow** [comment]
Ya, I like that approach @ThomasLandauer - PR Welcomed.
