### ISSUE TITLE
`make:entitiy`: Suggestion: Add `enumType`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/maker-bundle#1233]
I'm suggesting to add this possible outcome to the wizard:
```php
#[ORM\Column(nullable:true, enumType: Suit::class)]
private ?Suit $suit = null;
```
Maybe via a dedicated `enum` entry in the types list, then by inferring the actual type (i.e. `string` or `int`) from the enum itself.

**Comment by crassaert** [comment]
There was a feature to convert enum strings to value introduced in v1.43.0 but disappeared in v1.44.0, I dunno why ...

https://github.com/symfony/maker-bundle/commit/e09a55be6331346fa46c0e3aabced6ee8c434332
