### ISSUE TITLE
Returns wrong hinted "command" in output when called via Symfony CLI

### ISSUE THREAD

**Issue by magikid** [symfony/maker-bundle#1235]
This is related to symfony/symfony#46705.

When running `symfony make:migration`, the output shows that you should next run `php bin/console doctrine:migrations:migrate` even though the user used `symfony` and not `php bin/console`.  The bundle should detect which was used by the user and return that one in the output.

**Comment by jrushlow** [comment]
Howdy!

Unfortunately we don't have a way to determine if the user typed in `symfony make:migration` or `php bin/console.....` since `symfony make:migration` ultimately calls` bin/console doctrine:migration:migrate`. 

Cheers!

**Comment by jrushlow** [comment]
This will now be possible in the next feature release of the Symfony Binary (5.5+)
