### ISSUE TITLE
Entity generation: switching from return types :self to :static in fluent setters

### ISSUE THREAD

**Issue by florentdestremau** [symfony/maker-bundle#1236]
I figured that with PHP8.0+ we have `: static` as a return type , which is the best option for return type in fluent setters in entities. Can this be updated in place of the `: self` that is currently in use ?

**Comment by mmarton** [comment]
Hi @florentdestremau

This just got released. Can you please add some source here to clarify why static return type is the best option for fluent setters?

**Comment by florentdestremau** [comment]
Hi @mmarton 

- https://blog.smarchal.com/php-self-vs-static (FR)
- https://arueckauer.github.io/posts/2019/11/self-vs.-static/ (EN)

From what I see and get in my own project, there is only advantages for static vs self, as soon as your start mixing interfaces with your entities.

**Comment by mindaugasvcs** [comment]
> Hi [@mmarton](https://github.com/mmarton)
> 
> * https://blog.smarchal.com/php-self-vs-static (FR)
> * https://arueckauer.github.io/posts/2019/11/self-vs.-static/ (EN)
> 
> From what I see and get in my own project, there is only advantages for static vs self, as soon as your start mixing interfaces and traits with your entities.

It's a code smell if you start extending your entities, otherwise there's no point in "static" usage.
