### ISSUE TITLE
make:<object> seems to not work in version 1.1.0  on windows environment

### ISSUE THREAD

**Issue by devikprod** [symfony/maker-bundle#124]
Hi to everybody.
The new 1.1.0 makerbundle return error during object creation ( entity, form, controller etc ).
The version 1.0 work correclty
I'm working under Window 7 and Windows 10 environments
This is the verbose output:

2018-02-21T10:21:45+00:00 [debug] Warning: mkdir(): No such file or directory
2018-02-21T10:21:45+00:00 [error] Error thrown while running command "make:entity -vvv prova". Message: "Failed to create "C:\PHPDevelopment\mrc//C:\PHPDevelopment\mrc\vendor\composer/../../src/Entity""
2018-02-21T10:21:45+00:00 [debug] Command "make:entity -vvv prova" exited with code "1"

In Filesystem.php line 106:

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create "C:\PHPDevelopment\mrc//C:\PHPDevelopment\mrc\vendor\composer/../../src/Entity"

Exception trace:
 Symfony\Component\Filesystem\Filesystem->mkdir() at C:\PHPDevelopment\mrc\vendor\symfony\filesystem\Filesystem.php:682
 Symfony\Component\Filesystem\Filesystem->dumpFile() at C:\PHPDevelopment\mrc\vendor\symfony\maker-bundle\src\FileManager.php:55
 Symfony\Bundle\MakerBundle\FileManager->dumpFile() at C:\PHPDevelopment\mrc\vendor\symfony\maker-bundle\src\Generator.php:162
 Symfony\Bundle\MakerBundle\Generator->writeChanges() at C:\PHPDevelopment\mrc\vendor\symfony\maker-bundle\src\Maker\MakeEntity.php:77
 Symfony\Bundle\MakerBundle\Maker\MakeEntity->generate() at C:\PHPDevelopment\mrc\vendor\symfony\maker-bundle\src\Command\MakerCommand.php:93
 Symfony\Bundle\MakerBundle\Command\MakerCommand->execute() at C:\PHPDevelopment\mrc\vendor\symfony\console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at C:\PHPDevelopment\mrc\vendor\symfony\console\Application.php:883
 Symfony\Component\Console\Application->doRunCommand() at C:\PHPDevelopment\mrc\vendor\symfony\framework-bundle\Console\Application.php:84
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at C:\PHPDevelopment\mrc\vendor\symfony\console\Application.php:241
 Symfony\Component\Console\Application->doRun() at C:\PHPDevelopment\mrc\vendor\symfony\framework-bundle\Console\Application.php:72
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\PHPDevelopment\mrc\vendor\symfony\console\Application.php:143
 Symfony\Component\Console\Application->run() at C:\PHPDevelopment\mrc\bin\console:39

make:entity [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<entity-class>]

**Comment by Pierstoval** [comment]
I also have this kind of issue on Windows with MakerBundle v1.1.0:

```
$ php bin/console make:controller

 Choose a name for your controller class (e.g. BraveChefController):
 > DefaultController

2018-02-21T11:35:57+01:00 [error] Error thrown while running command "make:controller". Message: "Failed to create "E:\dev\www\flex_tests\tests//E:\dev\www\flex_tests\tests\vendor\composer/../../src/Controller""

In Filesystem.php line 106:

  Failed to create "E:\dev\www\flex_tests\tests//E:\dev\www\flex_tests\tests\vendor\composer/../../src/Controller"


make:controller [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<controller-class>]
```

**Comment by weaverryan** [comment]
Thanks guys! Definitely a bug - probably something in FileManager or maybe Generator when we’re trying to figure out the final path. I don’t have a Windows computer, but I’ll check into it. If you guys can do any debugging and see where this bad path is created, that would be awesome :)

**Comment by sadikoff** [comment]
@weaverryan It's in `FileManager`
after calling `getPathForFutureClass` we have relative path:
>D:\test\sf-flex-4\vendor\composer/../../src/Controller/TestController.php
than while dumping file we call `absolutizePath` which generates:
>D:\test\sf-flex-4//D:\test\sf-flex-4\vendor\composer/../../src/Controller/TestController.php

**Comment by sadikoff** [comment]
Fast fix
```php
....
    public function relativizePath($absolutePath): string
    {
       # fix for windows directory separator
        $absolutePath = str_replace('\\', '/', $absolutePath);
....
    private function realPath($absolutePath): string
    {
        $finalParts = [];
        $currentIndex = -1;
        # fix for windows directory separator
        $absolutePath = str_replace('\\', '/', $absolutePath);
....

**Comment by weaverryan** [comment]
Thank you @sadikoff! Very helpful :). I'm working on it in #125 :)

**Comment by weaverryan** [comment]
Hey guys!

Can you verify that the bug is fixed in 1.1.1? We now have AppVeyor running, so hopefully we won't have any future Windows-only surprises like this :).

Cheers!

**Comment by devikprod** [comment]
I'll try in some minutes....depending on my children :-(

Il 21 feb 2018 8:58 PM, "Ryan Weaver" <notifications@github.com> ha scritto:

**Comment by devikprod** [comment]
Hi, it worked for me.
Great work folks!!!

**Comment by weaverryan** [comment]
Beautiful! Thanks for checking :)
