### ISSUE TITLE
Custom command not found

### ISSUE THREAD

**Issue by jdiazgon55** [symfony/maker-bundle#1240]
Hi guys!

I am having an issue trying to create my own `make:...` command. The documentation states:

> in case your applications need to generate custom boilerplate code, you can create your own make:... command reusing the tools provided by this bundle. To do that, you should create a class that extends [AbstractMaker](https://github.com/symfony/maker-bundle/blob/main/src/Maker/AbstractMaker.php) in your src/Maker/ directory. And this is really it!

So I created a `maker-bundle/src/Maker/MakeFront.php` file that extends `AbstractMaker`

```php
final class MakeFront extends AbstractMaker
{
    private $doctrineHelper;
    private $inflector;
    private $frontClassName;

    public function __construct(DoctrineHelper $doctrineHelper)
    {
        $this->doctrineHelper = $doctrineHelper;
        $this->inflector = InflectorFactory::create()->build();
    }

    public static function getCommandName(): string
    {
        return 'make:front';
    }

    public static function getCommandDescription(): string
    {
        return 'Creates CRUD for FRONT entity class';
    }

    public function configureCommand(Command $command, InputConfiguration $inputConfig): void
    {
        ....
    }

    public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator): void
    {
        ...
    }

    public function configureDependencies(DependencyBuilder $dependencies): void
    {
        ...
    }
}
```

I also added to `maker-bundle/src/Resources/config/makers.xml` the following:

```xml
            <service id="maker.maker.make_front" class="Symfony\Bundle\MakerBundle\Maker\MakeFront">
                <argument type="service" id="maker.doctrine_helper" />
                <tag name="maker.command" />
            </service>

```

But, when executing `php bin/console make:front` I get this output:

```cmd

  Command "make:front" is not defined.  

  Did you mean one of these?
      make:auth
      make:command
      make:controller
      make:crud
      make:docker:database
      make:entity
      make:fixtures
      make:form
      make:functional-test
      make:message
      make:messenger-middleware
      make:migration
      make:registration-form
      make:reset-password
      make:serializer:encoder
      make:serializer:normalizer        
      make:stimulus-controller
      make:subscriber
      make:test
      make:twig-extension
      make:unit-test
      make:user
      make:validator
      make:voter
```

Just for your interest, I modified that code directly on the `vendor/symfony/maker-bundle` project. Can you please tell me how to make my custom command available?

**Comment by jdiazgon55** [comment]
It seems that if I copy and paste the file into my own project folder `src/command/FrontCommand.php` it detects it, but I want to add it to the main `maker_bundle` project, inside the vendor folder.

**Comment by jrushlow** [comment]
Howdy @jdiazgon55!

You're on the right track. There are a couple different approaches to achieve what you're trying to do. Starting with the simple version first - If I wanted to add a maker command to a symfony app:

1) `composer require --dev symfony/maker-bundle`
2) Create a new command in `src/Command` e.g. `App\\MyApp\\Command\\MakeFront`
3) `MakeFront extends AbstractMaker` and set the command name to your choosing
4) Configure the command to do what you want it todo
5) run `bin/console your-command-name

You can then copy&paste this command into as many symfony app's as you want or create your own bundle.

This is a bit more complex and outside the realm of MakerBundle itself but I'll get you moving in the right direction:

A) Read the official Symfony documentation on how to create a bundle https://symfony.com/doc/current/bundles.html
B) Checkout the Screen Cast we have to make a bundle over on SymfonyCasts - https://symfonycasts.com/screencast/symfony-bundle
C) In *your* bundle, you'll add MakerBundle as a dependency using `composer require symfony/maker-bundle`
D) Create your command as mentioned above in step 2
E) determine how to distribute your bundle. e.g. using packagist is recommended
F) you can then `composer require --dev your/new-bundle` in as many projects as you want
G) run `bin/console your-command` in those projects

I hope this helps!

**Comment by jdiazgon55** [comment]
Hey @jrushlow, thank you so much for the help! Now it is more clear. Closing this issue.

**Comment by jdiazgon55** [comment]
Just in case it helps. I was even able to make the command work without creating a separate bundle. It seems that you need to clear the cache (I do it with `composer install`) and after that the command will be available to use.
