### ISSUE TITLE
[Serializer] Custom Normalizer broken after upgrading to 6.1

### ISSUE THREAD

**Issue by alexchuin** [symfony/maker-bundle#1252]
### Symfony version(s) affected

6.1

### Description

My custom Normalizer is broken since i've upgraded to Symfony 6.1.
This problem seems to be related to the new Serializer Profiler.

Maybe I forgot something?

Thanks,
Alex

### How to reproduce

Just use this example :

https://symfony.com/doc/6.1/serializer/custom_normalizer.html

### Additional Context

`FileNormalizer::__construct(): Argument symfony/symfony#2 ($normalizer) must be of type Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer, Symfony\\Component\\Serializer\\Debug\\TraceableNormalizer given`

**Comment by ivoba** [comment]
@lyrixx your link does not link a comment :)

I followed this: https://github.com/symfony/maker-bundle/issues/1252#issuecomment-1342478104

    App\Serializer\CustomDenormalizer:
        autowire: false
        arguments:
            $denormalizer: '@serializer.normalizer.object

So i suppose current documentation is wrong?

**Comment by kissifrot** [comment]
Well disabling autowiring can be quite cumbersome if there are many other services injected in the custom normalizer, is there a workaround for for workaround? :stuck_out_tongue:

**Comment by mtarld** [comment]
I think you still can let autowiring enabled and override only the denormalizer argument

**Comment by lyrixx** [comment]
This works well
https://github.com/symfony/maker-bundle/issues/1252#issuecomment-1342477712 

Or use the NormalizeAwareInterface

**Comment by ivoba** [comment]
@lyrixx i think that NormalizeAwareInterface is *not*  working is the actual problem.
Seems that the autowiring is broken with a circular reference problem.

This is why the most comments here recommed to disable autowire as a solution.

**Comment by lyrixx** [comment]
For me it's was OK, since it's a setter.

**Comment by aiibileme** [comment]
When ı added a comment at collect_serializer_data on web_profiler.yaml, it worked.

`when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: false
`

**Comment by gansky-alexander** [comment]
Hello, all ! 

I tried all workarounds and them are not working for me.
Do you have any information about this bug when are you going to fix it ?

What issues i faced:
- circular reference on service registration
- endless loading of the controller

**Comment by mtarld** [comment]
Actually, with a fresh Symfony instance, I managed to make it work.

You can leverage the `NormalizerAwareInterface` like the following:
```php
final class FoobarNormalizer implements NormalizerInterface, NormalizerAwareInterface
{
    use NormalizerAwareTrait;
}
```
```yaml
services:
    App\Serializer\Normalizer\FoobarNormalizer:
        calls:
            - setNormalizer: ['@serializer.normalizer.object']
```

Or using a constructor injection like the following:
```php
final class FoobarNormalizer implements NormalizerInterface
{
    public function __construct(
        private NormalizerInterface $normalizer,
    ) {
    }
}
```
```yaml
services:
    App\Serializer\Normalizer\FoobarNormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object'
```

In either way, you must never use a concrete implementation of any normalizer/encoder in the code, you should inject the interface and configure your container to inject the proper instance. Therefore, IMHO the maker bundle should be updated accordingly.

And if you don't want to specify which normalizer instance to use because you don't care, be aware that the constructor injection won't work because of a circular reference exception (with and without the debug), therefore my advice is to always use the `NormalizerAwareInterface`.

**Comment by gansky-alexander** [comment]
> ```yaml
> App\Serializer\Normalizer\FoobarNormalizer:
>         calls:
>             - setNormalizer: ['@serializer.normalizer.object']
> ```

Got it, thanks !

I tried this approach. You may see my example below:

Symfony 6.2.5 and all related bundles.

services.yaml
```yaml
    App\Serializer\Normalizer\OrderNormalizer:
        calls:
            -   setNormalizer: ['@serializer.normalizer.object']
```

Normalizer itself
```php
<?php

namespace App\Serializer\Normalizer;

use App\Entity\Order;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OrderNormalizer implements NormalizerInterface, NormalizerAwareInterface
{
    use NormalizerAwareTrait;

    private $requestStack;

    public function __construct(
        RequestStack $requestStack
    ) {
        $this->requestStack = $requestStack;
    }

    /**
     * @param Order $topic
     * @param $format
     * @param array $context
     *
     * @return mixed
     */
    public function normalize($topic, $format = null, array $context = [])
    {
        $data = $this->normalize($topic, $format, $context);

        $data['extra_field'] = 'extra data';

        return $data;
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof Order;
    }
}

```

When i export orders i use next in controller
```php
        $query = $orderRepository->getQuery();
        $page = $request->query->getInt('page', self::DEFAULT_PAGE);
        $pageSize = $request->query->getInt('pageSize', self::DEFAULT_PAGE_SIZE);

        try {
            $result = $this->paginator->paginate(
                $query,
                $page,
                $pageSize <= self::MAX_PAGE_SIZE ? $pageSize : self::MAX_PAGE_SIZE,
                ['wrap-queries' => true]
            );
        } catch (LogicException $exception) {
            return $this->json(['message' => $exception->getMessage(), 'code' => Response::HTTP_BAD_REQUEST]);
        }

        return $this->json(
            [
                'result' => $result,
                'pagination' => [
                    'page_size' => $pageSize,
                    'page' => $page,
                    'total' => $result->getTotalItemCount(),
                    'pages_count' => ceil($result->getTotalItemCount() / $pageSize),
                ],
            ],
            Response::HTTP_OK,
            [],
            [
                'groups' => $groups,
                AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true,
            ]
        );
```

Result:
502 Bad Gateway.
If i remove custom normalizer i gets correct data but obviously without 'extra_field'. How can i manage this ?

Looks like ObjectNormalizer injects all normalizers even custom and when i tries to serialize any object ObjectNormalizer went to infinity loop with that.

**Comment by danielburger1337** [comment]
>     public function normalize($topic, $format = null, array $context = [])
>     {
>         $data = $this->normalize($topic, $format, $context);
> 
>         $data['extra_field'] = 'extra data';
> 
>         return $data;
>     }
Infinite reccursion because you call `$this->normalize` instead of `$this->normalizer->normalize`

**Comment by gansky-alexander** [comment]
> ```
> final
> ```

Thank you, missed this !
But infinite reccursion is still here, if i make next all works 
```php
public function supportsNormalization($data, $format = null)
{
    return false;
}
```

if i put next
```
public function supportsNormalization($data, $format = null)
{
    return $data instanceof Order;
}
```
i see 502 error message

**Comment by gansky-alexander** [comment]
I found a solution.

1) Inject object normalizer by myself
```yml
App\Serializer\Normalizer\OrderNormalizer:
    calls:
        -   setBaseNormalizer: ['@serializer.normalizer.object']
            
```
```php
    public function setBaseNormalizer($normalizer)
    {
        $this->normalizer = $normalizer;
    }
```

**Comment by teol** [comment]
Any update on this problem? Looks like it hasn't been fixed yet

**Comment by mdeboer** [comment]
It hasn't been fixed in the sense that there is no fix to be made in the code imho. The docs need to be updated to explain about this issue and how to properly wire up your custom normalizer.

Here is an example on how I do it:

```php
<?php

namespace App\Serializer\Normalizer;

use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

readonly class MyCustomNormalizer implements DenormalizerInterface
{
    private NormalizerInterface&DenormalizerInterface $normalizer;

    public function __construct(
        #[Autowire(service: 'serializer.normalizer.object')] NormalizerInterface&DenormalizerInterface $normalizer,
    ) {
        $this->normalizer = $normalizer;
    }
}
```

Obviously you can replace the `serializer.normalizer.object` service with any normalizer you like.

**Comment by mdeboer** [comment]
I just found out that there is proper documentation for this now:

https://symfony.com/doc/current/serializer/custom_normalizer.html#creating-a-new-normalizer

**Comment by milabron** [comment]
> I just found out that there is proper documentation for this now:
> 
> https://symfony.com/doc/current/serializer/custom_normalizer.html#creating-a-new-normalizer
> 
> If this isn't related to the maker bundle anymore, I reckon this ticket can be closed?

The documentation is not updated. Using the information in the documentation I get deprecated messages and when I try to test the method described in the message I get circular reference, leaving docker unusable.

**Comment by mtarld** [comment]
I think 

> I just found out that there is proper documentation for this now:
> 
> https://symfony.com/doc/current/serializer/custom_normalizer.html#creating-a-new-normalizer
> 
> If this isn't related to the maker bundle anymore, I reckon this ticket can be closed?

I think this PR still needs to be merged: https://github.com/symfony/maker-bundle/pull/1273

**Comment by mdeboer** [comment]
> > I just found out that there is proper documentation for this now:
> > https://symfony.com/doc/current/serializer/custom_normalizer.html#creating-a-new-normalizer
> > If this isn't related to the maker bundle anymore, I reckon this ticket can be closed?
> 
> I think this PR still needs to be merged: #1273

I don't think that is related as that proposes a whole new redesign of the Serializer component.

_Offtopic: I do think that sounds interesting though but would need to dig into the details._

**Comment by chalasr** [comment]
Now that https://github.com/symfony/maker-bundle/pull/1273 has been merged, I think we can close here.

**Comment by clegginabox** [comment]
Sorry to bump an old issue but I've come across a similar/same issue in a custom normalizer when using `DenormalizerAwareTrait`

**Comment by stof** [comment]
please create a new issue with the proper details
