### ISSUE TITLE
native make:crud 

### ISSUE THREAD

**Issue by snipershady** [symfony/maker-bundle#1266]
### Description

With Symfony 6.2 is impossible to use the command `make:crud` without

https://packagist.org/packages/sensio/framework-extra-bundle

BUT
_This package is abandoned and no longer maintained. The author suggests using the Symfony package instead._

So, at the moment, if you want to use `make:crud` a abandoned and no longer maintained package is mandatory.

### Example

`php bin/console make:crud Dummy`

**ERROR] Missing package: to use the make:crud command, run:**                                                            
                                                                                                                        
        ` composer require annotations `

**Comment by lyrixx** [comment]
fixed by #1265 ?

**Comment by jrushlow** [comment]
Yup - #1265 resolves this...

**Comment by rvmourik** [comment]
@jrushlow is it known when this will be present in a tagged release?
