### ISSUE TITLE
Command to create bundles make:bundle

### ISSUE THREAD

**Issue by rela589n** [symfony/maker-bundle#1271]
Hello!
Some applications separate domain logic by bundles (modular monolith). Usually there are quite a few bundles (dozens of), since functionality is decoupled. New bundle creation becomes a tedious work as far as we need to create `Bundle` class, `Extension` class for  `DependencyInjection`, `services.yaml` file and it is necessary to register it in `bundles.php`.

It would be great to have `make:bundle` command, which would automate this process. 

Thank YOU!

**Comment by jrushlow** [comment]
Howdy @rela589n - I'm not sure that `make:bundle` would be a good fit for MakerBundle itself. I completely understand your use case, but typically when creating a bundle - the bundle lives in it's own repository. Symfony stopped recommending to use bundles for code organization back around the Symfony 4.0 release. This feels more like an edge case to me where it would be better for a standalone Symfony CLI Application (w/ or w/o MakerBundle) to handle the grunt work.

We don't have any plans in the foreseeable future to implement such a feature. But if there is strong support for this, we can reevaluate in the future.
