### ISSUE TITLE
XML mapping support for command make:entity

### ISSUE THREAD

**Issue by lobodol** [symfony/maker-bundle#1299]
Hello,

I like very much this bundle, especially the entity generation, which is very convenient.
However, I'd like to use XML mapping, but this seems not supported by the `make:entity` command:

```
[ERROR] Only attribute mapping is supported by make:entity, but the <info>App\Entity\Foobar</info> class uses a different
         format. If you would like this command to generate the properties & getter/setter methods, add your mapping    
         configuration, and then re-run this command with the <info>--regenerate</info> flag.   
```

Doctrine configuration:
```yml
doctrine:
        mappings:
            App:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

Do you plan to support such type soon or late?

Regards,

**Comment by sadikoff** [comment]
As far as I know there was no exact plans to support or not support XML mapping however I think if there will be a good PR then why not?

**Comment by wouterj** [comment]
The maker bundle only supports one format for all its configuration. The reason being that every permutation added to a maker exponentially increases the maintenance costs. We favor supporting a bit more dynamic makers (by interactively asking for information) over supporting many formats.

I'm not fully up to date on all maker bundle maintenance, but I think it it doesn't want to support more formats any time soon.

**Comment by jrushlow** [comment]
@wouterj hit the nail on the head. Going through the transition of `annotation` -> `attribute` mapping was pretty maintenance intensive. Atleast for now, there are no plans to add any additional mapping formats.
