### ISSUE TITLE
Improve InputConfiguration to handle more options

### ISSUE THREAD

**Issue by sadikoff** [symfony/maker-bundle#131]
Hi there. 

May be we can change `InputConfiguration` to handle options like autocomplete and validation? It will help us to simplify custom makers and brings ability to make complex interaction automatically.

Example [changes](https://github.com/symfony/maker-bundle/compare/master...sadikoff:improved-input-configuration)

If no one mind, I will create PR and we can discuss the best way to improve this part of bundle :)

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
