### ISSUE TITLE
native make:crud require the abandoned package "sensio/framework-extra-bundle" 

### ISSUE THREAD

**Issue by snipershady** [symfony/maker-bundle#1320]
With Symfony 6.3, clean setup, is impossible to use the command make:crud without

https://packagist.org/packages/sensio/framework-extra-bundle

BUT
This package is abandoned and no longer maintained. The author suggests using the Symfony package instead.

So, at the moment, if you want to use make:crud an abandoned and no longer maintained package is mandatory.
Example

php bin/console make:crud Dummy

ERROR] Missing package: to use the make:crud command, run:

    ` composer require annotations `

Installing it, anyway... it works fine, but It's weird to receive the deprecation notice

`Package operations: 1 install, 0 updates, 0 removals
  - Installing sensio/framework-extra-bundle (v6.2.10): Extracting archive
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.`

**Comment by weaverryan** [comment]
Hi there!

This will be fixed in the next version - https://github.com/symfony/maker-bundle/blob/4bd486827256eed40a8d7bf1c2af21481ce35918/src/Maker/MakeCrud.php#L327 - which I will hopefully release tomorrow.

Cheers!
