### ISSUE TITLE
Do not flush in the repository

### ISSUE THREAD

**Issue by lyrixx** [symfony/maker-bundle#1327]
ATM, the generated code is:
```php
    public function add(Message $entity, bool $flush = true): void
    {
        $this->_em->persist($entity);
        if ($flush) {
            $this->_em->flush();
        }
    }
```

This is a bad idea:
* it's confusing: one may thing it will flush only the new message (it's not!)
* flush should be done in the most outside layer of the application (controller, command, message handler) to avoid flushing invalid data

**Comment by weaverryan** [comment]
Yea, I think we had decided to remove all of those methods in the repo - I just haven’t had time to do it. PR welcome!
