### ISSUE TITLE
Change the tracking policy by default on entities

### ISSUE THREAD

**Issue by Neirda24** [symfony/maker-bundle#1341]
Hi.

By default each doctrine Entities uses DEFERRED_IMPLICIT which may harm performance and make what I found to be a weird behavior (flush without persist on a known entity applies modification to remote database).

I suggest to add a `ChangeTrackingPolicy(DEFERRED_EXPLICIT)` when running `make:entity`.

Because the `make:entity` generates the repository and a save method that always does a persist, developers either do a manual persist or use this method from the repository. I tend to think this would be an easy win without any cost.

WDYT ?

**Comment by weaverryan** [comment]
Hi there!

> Because the make:entity generates the repository and a save method that always does a persist

This has actually been removed in the last release :).

> I suggest to add a ChangeTrackingPolicy(DEFERRED_EXPLICIT) when running make:entity.

For better or worse, I don't think this is a common practice. For `make:entity`, we need to generate code that is the most common / expected.

So while I think EXPLICIT might be a good option, I don't think we should generate it that way, at least not today.

Cheers!

**Comment by Neirda24** [comment]
Didn't know it was removed indeed. Need to check it out to fully understand what it does and doesn't do now. 

I agree that what is generated needs to be simple enough for everyone to use. On my end, I was coding on symfony for 4 years before I learned that by default doctrine doesn't need to use persist for retrieved entities. So regarding the expected behaviour, I would say it makes sense to change it.

During training we gave at Sensio, we often get asked about this behaviour. Then I have to explain a bit about implicit vs. explicit (which can become very tedious) but the simple fact is: "For any modification you want to see in the database, you need to call persist/remove before flush".

I think it is not common because doctrine doesn't enforce this neither is symfony community through documentation. that would be a first step in the right direction IMO.

Even if we consider external libraries that do entity management, you always have to consider it might be EXPLICIT so you must call persist first. In the end, almost everyone uses it this way. Especially those that are using the maker bundle extensively. I've seen quite some project with entities/repositories auto-generated that doesn't change what was auto-generated except if they really have to.

Please reconsider (I'd be happy to contribute) having this natively and helping spread the word about this great feature.

Thanks again :)
