### ISSUE TITLE
Two methods have disappeared between two commits

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/maker-bundle#1348]
I found something strange in the history of this file : 

File : https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/doctrine/Repository.tpl.php
History : https://github.com/symfony/maker-bundle/commits/main/src/Resources/skeleton/doctrine/Repository.tpl.php

Functions ```public function save``` and ```public function remove``` were available the Jul 6, 2023 but not anymore on the Jul 10, 2023.
Maybe a merge broke something?

- Commits on Jul 6, 2023

> https://github.com/symfony/maker-bundle/blob/dd3208f64ab854e329b6697f4333a4af20d09cf1/src/Resources/skeleton/doctrine/Repository.tpl.php

- Commits on Jul 10, 2023

> https://github.com/symfony/maker-bundle/blob/9907779eaa8c0a7686f0cd5dee1dddfe5c9efab3/src/Resources/skeleton/doctrine/Repository.tpl.php

**Comment by constantable** [comment]
Methods removed intentionally #1328
