### ISSUE TITLE
Generator example from DocBlock will not work

### ISSUE THREAD

**Issue by Antarian** [symfony/maker-bundle#1371]
https://github.com/symfony/maker-bundle/blob/0f060e9ee6fbc79626fef16004a0bb8b0bee32ab/src/Generator.php#L137

In current implementation name either needs to be absolute, or to make it work generator code needs to change.
E.g. change line 150
https://github.com/symfony/maker-bundle/blob/0f060e9ee6fbc79626fef16004a0bb8b0bee32ab/src/Generator.php#L150
to:
```
try {
    Validator::classDoesNotExist($name);
    $className = rtrim($fullNamespacePrefix, '\\').'\\'.Str::asClassName($name, $suffix);
} catch (RuntimeCommandException $e) {
    $className = $name;
}
```
This would have edge case if there is match with class even if $name value is only partial. But that should be very rare.
Like `Prototype\\DummyEntity` may exist and we really want "App\\Entity\\Prototype\\DummyEntity".

**Comment by weaverryan** [comment]
I'm open to a PR!
