### ISSUE TITLE
Remove PhpCompatUtil ?

### ISSUE THREAD

**Issue by smnandre** [symfony/maker-bundle#1374]
PhpCompatUtil is required in the constructor of the following classes since 1.41 / 1.42 it seems
* MakeController
* MakeEntity
* MakeCommand

But since 1.44 instanciating the Generator is deprecated.

And none of those classes uses or calls this object.

Correct me if i'm wrong, but i believe it is not called elsewhere, and as the Command are final and the phpCompat util is private, could it be removed ?

**Comment by weaverryan** [comment]
That looks correct to me 👍

**Comment by weaverryan** [comment]
Yea.... well, let's remove it where we can... but honestly, the class itself may be useful again in the future... or maybe not since we're going to be more strict on PHP versions.

**Comment by jrushlow** [comment]
`make:entity` is the last class that uses the `PhpCompatUtil` and is being removed in the referenced PR. Thinking we're going to keep the util for now as it may be needed again in a future version.
