### ISSUE TITLE
Prevent entity with accentuated names in make:entity

### ISSUE THREAD

**Issue by olberger** [symfony/maker-bundle#1379]
It seems that one can use accents (french ones for instance) in entity names, when using make:entity.

Even though PHP allows it, there are problems afterwards (with Doctrine, SQLite for instance).

It would probably be wise to filter input and refuse problematic characters in class/entity names.

Hope this helps.

And yes, I know... who in their right mind would be designing model entities with french vocabulary... newbees, obviously ;-)

**Comment by weaverryan** [comment]
PR welcome to tighten this up :)

**Comment by vsyrovat** [comment]
IMO issue is not fully resolved, see https://github.com/symfony/maker-bundle/pull/1474#issuecomment-2027716072 for details.
