### ISSUE TITLE
"make:entity" generates string property for attribute "precision" integer needed

### ISSUE THREAD

**Issue by unitize** [symfony/maker-bundle#138]
I created an entity with a decimal field and a precision with 2.
This is what the bundle generated:
`/**
     * @ORM\Column(type="decimal", precision="2")
     */
    private $cost;`

While trying to update the schema i got that error:
> [Type Error] Attribute "precision" of @ORM\Column declared on property App\Entity\Cost::$cost expects a(n) integer, but got string.

I change the string property to an integer and it worked.
`/**
     * @ORM\Column(type="decimal", precision=2)
     */
    private $cost;`

**Comment by weaverryan** [comment]
Yep, that looks legit. Thanks for the report - I’ll fix it as soon as I can (or maybe someone will beat me to it!)

**Comment by thomasisok** [comment]
I'm having the same issue with the length attribute for string types. It generates
`* @ORM\Column(type="string", length="50")`
Looks like maybe part of the same issue?

**Comment by weaverryan** [comment]
Fixed in #139 and tagged in v1.3.1!

Thanks for the report guys!
