### ISSUE TITLE
Handle "forbiden" or dangerous/ambiguous class names in make:entity

### ISSUE THREAD

**Issue by olberger** [symfony/maker-bundle#1380]
It seems that "Collection" for instance, would be a very bad name for an user entity generated by make:entity: Collection, per Doctrine\Common\Collections\Collection is already used for OneToMany relations, for instance... better avoid ambiguity.

However, it seems that there isn't any warning of show-stopper if a user wants to manage a set of collectibles and chose Collection for a Doctrine model entity :-/

I guess it would make sense to have a set of "reserved" names to prevent issues as early as possible.

Hope this makes sense

**Comment by weaverryan** [comment]
PR welcome here also to tighten this up :)
