### ISSUE TITLE
[RFC] Make TwigComponent "not live" per default ?

### ISSUE THREAD

**Issue by smnandre** [symfony/maker-bundle#1395]
## POV

I think i create around 50 TwigComponent for 1 LiveComponent
...but my personal experience may not be enough to claim any general case 😅 

## Current behaviour

During the interaction, the "Make this a live component" defaults to `yes`.

<img width="454" alt="make-twig-component" src="https://github.com/symfony/maker-bundle/assets/1359581/a7972833-fd13-4a68-baa2-f72655082b3b">

Same thing if an arg is given:

```shell
 sf make:twig-component FooBaz   

 Make this a live component? (yes/no) [yes]:
 > n
```

## Suggestion

* use "no" as default (at least when the name is given to the command)
* create another maker dedicated to the LiveComponent

What do you guys think ?

**Comment by jrushlow** [comment]
deferring to @weaverryan as `ux` is more in his wheelhouse

**Comment by weaverryan** [comment]
Agree - defaulting to NOT live makes sense.
