### ISSUE TITLE
Maker entity generate wrong length for string

### ISSUE THREAD

**Issue by MinDBreaK** [symfony/maker-bundle#143]
When generating a string field in the entity, the length option comes like this : 

```php
/**
  * @ORM\Column(type="string", length="64")
*/
```

instead of : 

```php
/**
  * @ORM\Column(type="string", length=64)
*/
```
This causes the following exception : 

> [Type Error] Attribute "length" of @ORM\Column declared on property App\Entity\Foo::$name expects a(n) integer, but got string.

This only happen when using custom values for the string length

**Comment by weaverryan** [comment]
Hi there!

This was fixed in #139. If you upgrade to the latest version and still have issues, let me know!
