### ISSUE TITLE
IDE inspection multiple definitions of tests namespace

### ISSUE THREAD

**Issue by chapterjason** [symfony/maker-bundle#144]
Since the latest updates I've got some issues with the namespace in my IDE (PHPStorm).

I always get the `multiple definitions found for class User` warning, cause I have my own `App\Entity\User` class and the tests also have this namespace. It would be really useful to change the namespaces to something like `Symfony\Bundle\MakerBundle\Tests\Fixtures\Entity\User` in the tests.

**Comment by weaverryan** [comment]
Hmm, yea - I think we should indeed make this change.... we do purposefully use real namespaces in the tests, but we could rename User to something less common (e.g. MakerTestUser).

**Comment by weaverryan** [comment]
See #147

**Comment by chapterjason** [comment]
Thanks 👍🏼
