### ISSUE TITLE
`make:entity` and enums

### ISSUE THREAD

**Issue by klkvsk** [symfony/maker-bundle#1440]
It seems entity generator is unable to handle enums.
On an existing entity class 
```
#[ORM\Entity]
class MyEntity
{
    // ...
    #[ORM\Column(nullable: false)]
    protected MyEntityType $type;
    // ...
```
`make:entity --regenerate` outputs enum's backed type (or is it getting it from mapped field type actually?):
```
    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }
```
Also, when running `make:entity` as a command-line wizard, while creating a property there is no option for enum type.

Quick browse of maker-bundle's code showed [almost nothing about enums](https://github.com/search?q=repo%3Asymfony%2Fmaker-bundle%20enum&type=code). 
Is it really unsupported yet?
Can it be fixed to generate a proper param/return type hint at least?

**Comment by tschmidtdev** [comment]
Im not completly sure for now but if i check the source code it checks for doctrine types and an enum isn´t a doctrine type right now its just an string with an option called enumType. 

So how could we handle it in detail? At the moment all Types are well defined an enum could be an own enum class and could live in a special location /src/enum, /src/myspecialEnums what ever right?

Should we really add this? If we do so how should we handle it? 

Add enum to the *validTypesList
Check is the given *type an enum
Check is there an enum (enum_exists?) ? (But how in which place, maybe ask for a default location for the given enumType? )
Or maybe create an placeholder enum in src/Enum ?
Create the property with the enum class add the Option enumType: EnumClass to it.
Create getter/setter which returns the EnumClass
Add to migrations?

I'm new here and eager to contribute, relying on community support to navigate these enhancements. Open to feedback and additional ideas on improving enum support in MakerBundle.
