### ISSUE TITLE
[BUG] [Make:registration-form] Form errors are not handled

### ISSUE THREAD

**Issue by vlrjuan** [symfony/maker-bundle#1453]
# How to reproduce

Use attribute "no validate" in the registration form.

```
{{ form_start(registrationForm, {
    'attr': {
        'novalidate': 'novalidate'
    }
}) }}

{# ... #}

{{ form_end(registrationForm) }}
```

Nothing appears when clicking "S'inscrire" (no violations or form errors in the debug bar either):

<img width="1080" alt="Capture d’écran 2024-02-16 à 17 00 36" src="https://github.com/symfony/maker-bundle/assets/159065266/e5eefe76-9107-4d3c-a040-4e3fb8e8b498">

Expected behavior :

<img width="1080" alt="Capture d’écran 2024-02-16 à 17 03 08" src="https://github.com/symfony/maker-bundle/assets/159065266/0659ec89-cca6-47d3-9ba4-33d7eaa8825c">

# How to fix

Replace :
```
return $this->render('registration/register.html.twig', [
    'registrationForm' => $form->createView(),
]);
```
with :
```
return $this->render('registration/register.html.twig', [
    'registrationForm' => $form,
]);
```

**Comment by mdoutreluingne** [comment]
I haven't managed to reproduce the bug by starting again with a new project. I have form violations and errors appearing in my form.

However, I've still created a PR to remove the `creatView()` methods, as it's no longer needed to render the form.
