### ISSUE TITLE
Replace `$request->request` by `$request->getPayload()`

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#1454]
It would be interesting to replace `$request->request` with `$request->getPayload()`. The impacted files are:

- https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
- https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/crud/controller/Controller.tpl.php

You can refer to the blog article: https://symfony.com/blog/new-in-symfony-6-3-request-payload

What do you think ?

**Comment by jrushlow** [comment]
at first glance, I'm not opposed to the change. But I also do not know enough about the new `getPayload()` method to say ya! 100% lets do it. A PR is welcome none the less...
