### ISSUE TITLE
Critical error: ClassSourceManipulator

### ISSUE THREAD

**Issue by brianvarskonst** [symfony/maker-bundle#1517]
Hello, 

I created a new Project with PHP 8.3 which is running with ddev, where I wanted to create an new entity with the command `make:entity` alias `ma:en`. After the conforming the step `Can this field be null in the database (nullable) (yes/no) [no]` the error message from the screenshot appears. 

![image](https://github.com/symfony/maker-bundle/assets/53712359/ad4d41c2-b815-4f7b-9be5-56f2285f0225)

I tried to fix the composer autoloading, but the error still shows off and stop the command.

**Comment by jrushlow** [comment]
Hmm, that looks interesting. I'm not familiar with `ddev` aside from knowing it's a docker based dev environment. It sounds like it's using either an outdated || "too new" version of `nikic/php-parser`.

I'm not able to reproduce this locally on a fresh `symfony --webapp` against PHP 8.3. Can you create a https://gist.github.com/ containing your `composer.lock` file and the `require` && `require-dev` sections of your `composer.json`

After creating the gist of your `composer.lock` && `composer.json` try the following:
- run `composer outdated` and show the output here.
- running `composer upgrade -W` to make sure you're on the latest and greatest versions and see if you're getting the same error with the make:entity

**Comment by brianvarskonst** [comment]
Thank you, for the fast response and help. 

The suggested steps from you, resolved the issue for me.

> After creating the gist of your composer.lock && composer.json try the following:
>
> run composer outdated and show the output here.
> run composer upgrade -W to make sure you're on the latest and greatest versions
> run composer dump-autoload && bin/console cache:clear and see if you're getting the same error with the make:entity

Here is the gist (which I created before I run the steps you suggested): https://gist.github.com/brianvarskonst/8fdcf710f7c2d03357d706930942a442

**Comment by brianvarskonst** [comment]
Solved

**Comment by jrushlow** [comment]
Awesome! Glad to hear that.. 

For anyone else that stumbles onto this problem - this was a cache issue. Composer already had the latest version (as of 4/19/24) of `nikic/php-parser` (`5.0.2` per `composer.lock`) && `symfony/maker-bundle` (`1.58.0` per `composer.lock`)

Clear the cache by running: `composer dump-autoload` then `bin/console cache:clear`
