### ISSUE TITLE
make:form fails when using @Embeddable class

### ISSUE THREAD

**Issue by nalekberov** [symfony/maker-bundle#152]
I have an entity User, which contains location property that embeds Location class using @Embeddable annotation, when I issue make:form, and then type User for class name I run into such error:

In ClassMetadataInfo.php line 3325:

  Notice: Trying to get property 'name' of non-object

**Comment by LeJeanbono** [comment]
Can you provide an example with yours classes please ?

**Comment by sadikoff** [comment]
I think this error will be fixed in #149, but embedded fields will not be generated.

**Comment by weaverryan** [comment]
This should be fixed now - you should no longer get an error.

Thanks for the report!
