### ISSUE TITLE
[make:auth] V1.59 - Deprecated classes causes deprecated message on each page

### ISSUE THREAD

**Issue by eltharin** [symfony/maker-bundle#1530]
the trigger_deprecation function before MakeAuthenticator Class make a deprecation message on each called page not just when command make:auth is called : 

Since symfony/maker-bundle v1.59.0: The "Symfony\Bundle\MakerBundle\Maker\MakeAuthenticator" class is deprecated, use any of the Security\Make* commands instead.

can pass the deprecated in interact function ? 

should I make a PR ?

**Comment by jrushlow** [comment]
Howdy @eltharin - yes, If you can submit a PR - I'll get it pushed out in a point release pretty quick. Thanks!
