### ISSUE TITLE
Deprecation : symfony/maker-bundle v1.59.0

### ISSUE THREAD

**Issue by pierrealexaline** [symfony/maker-bundle#1537]
Symfony 7.0.7
PHP 8.3.6
Symfony/maker-bundle v1.59.0
Dev. env.

Message retourned by profiler:

`Since symfony/maker-bundle v1.59.0: The "Symfony\Bundle\MakerBundle\Maker\MakeAuthenticator" class is deprecated, use any of the Security\Make* commands instead.`
Can i just uninstall the `Symfony\Bundle\MakerBundle\Maker\MakeAuthenticator` ? because is now a part of Security ? or wait for fix ? what is the good solution to avoid deprecation ?

Thanks by advance

**Comment by jrushlow** [comment]
Howdy @pierrealexaline - we have a fix already merged to silence the noise about the `make:auth` deprecation. As soon as the tests pass, I'll push out a new release... `composer upgrade` and you'll be all set...

https://github.com/symfony/maker-bundle/releases/tag/v1.59.1
