### ISSUE TITLE
[make:entity] Entity Names Should Be Allowed to Have Digits (i.e. v1)

### ISSUE THREAD

**Issue by jakeschroeder-fountaindigital** [symfony/maker-bundle#1556]
Steps to reproduce:
- Use make:entity with a namespaced classname that includes a digit (i.e., Foo\v1\Bar)
- Observe ASCII error

https://github.com/symfony/maker-bundle/blob/6960c1cc31e8e4f8f1de6b8a139b7867092e5c13/src/Maker/MakeEntity.php#L832

Replace regex in line 832
`
Old = ^[a-zA-Z\\\\]+$
`
`
New = ^[a-zA-Z\\\d]+$
`

Removes duplicated \\ (escaped "\") and adds digit as allowable character.

**Comment by Sayanel34** [comment]
I went from 1.39 to 1.59 and experienced this.
I went down to 1.56 for now and it works again without this error.
Hope it will get fixed, we still need number in namespace for now.
