### ISSUE TITLE
CSRF stateless on skeleton to create the login form

### ISSUE THREAD

**Issue by chadyred** [symfony/maker-bundle#1617]
Hello,

I look at the template to initialize the login form but the default recipe here gimme a little trouble at update (maybe cause of https://github.com/symfony/recipes/pull/1361/files)

The CSRF token of 'authenticate' token id becomes "stateless" ? Some JS seems missing :thinking: because the value have to be replace dynamically ? So, to validate the form with the default configuration at the installation of the 7.2 seems to be broke, FYI I create the form before, and update a few days ago.

https://github.com/symfony/maker-bundle/blob/ce60831a9d6c41c032117ddf59f303f56d004c87/templates/authenticator/login_form.tpl.php#L26

Maybe I miss the Asset Mapper update ? Maybe `#[IsCsrfTokenValid())]` must be used ?

**Comment by nicolas-grekas** [comment]
I'm sorry I don't understand which issue you're trying to describe here. What is the thing that doesn't work as a expected?
I you're wondering whether JS is required for stateless CSRF to work, the answer is no.

**Comment by chadyred** [comment]
I reinstall and update, and all is good. Sry :)
