### ISSUE TITLE
Misspelling in validator

### ISSUE THREAD

**Issue by bestog** [symfony/maker-bundle#169]
https://github.com/symfony/maker-bundle/blob/480783ec9078fef2910cb0901701ef3212e04835/src/Validator.php#L153

does't > doesn't

**Comment by weaverryan** [comment]
Thanks @bestog! :)

**Comment by bestog** [comment]
Sorry, i found two more positions. :)
https://github.com/symfony/maker-bundle/blob/480783ec9078fef2910cb0901701ef3212e04835/src/Validator.php#L170
https://github.com/symfony/maker-bundle/blob/480783ec9078fef2910cb0901701ef3212e04835/src/Validator.php#L174

PS: Awesome Bundle. I love it! 🥇
