### ISSUE TITLE
Add verification for special suffix in Entity

### ISSUE THREAD

**Issue by MinDBreaK** [symfony/maker-bundle#172]
When generating an entity with special words like ```Type``` (actually what have been used), when generating a CRUD will generate incorrect FormType.

For example : 
```php 
class PokemonType ...
```

will have a Form Type : 
```php 
class PokemonType ...
```

However, to be correct, it should be : 
```php
class PokemonTypeType ...
```

There is no information in the documentation (at least in what I found) about suffix that should not be used. 
It should have some kind of verification to either forbid special suffix like ```Type```, ```Controller```.

**Comment by weaverryan** [comment]
Hey there!

Hmm. This makes sense. But I’m not sure there’s anything we can do about it. I don’t want to ask the user any extra questions, and adding the suffix is really nice in almost all situations. But, for sure, this is a weird, but legit edge case. However, unless we can think of a decent solution, I think it’s better to keep the generator just a little imperfect :).

Cheers!
