### ISSUE TITLE
make:* commands dump files to project's root directory if root directory is "/src"

### ISSUE THREAD

**Issue by vitalikaz** [symfony/maker-bundle#182]
I used to create my docker containers by mounting whole the codebase to container's `/src` directory while in dev environment and never had any issues with that. With a "new" symfony directory structure I have something like that in containers:
```
/home
  ...
/etc
  ...
...
/src
|-- /bin
|----  console
|--  /config
|--  /public
|--  /src
|----  /Controller
|----  /Entity
|----  /Repository
|--  /vendor
...
```

and what I've noticed is that when I run `make:*` commands being in my project's root directory (`/src`), all the things are dumped directly to my project's root:

```bash
www-data@c4a3847291f2:/src$ ls  
bin  composer.json  composer.lock  config  docker-compose.yml  infrastructure  public  src  symfony.lock  var  vendor
www-data@c4a3847291f2:/src$ php bin/console make:controller DummyController

 created: Controller/DummyController.php

           
  Success! 
           

 Next: Open your new controller class and add some pages!
www-data@c4a3847291f2:/src$ ls
Controller  bin  composer.json  composer.lock  config  docker-compose.yml  infrastructure  public  src  symfony.lock  var  vendor
www-data@c4a3847291f2:/src$ ls Controller/
DummyController.php
www-data@c4a3847291f2:/src$ ls src/Controller/
www-data@c4a3847291f2:/src$ 
```

So instead of dumping result to `/src/src/Controller/DummyController.php` this command dumps it to `/src/Controller/DummyController.php`.

Didn't have enough time to investigate that (probably we have some bug in `\Symfony\Bundle\MakerBundle\FileManager::relativizePath` ?), but maybe will do it in some near future if nobody else does :)

**Comment by jrushlow** [comment]
this is such an extreme edge case, that i don't think we'll worry about tracking down right now. We are happy to take a look at PR's if someone wants to fix this.
