### ISSUE TITLE
No phpdoc on generated Entities?

### ISSUE THREAD

**Issue by trsteel88** [symfony/maker-bundle#183]
The sensio generator bundle used to generate php doc above each getter/setter when creating an Entity.

The maker bundle doesn't do this and I find myself spending a lot of time re-adding these comments. I find it faster to just create my entity classes manually - making the generator redundant.

Is there a reason that the maker bundle doesn't generate the following?

- @var doesn't appear with the variables
- A comment with the getter/setter (e.g. "Set name" or "Get name.")
- @param string $name on setters
- @return string

Since php7 is now a minimum requirement we should probably have a type hint return type on getters? e.g.

```
/**
 * Get dateCreated.
 *
 * @return \DateTime
 */
public function getDateCreated(): ?\DateTime
{
....
}
```

**Comment by weaverryan** [comment]
Yep, I agree with Nicolas :). We DO want to add doc blocks, return types and type hints, when they add value. About your last point, we *do* have return types on the getter methods, don’t we?

**Comment by trsteel88** [comment]
That makes sense re the not adding them.

I would have thought that it would be good to have the @var with the variables though? Otherwise when you're referring to $this->createdAt within the Entity the IDE doesn't know it is usually a \DateTime. It would only know what $this->getCreatedAt() is a \DateTime object.

I'm 99% sure it didn't generate the :? \DateTime return type when I tried it yesterday. I'll double check it and let you know though.

**Comment by weaverryan** [comment]
That’s true about having an @var above the property itself, at least for objects. I think it might make sense to add that (again, just for objects).

If you don’t see the return type, let me know. It’s easy to check... I just keep chatting you from my phone where I can’t check :)

**Comment by trsteel88** [comment]
I setup a fresh version of sf4 and created two entities. There is no @var annotation on any properties.

You are right that the getters do return the correct type.

https://github.com/trsteel88/sf4-make-entity/blob/master/src/Entity/Invoice.php

https://github.com/trsteel88/sf4-make-entity/blob/master/src/Entity/Item.php

I think if we're going to have @var annotations we should still include it strings (just for consistency). I think a few people might have OCD (mainly myself) and would just have to add it manually haha

**Comment by andrewtch** [comment]
@trsteel88 what IDE are you using? PHPstorm with sf plugin basically guesses type even if you mentioned it year ago in already deleted file )

**Comment by weaverryan** [comment]
This is really subjective. Personally, I’d add the var to objects only, not on scalar properties. What do others think? We can’t make it perfect for everyone, and I don’t want to start including options :)

**Comment by andrewtch** [comment]
As for occam's razor, I vote for including the smallest amount of code to provide autocompletition and static analysis. Thus, if return type and typehints are included, phpdoc is not necessary. 

// This is a commentary

**Comment by javiereguiluz** [comment]
I'm closing here because the latest version of MakerBundle adds return types for both getters and setter and type-hints for all arguments.

The only missing piece would be the PHPdoc for the properties that are objects. However, since we want to keep this bundle simple, I prefer to not add that feature. It won't be that useful (because we encourage using getter/setters and all properties are private) and because in PHP 7.3 (or 8.0) we'll have full property types 🎉 🎉 🎉 and that would be really useful ... and we'll add support for them right away!

Thank you all for the discussion.
