### ISSUE TITLE
Generating entity inside folder eg: Attr\Values, and entity with name Attr already exists

### ISSUE THREAD

**Issue by TioLancaster** [symfony/maker-bundle#192]
I'm trying to generate an entity, using: 

`php bin/console make:entity`

When in the Class name of the entity I put the following value: Attr\Values, and the Attr class already exists, so:
\App\Entity\Attr.php
\App\Entity\Attr\Values.php ( the new one I'm creating ), the following happens:

 

> created: src/Entity/Attr/Values.php
>  created: src/Repository/Attr/ValuesRepository.php
> 2018-05-29T15:47:54+00:00 [error] Error thrown while running command "make:entity". Message: "Call to a member function getName() on string"
> 2018-05-29T15:47:54+00:00 [critical] Call to a member function getName() on string
> 
> In MakeEntity.php line 837:
> 
>   Call to a member function getName() on string

The curious thing, is that the entity is created, nothing is changed on the Attr entity, and if run the command again to edit the entity Attr\Values, everything is fine, and everything works perfectly.

I'm on Windows 10, and running v1.5.0 of maker-bundle.

**Comment by nikophil** [comment]
i have the same troubles : 
- symfony 4.1.0 
- symfony/maker-bundle 1.5.0

on ubuntu

**Comment by LauLaman** [comment]
i got the same problem, 
However when i run the command again for the same Entity i am able to add fields

**Comment by weaverryan** [comment]
Thanks for the report guys! Sorry this bug persisted for a bit - thanks to @nikophil for fixing it :)
