### ISSUE TITLE
Empty root_namespace and validators will fail with Doctrine

### ISSUE THREAD

**Issue by wtorsi** [symfony/maker-bundle#193]
Hi, 
When setting namespace prefix for `MakerBundle` as '', `DoctrineHelper` returns not correct relative paths for entities.

For example, I have this kind of directory structure, without namespace `App` actually.
````
src/
src/User/Entity/User [User\Entity\User]
src/User/Controller/SecurityController [User\Controller\SecurityController]
````
I've already set `maker.root_namespace:''`.
In this case `DoctrineHelper` returns `User\User` as relative path for entityClass and all validators for real namespace of class `User\Entity\User` will fail.

**Comment by javiereguiluz** [comment]
@wtorsi let's ask @weaverryan, who created the great entity generator, if this feature is supported. Maybe it's not, because for the MakerBundle we're very committed to keep things simple, so it's not very flexible about the structure of the app directories. Thanks!

**Comment by jrushlow** [comment]
This is not something that we have planned to implement. However, we will gladly review any PR's that add support for this.
