### ISSUE TITLE
Make:entity --regenerate : OneToOne relationship bug in the setter

### ISSUE THREAD

**Issue by JayPe69** [symfony/maker-bundle#195]
Hello,

I have one entity Organization with a team property
```
class RefOrganization

    /**
     * One Organization has One team
     * @ORM\OneToOne(targetEntity="RefTeam", mappedBy="organization")
     */
    private $team;
```

I have a second entity Team with a Organization property
```
class RefTeam

    /**
     * One Team has one Organization
     * @ORM\OneToOne(targetEntity="RefOrganization", inversedBy="team")
     * @ORM\JoinColumn(name="ORGANIZATION_ID", referencedColumnName="ID", nullable=true)
     */
    private $organization;
```
With the following code, I got a OneToOne relationship between both entities.
However, when lauching the Make:Entity --regenerate to get back all setters / getters, 

In the RefOrganization entity, it generates the following setter for the team :

```
    public function setTeam(?RefTeam $team): self
    {
        $this->team = $team;

        // set (or unset) the owning side of the relation if necessary
        $newOrganization = $team === null ? null : $this;
        if ($newOrganization !== $team->getOrganization()) {
            $team->setOrganization($newOrganization);
        }

        return $this;
    }
```

When creating the RefOrganization without team (as it's nullable), we have an error because of the : 

```
if ($newOrganization !== $team->getOrganization()) 
```
call method getOrganization of null object 

Regards

**Comment by JayPe69** [comment]
```
    public function setTeam(?RefTeam $team): self
    {
      // unset the owning side of the relation if necessary
      if ($this->team !== null && $team === null) {
        $this->team->setOrganization($team);
      } else {
        // set the owning side of the relation if necessary
        if ($team !== null && $this !== $team->getOrganization()) {
            $team->setOrganization($this);
        }
      }
      $this->team = $team;

      return $this;        
    }
```

This code works

**Comment by weaverryan** [comment]
Yep, this looks like a bug in the generated code.

**Comment by elementaire** [comment]
Both codes of the bundle and the proposal of JayPe69 are buggy.

I think, it should be :

```
public function setTeam(?RefTeam $team): self
{
  if ($this->team) {
    $this->team->setOrganization(null);
  }

  if ($team) {
    $team->setOrganization($this);
  }

  $this->team = $team;

  return $this;
}
```

**Comment by JayPe69** [comment]
Yep you are right : 

```
    public function setTeam(?RefTeam $team): self
    {
      // unset the owning side of the relation if necessary
      if ($this->team !== null) {
        $this->team->setOrganization(null);
      } else {
        // set the owning side of the relation if necessary
        if ($team !== null && $this !== $team->getOrganization()) {
            $team->setOrganization($this);
        }
      }
      $this->team = $team;
```

      return $this;        
    }

**Comment by JayPe69** [comment]
yep you are right :)

**Comment by yizhihouzi** [comment]
one year passed,this question has not been resolved!

**Comment by yizhihouzi** [comment]
> yep you are right :), if you keep the current code it could be :
> 
> ```
> public function setTeam(?RefTeam $team): self
> {
>   if ($this->team) {
>     $this->team->setOrganization(null);
>   }
> 
>   if ($team !== null && $this !== $team->getOrganization()) {
>     $team->setOrganization($this);
>   }
> 
>   $this->team = $team;
> 
>   return $this;
> }
> ```

but the team's organization may not be nullable.

**Comment by devozanges** [comment]
it's so weird that this simplistic mistake hasn't been fixed since then. 
There are many ways to do it better...

**Comment by mfu-aroche** [comment]
Bump, similar issue here...

**Comment by CODEheures** [comment]
Always bugged... My solution
```
public function setTeam(?RefTeam $team): self
    {
        // set (or unset) the owning side of the relation if necessary
        $newOrganization = $team === null ? null : $this;
        if ($newOrganization !== $this->team->getOrganization()) {
            $this->team->setOrganization($newOrganization);
        }

        $this->team = $team;

        return $this;
    }
```

**Comment by CODEheures** [comment]
Still bugged... My solution

    public function setTeam(?RefTeam $team): self
    {

       if (!$team && $this->team) {
    		$this->team->setOrganization(null);
	}
       
        $this->team = $team;

        // set (or unset) the owning side of the relation if necessary
        $newOrganization = $team === null ? null : $this;
        if ($team && $newOrganization !== $team->getOrganization()) {
            $team->setOrganization($newOrganization);
        }

        return $this;
    }

**Comment by Kocal** [comment]
Hi :wave: 

I've also faced the issue and this is how I fixed it:
```php
public function setUser(?User $user): void
{
    if ($user === null && $this->user !== null) {
        $this->user->setRegion(null);
    }
 
    if ($user !== null && $user->getRegion() !== $this) {
        $user->setRegion($this);
    }
  
    $this->user = $user;
}
```

This solution prevents:
- an useless `setRegion(null)` when `$user` is not `null`
- an infinite loop if `User#setRegion` is calling `Region#setUser`

I can try to make a PR for fixing this behaviour. I hope there are already tests for this! :smile:

**Comment by hosseinsalemi** [comment]
Same problem, It didn't fix.
version: v1.43.0.
