### ISSUE TITLE
Maker Bundle does not find App namespace

### ISSUE THREAD

**Issue by ahmeier** [symfony/maker-bundle#196]
I have a very strange problem with maker bundle in my symphony 4.1 project. I am using the standard App namespace. The project works fine, no issues with composer update or composer install.

When I try to run bin/console make:entity I get the following warning:

`! [NOTE] It looks like your app may be using a namespace other than "App".
 !
 !        To configure this and make your life easier, see:
 !        https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html#configuration.`

My autoload keys in composer.json are:

> "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },

At this point I am not sure where to start the trouble shooting. I have seen some posts to make sure that the services.yaml file is set up correctly, but I cannot find an error there (App related entries below...):

> 
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/*'
        exclude: '../../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # create aliases for bundle services to make them compliant with symfony 4

    # this listener is required by App\EventListener\MyUserAccessListener
    ApiPlatform\Core\EventListener\ReadListener: ~

    # this service needs to be public as it replaces the
    # API Platform PUT controller for MedicalSchool resources
    App\Action\MedicalSchoolPut:
        public: true

    # this service needs to be public as it replaces the
    # API Platform POST controller for File resources
    App\Action\FilePost:
        public: true`

Any thoughts? Thanks!

**Comment by weaverryan** [comment]
Hmm. Info the maker commands work despite the warning?

At the very least, this looks funny - it could be a bug - the system may incorrectly be thinking your app doesn’t use the App namespace.

**Comment by ahmeier** [comment]
@weaverryan thanks for your input. Unfortunately, even though everything else works, the maker bundle does not. It fails for all commands with:
`Could not determine where to locate the new class "App\Entity\NAME_OF_CLASS", maybe try with a full namespace like "\My\Full\Namespace\NAME_OF_CLASS"`.

Trying adding a full namespace, including the App namespace, fails as well.

I am just not sure where to start troubleshooting this...

**Comment by weaverryan** [comment]
Hmm, interesting.

Could you try to post a small project on GitHub to see if you can replicate it? Do you have any special autoloading happening? 

This is pretty core functionality, so I don’t think it’s broken in general - other people would be having problems. But something special to your setup is causing this behavior (which is likely a bug).

Also, if you want to debug, look at the AutoloaderUtil::isNamespaceConfiguredToAutoload() method and add some dump code there. This is what looks at your autoloading config to see if App is a configures autoload rule.

Cheers!

**Comment by weaverryan** [comment]
Thanks for the update!
