### ISSUE TITLE
Support for configurable Flex directories

### ISSUE THREAD

**Issue by stof** [symfony/maker-bundle#2]
Currently, the generators are hardcoding the `src` folder for the source. But `SRC_DIR` is configurable in Flex.
The bundle should read the configured value in the composer.json instead, to account for Flex configuration.

**Comment by GromNaN** [comment]
Isn't it just getting or injecting `SRC_DIR` in the FileManager ?
https://github.com/symfony/maker-bundle/blob/master/src/FileManager.php#L31

**Comment by cfoehrdes** [comment]
Is the hardcoded App Namespace not a similar issue? I was a bit shocked that we would be forced to an "App" prefix for our entire application src if we want to be able to use the makers. And moving the business logic out of src is not really an option, tbh.

**Comment by stof** [comment]
Well, Flex itself does not support changing the namespace (as it would force to make all recipes much more complex than just copying some files).. This is why the scope of the initial request here is to support what is supported on the Flex side.
