### ISSUE TITLE
Adding $generator->appendToFile() method

### ISSUE THREAD

**Issue by Skandalik** [symfony/maker-bundle#208]
Hi,
When doing project that's already on the SF4, but still a lot of old config files are not using autowire and autoconfigure (sometimes because of another bundle) and I realized that MakerBundle doesn't allow to append generated code to files.

Example:
I create `ExampleNewStrategy` class and register it as a service in the let's call this `main_strategy.yml` file.

Generator class allows only to generate new files. Appending to files would be useful as well.

**Comment by weaverryan** [comment]
Hi there!

Can you tell me a bit more about what you’d like to do? Do you want to create a custom generator command to your project? And which file in your example would you want to generate?

Cheers!

**Comment by Skandalik** [comment]
Let's say I have three classes that have services defininiton in `main_strategy.yml` file.
```
services:
   App\Example\FirstStrategy: ~
   App\Example\SecondStrategy: ~ 
   App\Example\ThirdStrategy: ~
```
I want to create `FourthStrategy` using custom command with MakerBundle, let's call it `ExampleStrategyMaker` and it should create `FourthStrategy` class, and register it in `main_strategy.yml` (append another definition under the `App\Example\ThirdStrategy: ~`). From what I've seen, there is no possibility to append templates to files, just generating new ones.

**Comment by Skandalik** [comment]
FIY I created a PR: https://github.com/symfony/maker-bundle/pull/210

**Comment by jrushlow** [comment]
Closing this issue for now, see https://github.com/symfony/maker-bundle/issues/814 for additional context in regards to makers for services. If you have any questions, please let us know! Thanks @Skandalik
