### ISSUE TITLE
make:controller - twig filename $controllerName.html.twig instead of index.html.twig

### ISSUE THREAD

**Issue by kshishkin** [symfony/maker-bundle#217]
This command only creates two files. If their name bodies matched, it would be easier to 

- navigate using search tools
- refactor

It would make semantic sense as well.
Since it brakes compatibility promise we could make it parametrised with index as default but in a long run the matching name might bring the tool into wider use.

**Comment by LeJeanbono** [comment]
It's a best practice to name the 'main' twig file of a controller `index.html.twig` in the folder

**Comment by kshishkin** [comment]
No problem, we can call the new approach best practice as well once we
adopt it

**Comment by brucep** [comment]
The directory is superfluous if you only have one template in a controller.

**Comment by kshishkin** [comment]
That is true, I'm guessing we have to have a folder now just because the main file gets called "index" by default.

While this is ok with several views, once your app gets bigger you have a lot of "index" files where the name means nothing. If we moved away from this we could resign from folder to further simplicity. 

The folder makes more sense with CRUD generator, but even there the main file could be just plural of the entity. The things have names for purpose.

**Comment by jrushlow** [comment]
I don't foresee this happening. Currently, make:controller generates a template folder (named after the controller) and the `index.html.twig` template within that folder. As @LeJeanbono pointed out, `index.html.twig` is the best practice here. Using `xyz_controller.html.twig` or some variation there of wouldn't make much sense..

Thanks!
