### ISSUE TITLE
The make:migration doesn't execute a doctrine:migrations:diff

### ISSUE THREAD

**Issue by sinner** [symfony/maker-bundle#223]
After you create an Entity using the `make:entity` this suggests us to execute the command `make:migration`, even within the documentation.

But this command `make:migration` doesn't execute a `doctrine:migrations:diff` then it generates a migration with errors because it isn't taking into account the tables already generated by the previous entity definitions then it adds SQL sentences to create fields or tables already created.

I think it must not suggest using this command and suggests to use `doctrine:migrations:diff` instead.

**Comment by LeJeanbono** [comment]
Hi sinner,
`make:migration` do a `doctrine:migrations:diff`, see : https://github.com/symfony/maker-bundle/blob/fe8c5e98c1814a97d12bd392c845ed12652b625c/src/Maker/MakeMigration.php#L74

**Comment by sinner** [comment]
My bad. It wasn't executing the doctrine:migrations:migrate before doing it.
