### ISSUE TITLE
FEATURE: Migrations should be put in a subfolder depending on database engine

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/maker-bundle#225]
It may be necessary to allow the user to choose the database engine they use. At the moment, `make:migration` puts all migrations into the `migrations` folder. I think it would be better if migrations were put in sub folders depending on the engine used. e.g. `Migrations/mysql/`, `Migrations/sqlite/`, `Migrations/postgres/` etc. so then any installation code could ask and choose the necessary migrations.

**Comment by xabbuh** [comment]
I don't think this is usually the desired behaviour. In the typical application where you would be use the maker bundle you do not support different database engines. This means you would end up with just a single subdirectory here which is probably too confusing.

**Comment by ChangePlaces** [comment]
I partially agree that only one db engine will be used in most cases, but if that's the case, why is symfony so strongly tied to a DBAL? It doesn't agree with Doctrine's use-case.

**Comment by xabbuh** [comment]
I am not sure I understand your reasoning here. Regarding DBAL, most developers using Symfony will probably also not use it directly anyway. They will use the ORM as it makes it so easy to map your domain model to the database. The ORM in turn indeed uses the DBAL. But that's an implementation detail developers do not need to care about most of the time.

**Comment by ChangePlaces** [comment]
My reasoning is end-users may wish to choose a database engine, which is entirely possibly if using doctrine as it's db agnostic.

**Comment by xabbuh** [comment]
Sure, and that's what they do. But they will usually not support many different database engines in one single application. That's why I'm my opinion having a subdirectory would be rather disturbing for the common case than offer any advantage.

**Comment by jrushlow** [comment]
I do not foresee this happening for the reasons stated by @xabbuh. Thanks @ChangePlaces for the suggestion!
