### ISSUE TITLE
Attempting command make:entity causes error "An option with shortcut "a" already exists."

### ISSUE THREAD

**Issue by stphane** [symfony/maker-bundle#228]
Attempting `bin/console make:entity …` triggers the following error  *(See backtrace down below)*:

> An option with shortcut "a" already  exists.

Searching vendor directory for pattern `->addOption\(.+(['"])a\1` returned the following entries:  
*vendor/symfony/maker-bundle/src/Maker/MakeEntity.php*:75  
  → `->addOption('api-resource', 'a', …`
*vendor/doctrine/doctrine-cache-bundle/Command/DeleteCommand.php*:26
  → `->addOption('all', 'a', …`

To temporarily circumvent the issue I simply replace `'a'` with `null` in MakeEntity.php.

---

**Context**  
*Symfony 4.1, Symfony/maker-bundle (require ^1.3 ; installed 1.5.0 )*  
*Adding `-vvv` option to the command line adds the below backtrace:*

> Exception trace:
 Symfony\Component\Console\Input\InputDefinition->addOption() at /var/www/back-portal/vendor/symfony/console/Input/InputDefinition.php:222
 Symfony\Component\Console\Input\InputDefinition->addOptions() at /var/www/back-portal/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->mergeApplicationDefinition() at /var/www/back-portal/vendor/symfony/console/Command/Command.php:206
 Symfony\Component\Console\Command\Command->run() at /var/www/back-portal/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /var/www/back-portal/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/back-portal/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/back-portal/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/back-portal/src/Component/MultiApp/MultiAppConsoleApplication.php:35
 Component\MultiApp\MultiAppConsoleApplication->doRun() at /var/www/back-portal/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/back-portal/bin/console:46

**Comment by LeJeanbono** [comment]
Hi,
Thanks for the issue, shortcut `api` for `api-resource` could be an reasonable fix ?

**Comment by LeJeanbono** [comment]
@stphane  Not reproduced with `make:entity MyEntity -a`

**Comment by jrushlow** [comment]
Closing this for now. If you're still experiencing this issue, please try `composer update` and let us know any additional context. Thanks!
