### ISSUE TITLE
make:crud to make basic tests for each route

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/maker-bundle#229]
When running a `make:crud` command, it'd be handy if this command could scaffold tests that check for a valid 200 status for each route. e.g. `tests/Functional/Controller/FooTest` as a framework for checking the urls.

**Comment by lyrixx** [comment]
How could it work for routes with an Id ? like `/books/{id}` ?

**Comment by ChangePlaces** [comment]
@lyrixx it could create the code, but comment it out, leaving it up to the creator to implement it.

**Comment by lyrixx** [comment]
Good idea !
