### ISSUE TITLE
make:migration to output using the schema builder, rather than sql?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/maker-bundle#230]
Is there any reason why direct SQL is output in a migration, instead of the schema buider? Using the schema builder would help keep the migrations abstract across db engines.

**Comment by weaverryan** [comment]
Hi there!

We just wrap the Doctrine migrations library. Here is the conversation about why they use raw SQL instead of the schema builder tools: https://github.com/doctrine/migrations/pull/79

Cheers!
