### ISSUE TITLE
"make:command" leads into "Could not determine where to locate the new class"

### ISSUE THREAD

**Issue by SebTM** [symfony/maker-bundle#231]
I'm trying to get maker working with a new Symfony 4.1 installation. I've created it using composer, changed the "App"-Namespace to "MakerTest" (see composer.json) and configures maker to use "MakerTest" as root-namespace.

composer.json:
```
    "autoload": {
        "psr-4": {
            "MakerTest\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "MakerTest\\Tests\\": "tests/"
        }
    },
```

config/packages/maker.yaml:
```
maker:
  root_namespace: MakerTest
```

Output:
```
root@xyz:/var/www/# bc make:command

 ! [NOTE] It looks like your app may be using a namespace other than "MakerTest".
 !
 !        To configure this and make your life easier, see:
 !        https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html#configuration.

 Choose a command name (e.g. app:delicious-chef):
 > create-user


In Generator.php line 43:

  Could not determine where to locate the new class "MakerTest\Command\CreateUserCommand", maybe try with a full namespace like "\My\Full\Namespace\CreateUserCommand"


make:command [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]
```

Tried it with latest stable and also dev-master - same issue with both.

**Comment by QuentinSu** [comment]
Some news ? I have the exact same issue! Thanks

**Comment by SebTM** [comment]
Unfortunately not, I just created the commands manually.

**Comment by fritzmg** [comment]
Did you guys rebuild the application cache and do a `composer dump-autoload` after changing the config?

**Comment by SebTM** [comment]
@fritzmg Thanks for the support - I can't reproduce the problem anymore but potentially your answer  help other people having this issue :)
