### ISSUE TITLE
make:entity in my Location. 

### ISSUE THREAD

**Issue by CodeScroll** [symfony/maker-bundle#247]
How can i generate the entity in my own Bundle ?? For example ( image, folder structure url -> https://prnt.sc/kk96i1 ).

I have UserBundle. By making "make:entity \User\Entity\User" , The command generates the file "User.php" at the desirable location( App/User/Entity). But the "UserRepository.php" created at the App/Repository, when the desirable is at App/User/Repository. In a few words, how can i generate the entity with the symfony 3.4 style "MyBundle: EntityName" ? Thanks

**Comment by ckrack** [comment]
>>Also, why the User.php class generated at App/User/Entity and the UserRepository.php at App/Repository/ ?

That's related to autoloading of services.

**Comment by jrushlow** [comment]
Related to #51 - Closing this issue for now. In general - maker follows the directory Symfony's directory structure when generated classes.

**Comment by sovetski** [comment]
+1 for this, it should accept a parameter or something else to give the ability to change it, or easiest way, when a namespace is detected in the Entity name, just respect it..
