### ISSUE TITLE
maker:crud / Controller.tpl.php / redirect edit route after update

### ISSUE THREAD

**Issue by MUbedaSJ** [symfony/maker-bundle#257]
Hello,
Thanks you very much, for your "magic" bundle, very useful...
It seem redirect edit route after update is not correct, on this line : 

https://github.com/symfony/maker-bundle/blob/22a9bf33868f0fed6cab013fe5231e8485d15e20/src/Resources/skeleton/crud/controller/Controller.tpl.php#L81

On success update, redirected route should be **"_view"**  or **"_index"** page like this :

        return $this->redirectToRoute('<?= $route_name ?>_view', ['<?= $entity_identifier ?>' => $<?= $entity_var_singular ?>->get<?= ucfirst($entity_identifier) ?>()]); 

or

        return $this->redirectToRoute('<?= $route_name ?>_index');

**Comment by LeMonkii** [comment]
I think that it should redirect to the same route (edit) and that the new route should also redirect to the edit route (or at least show).
But if the community thinks that this is a bad idea the now useless parameter in the edit/redirect should be removed.


 ```
return $this->redirectToRoute('<?= $route_name ?>_index', [
    '<?= $entity_identifier ?>' => $<?= $entity_var_singular ?>->get<?= ucfirst($entity_identifier) ?>(),
]);
```
should be 

`return` $this->redirectToRoute('<?= $route_name ?>_index');`
