### ISSUE TITLE
Is it possible to overwrite an existing entity by making bidirectional a relation ?

### ISSUE THREAD

**Issue by maidmaid** [symfony/maker-bundle#264]
The diff would be something like :

```diff
/** @Entity */
class Product
{
    /**
-     * @OneToMany(targetEntity="Feature")
+     * @OneToMany(targetEntity="Feature", mappedBy="product")
     */
    private $features;
}

/** @Entity */
class Feature
{
+    /**
+     * @ManyToOne(targetEntity="Product", inversedBy="features")
+     */
+    private $product;

+    // getter/setter
}
```

**Comment by jrushlow** [comment]
See https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/association-mapping.html#one-to-many-bidirectional for additional details about how doctrine handles OneToMany's. 

At the persistence level, `Feature` would have a column `product_id` which would reference a `Product`'s primary key. If you called `$feature->setProduct($product)` this would create / set the `product_id` on the `feature` column. Nullable rules would come into play here. If a features product cannot be nullable, you would have to implement logic to handle that case either in the `setProduct()` method or else where in your business logic.

I hope this helps. Feel free to reach out if you need additional help.. Thanks @maidmaid!
