### ISSUE TITLE
make:crud XType (or XController)

### ISSUE THREAD

**Issue by adricorse** [symfony/maker-bundle#270]
I tried to execute this command except that it did not work as expected ...
make:crud XType
When command make:crud ends with "Type", the form isn't created correctly. (XType.php instead of XTypeType.php).
Bug may be reproduced with "Controller" instead of "Type".

**Comment by sadikoff** [comment]
I don't think that this is a BUG. It's some kind of feature. If you follow the examples, you should use `XTypeType` and `YourControllerController` and you will get what you want.

**Comment by sadikoff** [comment]
@adricorse Oh, this make sense, sorry for my little misunderstanding.

**Comment by adricorse** [comment]
@sadikoff , no problem, maybe it was missing an example ^^

**Comment by sadikoff** [comment]
@adricorse, I confirm that it's unexpected command behavior. I'll try to fix it in #241, if it's possible
