### ISSUE TITLE
Explicitly wire services and arguments 

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#28]
As a chore, we should remove service autowiring and auto-registration.

There are 2 reasons:

A) make the bundle faster in dev (no autowiring)
B) give the services non-class ids (no auto registration + use traditional-style ids) so that the commands don’t display in debug:autowiring

**Comment by nicolas-grekas** [comment]
To who may wonder: "faster in dev" applies to compiling the container only. Autowiring adds not overhead at runtime, dev or not.

**Comment by javiereguiluz** [comment]
Closing as already fixed.
