### ISSUE TITLE
Remove case-sensitivity on entity property types in make:entity

### ISSUE THREAD

**Issue by pschaub** [symfony/maker-bundle#288]
The command ``make:entity`` asks you about the type of the entity property.

If you enter the type ``Manytomany`` instead of ``ManyToMany`` it will not work.

````
 [ERROR] Invalid type "Manytomany".
````

I think the script should ignore the case-sensitivity on entity property types.

**Comment by javiereguiluz** [comment]
Or replace it by a choice so the user can't type it, only select it?

**Comment by jrushlow** [comment]
I'm closing this as it is possible to enter `?` to see all available field types for the question:
![image](https://user-images.githubusercontent.com/40327885/108180478-d262cc80-70d4-11eb-823b-c4fec7eeac8d.png)

Thanks @pschaub
