### ISSUE TITLE
Add command to generate Repository from existing entity

### ISSUE THREAD

**Issue by aequasi** [symfony/maker-bundle#292]

**Comment by aequasi** [comment]
Well, honestly, having `make:entity` generate repositories seems to violate SOC. This` command also alters the entity, adding methods that i don't want/need.

Besides that though, having a shortcut method for just creating repositories would be nice.

**Comment by aequasi** [comment]
Just to iron out my thoughts a little more:

It seems to me, having `make:entity` generate more than just entities is a little strange. IMO, it would make more sense to have a `make:repository` command that `make:entity` could offer to call at the end (if the user wants to).

This command would go through the entities (either by namespace, or by repo name?) and generate repositories. If there is a matching entity, it could tie the two together (add a repositoryClass to the entity).

Example call: `./bin/console make:repository App\Repository\UserRepository --entity=App\Entity\User`
or: `./bin/console make:repository App\Repository --entityNamespace=App\Entity`

If there was no matching entity, it would require the user to edit the entity's `repositoryClass`

**Comment by javiereguiluz** [comment]
@aequasi although you are right technically speaking, the target audience of this bundle is used to generate an entity + associated repository for it. When we designed the Makerbundle we decided to focus on ~80% of Symfony users. In this bundle we don't care about the other advanced users ... because probably they would never use this bundle anyways (believe it or not, we've received insults from some of those people and the've made fun of us just for creating this bundle).

So let's close this proposal and keep the the existing behaviour for now. Of course, even if this proposal didn't make it, we appreciate your issue and your willingness to help us improve this bundle. Thanks!

**Comment by aequasi** [comment]
Well, the changes i'm proposing wouldn't change anything for the existing users, and wouldn't alienate the more advanced users that would like to separate the two.

I *want* to use this bundle, but i can't because options like this aren't provided.

**Comment by javiereguiluz** [comment]
@aequasi although I haven't changed my mind about this, I'm reopening so @weaverryan can decide if we should implement this after all ... or if it's OK to close it as "won't fix". Thanks!

**Comment by jackbentley** [comment]
Personally, I think the arguments @aequasi put forward make complete sense. I don't see any reason not to implement this.

**Comment by gsylvestre** [comment]
That `make:repository` command would be very useful after you generate entities from an existing database. I think that command should create the same repo as the `make:entity` command does + add the `@ORM\Entity(repositoryClass="")` attribute in the Entity if missing.

It is time consuming for beginners to create all the repositories manually, and it is _really_ easy to forget to add the attibute in the annotation.

**Comment by gsylvestre** [comment]
Or maybe this should happens in the `make:entity --regenerate` command? That could work even better.

**Comment by xavierdever** [comment]
Please add this

**Comment by pittoul** [comment]
Please.....

**Comment by heardofdezz** [comment]
Yea the team should really think about implementing a make:repository that mimics make:entity behavior that @gsylvestre mentionned, i tho it wasnt very necessary until i generated my entities via an external database that had more then 30 tables, manually going thru all the entitie files to add `@ORM\Entity(repositoryClass="") ` and creating each file manually is super time consuming and defnetly prone to error im a human not a machine (unfortunate). Its not about being an advanced coder or junior but just having a practical command to avoid alot of messes and time consuming behavior that can be implemanted... thats my take on it, i really hope the team at symfony are indulgent and understanding.

**Comment by klemens-u** [comment]
Related: in a fresh symfony5 project with existing database:

Generate entities with annotations:

`php bin/console doctrine:mapping:import "App\Entity" annotation --path=src/Entity`

Now we want to create getter/setters + repositories:

`php bin/console make:entity --regenerate App`

Bummer: no repositories are created. Why?

We need to manually add the following to the annotation:

'@ORM\Entity(repositoryClass="App\Repository\BeerTypeRepository")`

Only then repos are generated with `make:entity`

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!

**Comment by awsms** [comment]
Is there currently a way to regenerate a repository from an existing entity, even with a third-party lib?
