### ISSUE TITLE
Namespaces and repository classes

### ISSUE THREAD

**Issue by egorzot** [symfony/maker-bundle#31]
Some questions:

1.  Is that possible to create entities or controllers with namespaces?
2.  How to disable creating repository class while making doctrine entity?

**Comment by piotrgradzinski** [comment]
Hi @egorzot! As far as I can see for the `make:entity` command there is no option to parametrise it. So on the command level you can't change namespace for new entity or disable creating repository class. 

You can do this on your own when entity/repository is created. 

In terms of the namespace for entity - `App\Entity` is a default namespace also repository is created by default. If you have different project structure you can change namespace after creation and remove repository along with removing repository param in entity annotation.

I hope this makes sense for you and answers your question.

**Comment by weaverryan** [comment]
We've just closed #40: there will *not* be a way to generate an entity without a repository. We want to be as helpful to most people as possible, but we can't make everyone happy :). Of course, you can always add your own maker command for your own needs!

We *may* make the namespace configurable. We'll follow whatever happens on symfony/flex#196

**Comment by egorzot** [comment]
@weaverryan no problem, thanks for answering.
