### ISSUE TITLE
Change template of skeletons when run command?

### ISSUE THREAD

**Issue by eugenekurasov** [symfony/maker-bundle#32]
I have a question:
Why we can't configuration path to template of different commands?
For example to pass option path_to_skeleton.

**Comment by javiereguiluz** [comment]
@eugenekurasov thanks for asking about this feature. It was on my TODO list, so I've created #33 to explain why this doesn't work and discuss about the possible alternatives. Thus, I'm closing this issue in favor of the other one. Cheers!
