### ISSUE TITLE
[RFC] Allow to override the skeleton files?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/maker-bundle#33]
When creating this bundle we decided to not require Twig to keep things simple. That means that our skeleton files can't have complex logic and we need to interpolate the placeholder variables ourselves. Not a big deal ... but not using Twig and not defining skeleton files as Twig templates has another problem...

... you can't easily override the skeleton files in your project (see #32 and lots of related issues in the SensioGeneratorBundle). Should we...

... add Twig as dependency and turn skeletons into templates?
... try to make the skeleton files overridable using the kernel file locator ?
... not support this feature explicitly?

**Comment by yceruto** [comment]
> add Twig as dependency and turn skeletons into templates?

:+1: adding logic to the skeleton template (like conditional code) look good to me and solve ideas like described by @weaverryan here https://github.com/symfony/maker-bundle/pull/22#issuecomment-345499964

**Comment by weaverryan** [comment]
I disagree with adding Twig as a dependency. I don't want API-only projects to end up with a `templates/` directory just so they can generate some guard authenticators or something else.

And I also don't think that our templates should be overridable - and opinion that I'm sure won't make me very popular with some people :). Making a generation command is very easy, and you can even extend from our `AbstractCommand`. If you want a different template for a generator, I think you should just create your own command.

**Comment by eugenekurasov** [comment]
@weaverryan so if I need add for example add to top
```
<?php declare(strict_types = 1); 
....
```

I need copy of exist command with change only skeleton? If I don't need change logic or add new variables, I think is violates the principle DRY, isn't it?

So I think I need have some solution when we need change only template.

**Comment by yceruto** [comment]
What about a `FilesystemLoader` able to find skeleton templates across defined `paths`?

Initially we have these paths (DI extension):
 * addPath: '%kernel.root_dir%/Resources/MakerBundle/skeleton' (if available, for overriding purpose)
 * addPath: The bundle 'Resources/skeleton' (always)

This would change the way skeleton templates are loaded so commands `getFiles()` should return relative path for us, abs or relative in userland:
```php
return [
    'security/Voter.php.txt' => '...',
];
```
Thus, we can override any skeleton without much effort, the user just need create a skeleton file here:
```
src/
  Resources/
    MakerBundle/
      skeleton/
        Controller.php.txt (this will override the default one for `make:controller` cmd with Twig dep.)
```
What do you think?

**Comment by yceruto** [comment]
What about a `FilesystemLoader` able to find skeleton templates through defined `paths`?

Initially it would have these paths (DI extension):
 * addPath: `%kernel.root_dir%/Resources/MakerBundle/skeleton` (if available, for overriding purpose)
 * addPath: The bundle `Resources/skeleton` (always)

It would change the way skeleton templates are loaded so commands `getFiles()` should return relative path for us, abs or relative in userland:
```php
return [
    'security/Voter.php.txt' => '...',
];
```
Thus, we can override any skeleton without much effort, the user just need to create a new skeleton file (with the same name of course) here under `src/Resources/MakerBundle/skeleton/` or maybe _better_ in `config/maker/skeleton/`:
```
src/
  Resources/
    MakerBundle/
      skeleton/
        Controller.php.txt (this will override the default one for `make:controller` cmd without Twig dep.)
```
What do you think?

**Comment by yceruto** [comment]
Look at this https://github.com/yceruto/maker-bundle/commit/c0f72a9c3ee0db45dfa48a5e9b87b94672a84241 tested and working! Let me know about to submit the idea ;)

**Comment by yceruto** [comment]
See another version (simplified) https://github.com/symfony/maker-bundle/pull/50

**Comment by weaverryan** [comment]
> @weaverryan so if I need add for example add to top

```php
<?php declare(strict_types = 1); 
....
```

For now, yes. We have a tricky balance to strike: if we make the bundle very extendible, then we need to be much more careful when adding/changing features so we don't break those extensions. By saying "create your own custom commands", the bundle can stay innovative. We learned this lesson with SensioGeneratorBundle. Of course, if you want to make your own command, we should make it as easy as possible. Right now, it's pretty easy, since we have the `AbstractCommand`, but perhaps we could make it even easier.

**Comment by eugenekurasov** [comment]
So problem only with BC, if it is so this is another problem. I don't give solution for this issue now, but you can see how trying resolved same issue in [doctrineMigrationsBundle](https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/DependencyInjection/Configuration.php#L34) - they give option for override they skeleton. I think you can found other solution.
So yes it's not easy to find the right solution but this is not good solution create new commands.

**Comment by yceruto** [comment]
Could be https://github.com/symfony/maker-bundle/pull/50 enough to solve the issue?

**Comment by ChangePlaces** [comment]
I think not being able to modify the output templates, with the justification "oh, if you're happy with the existing logic, but need to only change the output, then just copy/paste our existing command, but change the template dir yourself and also copy the template dir yourself" appears to break the "no bootstrap code necessary" direction that symfony appears to be heading towards.

**Comment by ckrack** [comment]
As with the proposed `target` option to use a different place than `src/` for the generated code, I'd suggest using an `origin` option, which could be used by the makers to set/override the path for the `Resources` directory.

```bash
php bin/console make:crud Foobar --origin=src/Resources/Maker
```

Pro:
- We can stay free of dependencies like Twig or iterating over possible paths.
- It would stay in the background
- It would even allow us to have packages, that just generates skeletons for specific makers, allowing a lot of customization.

Con:
- We need to change every maker to include this.
- Templates can not have an interface and an update could break skeletons

The last con would probably require us to define which variables are available inside the templates.
Skeleton-Packages would then dependend on a specific version of the maker-bundle.

**Comment by MUbedaSJ** [comment]
Hello,
I propose an auto-detection owerwriting CRUD "skeleton" templates, with only  3 lines :
Into "MakeCrup.php" file, you can add this line (at ~134), for detecting if custom skeleton files are defined on project...:
<pre><code class='php'>
 $customSkeletonDir=(file_exists(getcwd()."/templates/bundles/MakerBundle/skeleton/")?getcwd()."/templates/bundles/MakerBundle/skeleton/":"");
</code></pre>
       
Then use this variable '$customSkeletonDir' when calling templates:
at line ~137:
<pre>
 $generator->generateController(
            $controllerClassDetails->getFullName(),
            $customSkeletonDir.'crud/controller/Controller.tpl.php',
            ...
</pre>
and lines ~199:
<pre>
foreach ($templates as $template => $variables) {
            $generator->generateTemplate(
                $templatesPath.'/'.$template.'.html.twig',
                $customSkeletonDir.'crud/templates/'.$template.'.tpl.php',
                $variables
            );
        }
</pre>

I've tested, and it work like a charm !

**Comment by WilcoBrandSync** [comment]
Perfect! 

Two small changes:

> Hello,
> I propose an auto-detection owerwriting CRUD "skeleton" templates, with only 3 lines :
> Into "**MakeCrup.php**" file, you can add this line (at ~134), for detecting if custom skeleton files are defined on project...:

- It's the  "MakeCrud.php" file and not the  "MakeCrup.php" file;

> and lines ~199:
> 
> foreach ($templates as $template => $variables) {
>             $generator->generateTemplate(
>                 **customSkeletonDir**.$templatesPath.'/'.$template.'.html.twig',
>                 $customSkeletonDir.'crud/templates/'.$template.'.tpl.php',
>                 $variables
>             );
>         }

- Remove the 'customSkeletonDir.', otherwise it will generate a complete folder structure from root to the generated templates;

This is really a handy solution! Thank you for this.

**Comment by johnpancoast** [comment]
I'm a bit late, but I think this was a _perfect_ use case for Twig. I think that https://github.com/symfony/maker-bundle/pull/520/files should be held off.

No offense meant @weaverryan, we just disagree, but I don't see how having a `templates` directory in an API-only project matters. What if I have an API application that is also heavy on emails or Console commands (or anything else) and I find that Twig is useful for those cases? Then my API app might have a `templates` directory which is fine if there are Twig templates, regardless of their use case. The beauty of Symfony is in its independent libraries and how they can either coalesce into a framework or how they can be used independently for any case that a developer finds useful.

Twig is a templating language, nothing more, and code to be generated is, or could be templates.

Going further, the maker bundle is for generating code in _my_ application. I don't see why overriding templates or generation code should be made difficult for the developer. Sure, I can make my own makers/generators, but why force that on me if overriding templates can be made easier?

For an example, my current case is that I want to do remove the commented out portions in generated Repositories like the one below. Even if it's easy to create my own command, I don't think I should be forced to create a whole new command simply to change this. Not only that, but if I _did_ make my own command just to change template output, I'd likely want to override some existing logic to save me some time, but in this case, I cannot override `Symfony\Bundle\MakerBundle\Doctrine\EntityRegenerator::generateRepository()` because it's private, so I'd have to override the much larger method `Symfony\Bundle\MakerBundle\Doctrine\EntityRegenerator::regenerateEntities()` just to remove comments from generated repositories.

```
<?php

namespace App\Repository;

use App\Entity\Foo;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * @method Foo|null find($id, $lockMode = null, $lockVersion = null)
 * @method Foo|null findOneBy(array $criteria, array $orderBy = null)
 * @method Foo[]    findAll()
 * @method Foo[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class FooRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Foo::class);
    }

    // /**
    //  * @return Foo[] Returns an array of Foo objects
    //  */
    /*
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('f')
            ->andWhere('f.exampleField = :val')
            ->setParameter('val', $value)
            ->orderBy('f.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */

    /*
    public function findOneBySomeField($value): ?Foo
    {
        return $this->createQueryBuilder('f')
            ->andWhere('f.exampleField = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
    */
}

```

**Comment by MrYamous** [comment]
What would be the benefits of using Twig as a dependency? 
Currently "skeleton files can't have complex logic" as javiereguiluz said, but I'm not sure that's a problem. I mean this bundle has been made to be very extensible, considering that I think that the default generated code should remain simple but give developers the possibility to adapt it to their needs. 

MUbedaSJ's proposal seems to me to be a good compromise, which gives everyone the possibility to override default templates, without having to create a new command, and also allows to use, or not, Twig in the custom templates.

**Comment by MagnusDot** [comment]
> What would be the benefits of using Twig as a dependency?
> Currently "skeleton files can't have complex logic" as javiereguiluz said, but I'm not sure that's a problem. I mean this bundle has been made to be very extensible, considering that I think that the default generated code should remain simple but give developers the possibility to adapt it to their needs.
> 
> MUbedaSJ's proposal seems to me to be a good compromise, which gives everyone the possibility to override default templates, without having to create a new command, and also allows to use, or not, Twig in the custom templates.


that's exactly what i did in my PR

**Comment by spamRoast** [comment]
@MrYamous, @MagnusDot. remember that I'm late to this RFC and to this bundle, but it was still open so I felt like adding my thoughts. I haven't reviewed all of the maker code yet, but I'll throw in my thoughts.

> that's exactly what i did in my PR

So far, it looks like your [PR](https://github.com/symfony/maker-bundle/pull/520/files) is changing the crud maker to allow it to read from a directory relative to your current working directory. I don't know if that's the right approach. My CWD is not always relative to the project, meaning I have to cd into a certain directory for that command to load a template from a certain directory, and it's only for the crud maker at the moment.

> Currently "skeleton files can't have complex logic" as javiereguiluz said, but I'm not sure that's a problem. I mean this bundle has been made to be very extensible, considering that I think that the default generated code should remain simple but give developers the possibility to adapt it to their needs.

The bundle doesn't seem extensible in the way I need. How would I change the template for the repository that's created from the `make:entity` command, for example? The `make:entity` command [calls the EntityClassGenerator](https://github.com/symfony/maker-bundle/blob/master/src/Maker/MakeEntity.php#L140) which is a [final class](https://github.com/symfony/maker-bundle/blob/master/src/Doctrine/EntityClassGenerator.php#L20) (cannot be extended). That class [says where the template is](https://github.com/symfony/maker-bundle/blob/master/src/Doctrine/EntityClassGenerator.php#L47) but I cannot change that, at least not in a way that I can immediately see.

_Perhaps_ I can override the generator services themselves but that seems like overkill when all I want to do is change a template in a very minor way, just as writing my own command just to change the template a little seems like overkill.

> What would be the benefits of using Twig as a dependency?
The code is generated from templates that already have conditions, there are use cases for inheritance of these templates when people just want to override a small part of a template, and twig is a templating language built for things like that. Twig's inheritance allows a simple way to override a template and change a minor part, or override the whole thing, both of which seem like behavior that this bundle should allow. I don't see the harm in adding dependencies that are used for their intended purpose.

**Comment by johnpancoast** [comment]
@MrYamous, @MagnusDot. Oops, responded with another account. Responding with correct one. Remember that I'm late to this RFC and to this bundle, but it was still open so I felt like adding my thoughts. I haven't reviewed all of the maker code yet, but I'll expand on my thoughts.

> that's exactly what i did in my PR

So far, it looks like your [PR](https://github.com/symfony/maker-bundle/pull/520/files) is changing the crud maker to allow it to read from a directory relative to your current working directory. I don't know if that's the right approach. My CWD is not always relative to the project, meaning I have to cd into a certain directory for that command to load a template from a certain directory, and it's only for the crud maker at the moment.

> Currently "skeleton files can't have complex logic" as javiereguiluz said, but I'm not sure that's a problem. I mean this bundle has been made to be very extensible, considering that I think that the default generated code should remain simple but give developers the possibility to adapt it to their needs.

The bundle doesn't seem extensible in the way I need. How would I change the template for the repository that's created from the `make:entity` command, for example? The `make:entity` command [calls the EntityClassGenerator](https://github.com/symfony/maker-bundle/blob/master/src/Maker/MakeEntity.php#L140) which is a [final class](https://github.com/symfony/maker-bundle/blob/master/src/Doctrine/EntityClassGenerator.php#L20) (cannot be extended). That class [says where the template is](https://github.com/symfony/maker-bundle/blob/master/src/Doctrine/EntityClassGenerator.php#L47) but I cannot change that, at least not in a way that I can immediately see.

_Perhaps_ I can override the generator services themselves but that seems like overkill when all I want to do is change a template in a very minor way, just as writing my own command simple to change the template a little bit seems like overkill.

> What would be the benefits of using Twig as a dependency?

The code is generated from templates that already have conditions, there are use cases for inheritance of these templates when people just want to override parts, and twig is a templating language built for things like that. Twig's inheritance allows a simple way to override a template and change a minor part, or override the whole thing, both of which seem like behavior that this bundle should allow. I don't see the harm in adding dependencies that are used for their intended purpose.

**Comment by javiereguiluz** [comment]
We didn't agree on this ... so let's close as "won't fix" ... and for those needing it, they can use the "hack" shown in the previous comment. Thanks.
