### ISSUE TITLE
phpunit should be upgraded

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/maker-bundle#330]
I noticed a deprecation in the travis output:
>   1x: The "PHPUnit_Framework_MockObject_Matcher_Parameters::verify()" method will require a new "PHPUnit_Framework_MockObject_Invocation $invocation" argument in the next major version of its parent class "PHPUnit_Framework_MockObject_Matcher_StatelessInvocation", not defining it is deprecated.

This is fixed in more recent phpunit versions - the .travis.yml should bump it.

**Comment by jrushlow** [comment]
This has been addressed. Thanks @nicolas-grekas
