### ISSUE TITLE
MakeEntity throws ".../src/Entity/" directory does not exist

### ISSUE THREAD

**Issue by dtfafard** [symfony/maker-bundle#336]
When using a different file structure than App/... and setting "root_namespace" to use my new file structure. It works for creating standard entities, but when adding ManyToOne & complex Doctrine Entity Relations, it breaks and throws said error : ".../src/Entity/" directory does not exist

https://github.com/symfony/maker-bundle/blob/aa37ea1323ac888913bdd3e5f83d846798729449/src/Maker/MakeEntity.php#L102

https://github.com/symfony/maker-bundle/blob/aa37ea1323ac888913bdd3e5f83d846798729449/src/Maker/MakeEntity.php#L469

I managed to make the code work by removing "Entity" from the "src/Entity" string, but I would rather suggest to use the "root_namespace" or to add a new parameter in the maker.yaml file to handle this situation.

**Comment by weaverryan** [comment]
Hmm, no - I think we need to merge your PR and then see if there are any side effects. I hate having to do such a "weird" thing, but I thnk it's necessary :).

**Comment by weaverryan** [comment]
I'm tagging a release right now - it should fix things

**Comment by yceruto** [comment]
Thank you @weaverryan :tada:
