### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").

### ISSUE THREAD

**Issue by christiankasse** [symfony/maker-bundle#356]
`An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").`

When i try to generate a crud for my entity, this error appear when i want to create a new thing or edit using a method who are generating by this comand `php bin/console make:crud`

Please Help

**Comment by christiankasse** [comment]
I forgot some thing,

I just solve it

**Comment by robitwtms** [comment]
what did you forget? I'm having this issue right now.
