### ISSUE TITLE
Show only available command

### ISSUE THREAD

**Issue by ismail1432** [symfony/maker-bundle#357]
![image](https://user-images.githubusercontent.com/13260307/51891992-ee398f80-23a0-11e9-9b33-803ed044290d.png)

Running `php bin/console make` show a list of available make command but this one `make:migration` is not available, see picture.

IMO we should only show **available** command

**Comment by nicolas-grekas** [comment]
Hiding the command would remove any opportunity to discover it and read the message that suggests the missing package, isn't it?

**Comment by ismail1432** [comment]
>Hiding the command would remove any opportunity to discover it

True ! Maybe it's useless but what about the fact to separate available command and commands that need package.

```
Did you mean one of these?      
      make:auth                   
      make:command                
      make:controller             
      ...
-----------
Other command that need packages
    make:migration
```
Of course we should compare the difficulty to develop and benefits :smile:
