### ISSUE TITLE
Argument 1 passed to Symfony\Bundle\MakerBundle\Generator::createClassNameDetails() must be of the type string, null given

### ISSUE THREAD

**Issue by balvirsingh** [symfony/maker-bundle#358]
I am using symfony 4.2
symfony/maker-bundle - v1.11.3

When I run the command:-

`php bin/console make:entity`

It gives an error:-
019-01-31T12:47:57+00:00 [error] Error thrown while running command "make:entity". Message: "Argument 1 passed to Symfony\Bundle\MakerBundle\Generator::createClassNameDetails() must be of the type string, null given, called in /var/www/html/vendor/symfony/maker-bundle/src/Maker/MakeEntity.php on line 135"
2019-01-31T12:47:57+00:00 [critical] Argument 1 passed to Symfony\Bundle\MakerBundle\Generator::createClassNameDetails() must be of the type string, null given, called in /var/www/html/vendor/symfony/maker-bundle/src/Maker/MakeEntity.php on line 135

In Generator.php line 134:
                                                                               
  Argument 1 passed to Symfony\Bundle\MakerBundle\Generator::createClassNameD  
  etails() must be of the type string, null given, called in /var/www/html/ve  
  ndor/symfony/maker-bundle/src/Maker/MakeEntity.php on line 135

-------------------------------------------------------------------------------------------------------------------
Further when I run the command:-
`php  bin/console make:entity User`

It creates an entity file with single field "id" only. 

I need to add multiple fields through command, Please help me.

**Comment by mariemhammami** [comment]
hello I had the same mistake is what you find the right solution
