### ISSUE TITLE
After the entity is regenerated, tabs are added to existing methods.

### ISSUE THREAD

**Issue by byhaskell** [symfony/maker-bundle#361]
Hello, thanks for the maker bundle, great bundle!

After executing the "php bin / console make: entity --regenerate App" command on symfony 4.2.3, the generation is successful, but if in essence there are already methods (for example for Trait which does not automatically pick up for generation), then such methods are added a lot of tabs, which is why you always need to correct the structure of the class. (http://prntscr.com/mh9w5b)

```
public function getActive(): ?int
                                       	{
                                       		return $this->active;
                                       	}

	public function setActive(int $active): self
                                       	{
                                       		$this->active = $active;
                                       
                                       		return $this;
                                       	}
```
Can we expect a fix?

**Comment by byhaskell** [comment]
We should expect the correction?

**Comment by weaverryan** [comment]
Hi there!

Sorry for the late reply! We use https://github.com/nikic/php-parser to help generate code. This library itself detects if tabs or spaces are used inside the code, and generates new code using those. My guess is that you have tabs somewhere in your original source.

But, even if you do, it shouldn't "mangle" your existing code like this. If you have an example (like, the exact code - commited somewhere on GitHub) of a source file that gets "mangled" like this, we can check into it :).

Cheers!

**Comment by byhaskell** [comment]
@weaverryan There is no code here, unfortunately. The problem, as I noticed, arises when some methods are ruled by hands, after the start of regeneration — the method I have corrected shifts, and those methods that are automatically made and not changed by me remain in normal form.

**Comment by aaronfessler** [comment]
Same issue here :(

**Comment by byhaskell** [comment]
@aaronfessler I solved the issue by installing the plug in IDE. Although I hope to solve the problem, it is not always possible to install a plugin.

**Comment by netniV** [comment]
I had had the same issue just now when I converted an entity by replacing four-spaces to tab.  This was a global replace so the code should have identified that it was using purely tabs by what I've read here.  However, instead of tabs, it has inserted spaces.

```php
    /**
     * @ORM\Column(type="text")
     */
    private $Data;

	public function getId(): ?int
                        	{
                        		return $this->id;
                        	}

        public function setID(int $ID): self
                        	{
                        		$this->ID = $ID;

                        		return $this;
                        	}

    public function getName(): ?string
    {
        return $this->Name;
    }
```

To see this properly, highlight from the beginning of each row slowly going across.  There are no extra whitespaces at the function definition level, only the 1x-tab.  However, for the function itself, there are lots of indentation by space (28x-space) before the 1x-tab or 2x-tab are then present (noticeable when the mouse gets inline with the setID or getID).  The rest of the code is incorrectly formatted again with 4x-space indentation. Example of this is randomly large whitespace is shown by the green line below:

![image](https://user-images.githubusercontent.com/9052188/89729820-18a5e780-da31-11ea-8354-91f65540787d.png)

**Comment by netniV** [comment]
I thought it might be worth seeing this with whitespace turned on too:

![image](https://user-images.githubusercontent.com/9052188/89729912-f9f42080-da31-11ea-99ed-ac32620db9d7.png)

Interestingly enough, when I did a global replace for 4x-space to 1x-tab which resulted in the following:

![image](https://user-images.githubusercontent.com/9052188/89729953-34f65400-da32-11ea-8827-f029dd351a32.png)

This highlights that the number of spaces isn't actually completely 4x aligned.

**Comment by byhaskell** [comment]
No longer relevant, apparently corrected. Thank you, I close.

**Comment by netniV** [comment]
Can you confirm where this was corrected?

**Comment by byhaskell** [comment]
@netniV , Unfortunately no, I now use 4 and 5 symfony and nowhere else do I encounter this problem.

**Comment by netniV** [comment]
I was using symfony 5 when I encountered it.
