### ISSUE TITLE
[Symfony3.4] php version error in composer.json

### ISSUE THREAD

**Issue by zacharyzh** [symfony/maker-bundle#362]
I got the following code when I used `make:entity` command:

    public function getUsername(): ?string
    {
        return $this->username;
    }

The nullable return type declaration require php version greater than 7.1.

**Comment by LeJeanbono** [comment]
For your security you should use atleast 7.1 : https://www.php.net/supported-versions.php

**Comment by weaverryan** [comment]
Yea, make:entity (and a few other commands) require 7.1 - we throw an error if you try it in 7.0. We did that just to be pragmatic - those commands are already so complex, trying to leave off the billable types conditionally to support 7.0 wasn’t worth it :).

Cheers!

**Comment by zacharyzh** [comment]
@LeJeanbono Thanks for reminding me.

@weaverryan I understand now. I used to think this is a bug.
