### ISSUE TITLE
Custom namespace by makers

### ISSUE THREAD

**Issue by JodyLognoul** [symfony/maker-bundle#368]
I was looking for a way to change the _destination_ namespace for some makers.

I came up with this idea:

```yaml
# config/packages/dev/maker.yaml
maker:
  root_namespace: '%env(resolve:MAKER_NAMESPACE)%'
```
Then in the command line:

```bash
$ MAKER_NAMESPACE=App\UI\Web php bin/console make:controller
$ MAKER_NAMESPACE=App\UI\Cli php bin/console make:command
$ MAKER_NAMESPACE=App\Domain php bin/console make:entity
```

WDYT? Is there an other/better solution to achieve this?

Thanks

**Comment by kermitsxb** [comment]
Any update on this issue ?

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!

**Comment by c33s** [comment]
@jrushlow there is a PR for this feature. i would vote for reopening this ticket. it is too important for developing DDD applications.
https://github.com/symfony/maker-bundle/pull/378
