### ISSUE TITLE
How to generate doctrine entity without Symfony ?

### ISSUE THREAD

**Issue by arcaweb** [symfony/maker-bundle#372]
Hi,

In official doc we can read : 
`This bundle assumes you're using a standard Symfony 4 directory structure, but many commands can generate code into any application.`

I have created an empty app, installing symfony console, maker bundle and doctrine orm. But I do not have any make commands in console (I think because I have nothing to load bundles, no kernel).

How can I use is simply ?

Thanks :)

**Comment by weaverryan** [comment]
Hi @arcaweb!

This bundle only works for a Symfony application. If you're building an application from scratch using the Symfony components only, then the bundle won't work and you'll need to build your entities by hand.

Cheers!

**Comment by arcaweb** [comment]
Thanks @weaverryan, so what official doc says is wrong :/
