### ISSUE TITLE
Add option to turn off auto converting when making controller

### ISSUE THREAD

**Issue by yarcowang** [symfony/maker-bundle#388]
I'm doing APIs, and my controller located at:
`src/Controller/Api_v1/`
which as you can see there's the namespace `Api_v1`, and when I try to generate:
```
make:controller "Api_v1\\FileUploadController" --no-template

 created: src/Controller/ApiV1/FileUploadController.php

           
  Success! 
```
It makes me a different namespace. `ApiV1`. Yes, the converting sometimes might help. But sometimes, I just need the raw one. So, it would be better to have an option to turn off this...
 (And of course, do it by hand is another point of view...)

**Comment by przemyslaw-bogusz** [comment]
If I'm not mistaken, it's one of the Symfony coding standards to use `UpperCamelCase` for class names and namespaces. The MakerBundle follows these standards, which means implementing an option to break them, would not be a good solution.

**Comment by yarcowang** [comment]
@przemyslaw-bogusz Get it... But, there can be always exceptions, something like in this case. Maybe the standard should also add `_v...` (version suffix / or any other common used suffix) and without changing them~ (And obviously as you can see in this case `Api_v1` is more clear than `ApiV1` -- at least in my mind...) 😄
