### ISSUE TITLE
[Tests] add CI to the repository

### ISSUE THREAD

**Issue by Simperfit** [symfony/maker-bundle#39]
At the time of speaking there are no CI running the tests for the repository. Do we keep using travis ou do we add something like CircleCI ?

**Comment by javiereguiluz** [comment]
Yes! We should use Travis (and AppVeyor?) to align with the practices of the rest of the Symfony projects.

**Comment by Simperfit** [comment]
Can someone enable it ? I can do the configuration ;)

**Comment by fabpot** [comment]
I've just enabled Travis.
