### ISSUE TITLE
discussion about Override maker parts

### ISSUE THREAD

**Issue by rudak** [symfony/maker-bundle#390]
While reading the doc, I understood that making your own maker was childishly simple. But in fact this is far from being the case, all the classes are linked together and to override here or there, it takes a lot of work. 
The structure is really locked from everywhere, what a ordeal to override a ```GeneratorTwigHelper``` for example.
Isn't it possible to decouple all this a little bit ?

**Comment by pilOum** [comment]
Hi,
I have the same issue to override "Exception" part to translate every reason with a key and not directly the reason itself.
Thx :)

**Comment by weaverryan** [comment]
Sorry for never replying. It is true that the bundle is made with a “lock down first, open up as use-cases are presented” mentality. I did that so we could move quickly if needed to add or change makers without being over-burdened with protecting backwards compatibility.

If there is some specific hook or override point that would be useful, let me know! A real-life use-case would help, a pull request would be even better ;).

Cheers!
