### ISSUE TITLE
make:user then migration causes syntax error with MariaDB

### ISSUE THREAD

**Issue by juandevteloro** [symfony/maker-bundle#392]
Symfony version 4.2.8
**Description**  
I am using mariaDB as a database,when i use php bin/console make:user it creates the user entity and the repository , then i create the migration, but when i run
`php bin/console doctrine:migrations:migrate` 
i get
```
  An exception occurred while executing 'CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, compa
  ny_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(180) NOT NULL, last_nam
  e VARCHAR(180) NOT NULL, age INT NOT NULL, gender VARCHAR(8) NOT NULL, phone VARCHAR(10) NOT NU
  LL, provider VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, title VARCHAR(32) DEFAULT NULL,
   assigned_to VARCHAR(180) DEFAULT NULL, created_by VARCHAR(180) DEFAULT NULL, date_created DATE
  TIME DEFAULT NULL, modified_by VARCHAR(180) DEFAULT NULL, date_modified DATETIME DEFAULT NULL,
  roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email)
  , INDEX IDX_8D93D649979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLA
  TE utf8mb4_unicode_ci ENGINE = InnoDB':

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; c
  heck the manual that corresponds to your MariaDB server version for the right syntax to use nea
  r 'JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C7' at line 1
```

**How to reproduce**  
I have already added:
`server-version: 'mariadb-10.0.38' `

**Possible Cause**  
I think the issue is that mariadb 10.0.38 does not allow for JSON-type fields, i am not sure what the proper type of the field should be in this case but this should be the ORM annotation added  for the `$roles` attribute

**Comment by LeJeanbono** [comment]
Hi,
JSON Type in MariaDB is up since 10.2, upgrade and you will be fine ;)
see https://mariadb.com/resources/blog/json-with-mariadb-10-2/

**Comment by jramirezpr** [comment]
@LeJeanbono I don't have control over the db version to be used in production.

**Comment by LeJeanbono** [comment]
So don't save `roles` as `JSON` !

**Comment by juandevteloro** [comment]
Right, that is what i am currently trying as a workaround. But i think
either make:user should take into account tne server_version in order to
make the entity, or make:migration should take this into account.

**Comment by pluseg** [comment]
@juandevteloro As I see, Doctrine officially supports only MariaDB v10.2+. And it starts with DBAL v2.9+. See https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/platforms.html#mariadb
So, there is nothing to fix.
