### ISSUE TITLE
"BlogPost" hardcoded in templates for Normalizer and Voter

### ISSUE THREAD

**Issue by stefan2** [symfony/maker-bundle#395]
Shouldn't "BlogPost" be replaced by an entity name?

**Normalizer**

https://github.com/symfony/maker-bundle/blob/master/src/Resources/skeleton/serializer/Normalizer.tpl.php#L28
```php
public function supportsNormalization($data, $format = null): bool 
{
    return $data instanceof \App\Entity\BlogPost;
}
```
**Voter** 

https://github.com/symfony/maker-bundle/blob/master/src/Resources/skeleton/security/Voter.tpl.php#L16
```php
protected function supports($attribute, $subject)
{
    // replace with your own logic
    // https://symfony.com/doc/current/security/voters.html
    return in_array($attribute, ['POST_EDIT', 'POST_VIEW'])
        && $subject instanceof \App\Entity\BlogPost;
}
```

**Comment by pluseg** [comment]
@stefan2 @nicolas-grekas I propose adding more comments and turning off generated Normalizer/Voter by default. Please approve and I will create a PR.
```php
public function supportsNormalization($data, $format = null): bool 
{
    // Replace with your own logic
    // See https://symfony.com/doc/current/serializer/custom_normalizer.html
    // return $data instanceof \App\Entity\SomeEntity;
    return false; 
}
```

```php
protected function supports($attribute, $subject)
{
    // Replace with your own logic
    // See https://symfony.com/doc/current/security/voters.html
    // return in_array($attribute, ['POST_EDIT', 'POST_VIEW'])
    //    && $subject instanceof \App\Entity\BlogPost;
    return false;
}
```

**Comment by weaverryan** [comment]
That sounds sensible to me 👍

**Comment by stefan2** [comment]
I am new in this topic and created a normalizer for an entity. In this case the sample code was absolutely conclusive (except the name of the entity). I didn't realize (means didn't read the docs), that "$data" isn't necessarily an (my) entity. Now i know.

So this is fine for me too, thanks for the lesson :-)
