### ISSUE TITLE
make:auth login form: add logout support and help for logged in user

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#397]
After talking with @nicolas-grekas, we're proposing three changes to `make:auth` for the login form:

1) Add a question: "Do you want to generate a /logout URL?" and add the needed security.yaml and route/controller code for this if yes

2) On the login form, if the user is already logged in, display a message (in addition to the login form) like:

> you're logged in as XXX [Logout Liink]

3) In the controller, add commented-out code that the user could uncomment to redirect to the "target path" if the user is already logged in.

**Comment by maxhelias** [comment]
This feature is now present. The issue can be closed or there are still things to do?
