### ISSUE TITLE
Update MakeSubscriber for 4.3 event name changes

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#400]
In Symfony 4.3, many of the event names changes to be class names. The EventRegistry class - https://github.com/symfony/maker-bundle/blob/master/src/EventRegistry.php - as a short list of the most common events in Symfony. We should update these to use the latest event names, IF those new event classes are available (i.e. use the new event names if they are available in the user's app, otherwise use the old event names): https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#updated-httpkernel-event-classes

**Comment by javiereguiluz** [comment]
Closing and fixed by #403.
