### ISSUE TITLE
Registration form and validation

### ISSUE THREAD

**Issue by Soonz** [symfony/maker-bundle#412]
When using this command : php bin/console make:registration-form

It should be mentionned ( or done automatically ) that you must set the User "password" variable to "nullable=true" else you face a validation issue like so : 

![sfsdfsdfsdfsdfsdfsdfsdfsdfsdfsd](https://user-images.githubusercontent.com/3778544/58767139-934eb980-8587-11e9-98a9-9d03cc7d2ea4.png)

**Comment by weaverryan** [comment]
this is caused by auto-validation in Symfony 4.3 and the `symfony/property-info` being installed. I don't like making it nullable=true, as it's really not nullable. I need to check into this a bit more...

**Comment by Pierstoval** [comment]
It's a registration form, why would the password have to be `null`? I think this is totally legit, especially considering how auto-mapping was made in the first place.

**Comment by weaverryan** [comment]
This should be "fixed" now, in a sense. We've disabled (via the recipe) the auto-mapping feature by default in Symfony 4.3: https://github.com/symfony/recipes/pull/612/files - the auto mapping was causing this problem, and it needs a bit more work so we can work around situations like this.
