### ISSUE TITLE
[RFC] Add a make:user command.

### ISSUE THREAD

**Issue by Simperfit** [symfony/maker-bundle#42]
In order to be able to implement the security part of symfony, in my opinion it can help people to have the whole user stack generated

Since the only thing they will to do is to configure guard for this.

WDYT ?

see #41 for an implementation and testing if you want this in the Maker Bundle.

**Comment by kunicmarko20** [comment]
This is a nice thing to have, if it goes in this direction and this gets added, maybe there could also be a command that would generate a [traditional login form](https://symfony.com/doc/current/security/form_login_setup.html), where we could get Guard, Controller, Form Type and a template.

**Comment by weaverryan** [comment]
Yes, I want the `make:user` maker, and also a `make:auth:login` maker :).

**Comment by ro0NL** [comment]
@Simperfit im kinda into this :P https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9

**Comment by wouterj** [comment]
I'm closing this issue as I believe this has been implemented about 2 years ago in https://github.com/symfony/maker-bundle/pull/250 . Let me know if I'm missing something :)
