### ISSUE TITLE
Error when deleting entity

### ISSUE THREAD

**Issue by Zipounet** [symfony/maker-bundle#427]
hi,
Steps to reproduce:
- Create an entity with make:entity
- Run make:crud for the entity.
- Create new entity /<entity>/new
- Delete this entity using the delete button.

![image](https://user-images.githubusercontent.com/24437290/60020894-324f6880-9691-11e9-94cb-a942d40beeff.png)

By default, the form send a POST request instead a DELETE method. A hidden field "_method" exists on the form but not overide the form method.

The solution would be, to allow to override method parameter on the index.php like this 
Request::enableHttpMethodParameterOverride();

**Comment by LeJeanbono** [comment]
Are you using a HttpCache Reverse Proxy ?
https://symfony.com/doc/current/http_cache.html#symfony2-reverse-proxy

**Comment by jrushlow** [comment]
If this is still an issue, please let us know and we can re-open it. Thanks!
