### ISSUE TITLE
Doctrine DBAL

### ISSUE THREAD

**Issue by nasrithamer** [symfony/maker-bundle#428]
Hello,
when making **php bin/console make:entity** i have this error 
  ```
 Attempted to load class "MySQL57Platform" from namespace "Doctrine\DBAL\Platforms".  
   Did you forget a "use" statement for another namespace?
```

and here also  **php bin/console make:migration**

```
  Attempted to load class "MySqlSchemaManager" from namespace "Doctrine\DBAL\Schema".  
  Did you forget a "use" statement for another namespace? 
```

Any help plz ?

**Comment by LeJeanbono** [comment]
What is your doctrine configuration?

**Comment by weaverryan** [comment]
And maybe also what does “composer show doctrine/dbal” displays - specifically what version is installed.

**Comment by nasrithamer** [comment]
i reinstalled doctrine and it works good thank you
