### ISSUE TITLE
make:registration-form validator error on password

### ISSUE THREAD

**Issue by Claicon** [symfony/maker-bundle#432]
Hello,

so I followed the [How to Implement a Registration Form](https://symfony.com/doc/current/doctrine/registration_form.html) tutorial and everything worked fine except the error `data.password - This value should not be null.` (toolbar) occured in my validator when submitting the form. It seems like there's a problem with auto_mapping when using `plainPassword` element as a form element and the password is set after `if ($form->isSubmitted() && $form->isValid()) {`. This condition is not triggering because the error above and the plainPassword is actually set like described when the condition is true.

Symfony version: `4.3.2`

Thanks for reviewing!

**Comment by weaverryan** [comment]
For now, you’ll need to disable the validation auto mapping feature in validator.yaml that’s new in Symfony 4.3. In fact, we have currently disabled that config on new projects (starting about a week ago) as the feature needs a few extra options to make it not a pain in situations like this.

Cheers!
