### ISSUE TITLE
doctrine/annotations dependency tells to require sensio/framework-extra-bundle

### ISSUE THREAD

**Issue by MatTheCat** [symfony/maker-bundle#442]
When I tried to use `make:controller` I got

> [ERROR] Missing package: to use the make:controller command, run:              
>                                                                                
>         composer require annotations 

which I ran, before realizing it was installing sensio/framework-extra-bundle.

That surprised me because you're no longer supposed to require this bundle to annotate routes. Then I saw

> we only need doctrine/annotations

in https://github.com/symfony/maker-bundle/blob/master/src/Maker/MakeController.php#L89

So why does it ask to install sensio/framework-extra-bundle?

This also concerns `MakeRegistrationForm`.

**Comment by MatTheCat** [comment]
I just found https://github.com/symfony/symfony-docs/issues/10426

So basically we want the user to install the whole framework-extra-bundle because they **may** need it??

**Comment by weaverryan** [comment]
I’d be ok with changing to doctrine-annotations. Though, that change can only be made for makers that don’t rely on the param converter from FwExtraBundle.

**Comment by MatTheCat** [comment]
These are `MakeRegistrationForm` and `MakeController`. I could submit a PR tomorrow.
