### ISSUE TITLE
Unreadable console output

### ISSUE THREAD

**Issue by briavers** [symfony/maker-bundle#451]
When using the maker bundle to edit an entity or create one the output is unreadable it also occurs on other occasions when using the maker bundle

![2019-08-02 12_10_18-Window](https://user-images.githubusercontent.com/26483622/62363075-b281ad00-b51e-11e9-9a23-acc0506fe543.png)

I've tried with different fonts and different terminals (powershell, hyper, and the PHPstorm native one)

**Comment by LeJeanbono** [comment]
I suppose that you are on Windows.
You have to enable ANSI in terminal, follow this : [https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes](url)

**Comment by briavers** [comment]
This indeed seems to be the issue but it doesn't get solved by following the tutorials. i'll llok further into it.
