### ISSUE TITLE
[RFC] Add make:repository command

### ISSUE THREAD

**Issue by TheGarious** [symfony/maker-bundle#457]
Before create a PR for this, i see many demand of creating a repository with existing entities. 

I think add this command is important for developer not using make:entity command for their entity.

**Comment by romaricdrigon** [comment]
Hello,

I agree, it makes a lot of sense. Especially now that making repository is a little bit tricker (ie, you should extend `ServiceEntityRepository`, which is Symfony specific, etc.).
So what about a `make:repository` command, to which you pass entity name?
Do you see any other relevant options?

**Comment by TheGarious** [comment]
Yes for add entity name into command. 

Maybe an option to add many function into repository or added clean class.

**Comment by romaricdrigon** [comment]
I think we have only to generate a skeleton ; adding functions can be done later, by the user.
So updating the entity + generating an empty Repository, but with the same PhpDoc than through `make:user` and correct extension, would be a solid start.

**Comment by TheGarious** [comment]
Ok, i create this command this week-end :D
