### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by gregdeluxee** [symfony/maker-bundle#475]
Hello,

Autocomplete does not work when using make:entity.
From the example below, if I start typing "Sam" for the class name, I have nothing that appears in my terminal. (Just a sample gif I get from another issue to show what I mean.)

![](https://user-images.githubusercontent.com/73419/38252723-33ef5d86-3755-11e8-911b-a6b9c6aa5c63.gif)

Currently on Windows 10 pro, using php 7.3, v1.13.0 of maker-bundle and Symfony 4.3
I use the default namespace for my entities (App).

Any idea why it does not work anymore ?
Unfortunately, I couldn't tell when it started to not working for me.

**Comment by jrushlow** [comment]
@gregdeluxee is this still an issue for you? If so, please feel free to reopen this issue.. Thanks!
