### ISSUE TITLE
make:form only allows for entities to be bound

### ISSUE THREAD

**Issue by abenettt** [symfony/maker-bundle#477]
When trying to create a new form via `bin/console make:form` whilst supplying the bound class one can not specify a class which is not inside the `App\Entity` namespace even when one specifying the fully qualified class name. 

Entering:
```bash
bin/console make:form RegisterType App\Mode\Form\Register
```
Results in the following response
```
In ClassDetails.php line 45:

  Class App\Entity\AppModeFormRegister does not exist


make:form [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name> [<bound-class>]]
```

I would expect to be able to bind any class to the form and not being bound to a specific namespace.

**Comment by TheGarious** [comment]
Hello, i look this today 👍

**Comment by GaryPEGEOT** [comment]
@abenettt It might not be super intuitive, but you have to prefix the FQCN with a "\" for this to work, in your case:
`bin/console make:form RegisterType \App\Mode\Form\Register`

**Comment by jordisala1991** [comment]
I had to do it like this in my case: `console make:form ContactFormType \\App\\Model\\Lead`

**Comment by ckrack** [comment]
When specifying the `bound-class` as an argument, you need to escape the slashes.

```bash
bin/console make:form RegisterType \\App\\Mode\\Form\\Register
```

When using the interactive mode, the input must not be escaped:

```bash
$ bin/console make:form

 The name of the form class (e.g. AgreeablePuppyType):
 > RegisterType

 The name of Entity or fully qualified model class name that the new form will be bound to (empty for none):
 > \App\Mode\Form\Register
```

This was added in #301, which also includes a test.
There is not really any documentation for the individual makers in the Symfony docs, only a single page for the [Maker bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html).
I could add a hint for this in the `--help` of the command.

@weaverryan Do you think we should set up some more documentation for the individual makers within the Symfony docs?
