### ISSUE TITLE
Confusion about optional dependencies

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/maker-bundle#483]
In a new Symfony project, install Maker and run this:

```bash
$ php bin/console make:functional-test


 [ERROR] Missing packages: to use the make:functional-test command, run:

         composer require browser-kit css-selector panther --dev
```

`panther` is optional, but it's displayed nevertheless to install it.

However, if I install manually both `browser-kit` and `css-selector` (but not `panther`) the error message disappear and everything works.

So, optional dependencies are indeed optional ... but it's confusing to add them to the command that installs things to fix problems.

**Comment by javiereguiluz** [comment]
OK, I found the "problem" in this method: https://github.com/symfony/maker-bundle/blob/31a7597a99d8315bfa8eb0bfd2247ab880cb0c1b/src/DependencyBuilder.php#L134

According to these lines, this is the expected behavior:

https://github.com/symfony/maker-bundle/blob/31a7597a99d8315bfa8eb0bfd2247ab880cb0c1b/src/DependencyBuilder.php#L148-L152

I understand that without this code, optional dependencies would never be displayed ... but it still feels strange to recommend installing the optional dependencies.

Maybe it's a problem of this specific command? Functional tests !== "E2E tests" or "browser tests". So maybe we should stop recommending Panther in this case? Thanks.

**Comment by weaverryan** [comment]
Probably not recommending it here is a good idea. Then we should add proper support for an E2E maker (or a question on this maker... however we decide is best) and *then* require panther.

**Comment by javiereguiluz** [comment]
Ryan, that makes sense to me. I've created #484 to do the first part of what you proposed. Thanks.

**Comment by fabpot** [comment]
For the record, my experience is a bit different. If I don't install Panther, I cannot use the command.

**Comment by LeJeanbono** [comment]
@dunglas started something here #227
