### ISSUE TITLE
`make:user` default table name not compatible with PostgreSQL

### ISSUE THREAD

**Issue by blowski** [symfony/maker-bundle#485]
The `make:user` command defaults to creating a user entity with the table name `user`. This is a reserved word in PostgreSQL, so out of the box, Doctrine queries don't work.

I'm using:
* Maker bundle v1.14.0
* Doctrine ORM v2.6.4
* PostgreSQL v12.0

As soon as I try something like `$userRepository->findOneByUsername()` it fails:

```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.username = ? LIMIT 1' with params ["bob"]:

SQLSTATE[42703]: Undefined column: 7 ERROR: column t0.id does not exist
LINE 1: SELECT t0.id AS id_1, t0.username AS username_2, t0.roles AS...
```

If I change the name of the table to `users` in the `User` entity, queries work fine. This seems like a confluence of bugs from different projects, but it seems to me this would be the easiest place to fix it.

Possible fixes:
* Automatically pluralise the table name
* Automatically add a prefix to the table name
* Ask for a table name in the console command, and validate that it doesn't equal `user`. I'm not sure if this affects other databases - if it's a PostgreSQL specific issue then perhaps it could selectively apply the validation rule.

**Comment by LeJeanbono** [comment]
This is a doctrine Job to do that.
Some informations here :) https://github.com/doctrine/dbal/issues/1222

**Comment by blowski** [comment]
So should the generated code include the table name annotation, with the table name escaped? The [Symfony documentation says](https://symfony.com/doc/current/doctrine.html#doctrine-adding-mapping) says:

> Be careful not to use reserved SQL keywords as your table or column names (e.g. GROUP or USER)

but then the Symfony Maker bundle is not following that advice out of the box.

**Comment by romaricdrigon** [comment]
Hello,
I agree that MakerBundle should have some "safe" defaults, we should not push developers towards some (possible) Doctrine issue.
I still like `user` as a table name, pluralizing it does not feel quite right.
Maybe we could detect `Postgresql` platform, and then [quote it](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words)?

**Comment by chalasr** [comment]
I think it would be worth allowing to define the table name for any generated entity, adding the `@ORM\Table` annotation if needed and taking care of escaping SQL reserved word.

**Comment by blowski** [comment]
@chalasr are you still looking for help on this? As I originally raised the ticket, I could contribute something?

**Comment by weaverryan** [comment]
We're working on it over on #545. I'm actually on my way to review that now!
