### ISSUE TITLE
make:entity fails to determine locate for new class despite passing full namespace

### ISSUE THREAD

**Issue by FeyDreamers** [symfony/maker-bundle#491]
I am using Symfony 3.4 and I have the src/AppBundle.

I tried to add new entity with `bin/console make:entity`, but it fails to create it.

No matter if I provide `MyClass` or `\AppBundle\Entity\MyClass` or any other strange combination (`AppBundle\Entity\MyClass`,  `App\Entity\MyClass`,  `\AppBundle\MyClass`...) for class name, it always says:

> Could not determine where to locate the new class "App\Repository\Entity\MyClassRepository", maybe try with a full namespace like "\My\Full\Namespace\MyClassRepository"

Which looks to me that it ignored the `\AppBundle\Entity` path I explicitly provided.

Also adding `maker.yaml` inside `app/config/package/dev` (as suggested in error message) has no effect on it.

**Comment by jrushlow** [comment]
If this is still a problem, please let us know and we'll reopen the issue. Thanks!
