### ISSUE TITLE
make:auth fails when login.html already exists

### ISSUE THREAD

**Issue by SevenbitsIt** [symfony/maker-bundle#494]
**Symfony version(s) affected**: 4.3.7

**Description**  
when making a new entry point with make:auth the command fails if there're already a login.html.twig

**How to reproduce**  
bin/console make:auth on second guard authenticator.

**Possible Solution**  
one should be able to choose a name for the file if already a login.html.twig exist

**Comment by javiereguiluz** [comment]
@linaori you are right. I've transferred the issue to the right repository using GitHub tools. I hope it worked as expected. Thanks!

**Comment by jrushlow** [comment]
I'm not sure if this is still relevant. However, if it is, we do not any have plans to handle this edge case at the moment. But we will gladly accept any PR's
