### ISSUE TITLE
Organizing tests in test suites

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/maker-bundle#498]
Hello,

We should split the test suite, at least in Unit + Functional.
We could go further, and split the huge `Maker/FunctionalTest` provider into smaller chunks, ideally one per Maker.

Ping @sadikoff - you were feeling like working on this one, thanks in advance, do not hesitate to ask for help!

**Comment by sadikoff** [comment]
Yeah! Thanks for this ping! I'll find some time this week to create an initial PR. So I'll keep in touch!
