### ISSUE TITLE
Discussion about Symfony 3 compatibility

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/maker-bundle#503]
Hello,

At the moment, Maker bundle supports Symfony 3.4 (LTS), Symfony 4, and newly-released Symfony 5.
Supporting 3 major versions, with some big differences, is hard. Best practices changed, libraries changed. For instance, Swiftmailer was replaced by Symfony Mailer (see #359). And all that is causing the test suite to grow exponentially.

This issue is here to discuss a few point:
 * who is using Maker bundle with Symfony 3? At that time, SensioGeneratorBundle was the default option, I'm not sure it is used by many.
 * can we drop Symfony 3 compatibility before the LTS expire? Is there any Symfony guidelines against this?
 * if we did, should we release a new major version? since it is a BC break.
 * if we don't drop Symfony 3, which architecture should be set up? I think it would make sense to have `MakeSymfony3xxx`, `MakeSymfony4xxx` etc. classes for Maker whose code is specific to a Symfony version. Small classes will be easier to understand & maintain. And we could run subsets of tests on Travis on specific Symfony versions.

**Comment by nicolas-grekas** [comment]
There is no need for a major version bump if only 3.4 is dropped.
Releasing v1.15 with ^4.4 would be fine to me.
Of course, this might require maintaining a `1.14` branch to be able to release bug fixes for 3.4.

**Comment by alcaeus** [comment]
We've dropped support for Symfony 3.4 in DoctrineBundle 2.0, which brings in Symfony 5 support. DoctrineBundle 1.12 with support for Symfony 3.4 will be supported for the remainder of 3.4's support lifecycle. While we now have to maintain two branches, this is easier than maintaining a single branch that supports three Symfony majors.

Note that the decision to tag 2.0 was not made because we're dropping Symfony 3.4 - this can be done in a minor release (and has been done as such before).

**Comment by weaverryan** [comment]
Ok, then let's prepare a new minor version (1.15) with `^4.4` support. We can create a `1.14` branch in the event we need a bug fix release for 3.4 (its bug fix support ends in Nov 2020).

This WILL simplify things quite a bit... as this will also allow us to bump the PHP version to 7.1.

**Comment by romaricdrigon** [comment]
Agreed. I'm waiting a little bit more, and then I will start working on 1.15.

Actually, I'm wondering if we should not remove Sf5 compatibility from 1.14 branch, so it becomes "legacy" branch, and re-add it in 1.15 (which we will release immediately). This way, we could make CI green on 1.14 - which is definitely better if we need to support this branch until next November.

**Comment by romaricdrigon** [comment]
Agreed. I'm waiting a little bit more, and then I will start working on 1.15.

There's only one thing which I don't like right now, is that 1.14 will stay a "half-baked" branch, with failing tests, that will be harder to maintain. Are they any ways around?
For instance, making 1.13 the legacy branch would be much better (and I believe that thanks to #499, we could even make it green). But people running `composer update` will continue to get 1.14.

(deleted & rephrased previous comment)

**Comment by stof** [comment]
> But people running `composer update` will continue to get 1.14.

that's what is ruling out this option.

**Comment by weaverryan** [comment]
I think we should get 1.14 totally stable and make that the legacy branch. I don't see any practical issues with making 1.14 the "legacy" branch. Or do you disagree Romaric?

**Comment by jrushlow** [comment]
Closing this as it is slightly dated - Symfony 3.x is no longer LTS. Thanks!
