### ISSUE TITLE
`make:migration` does not detect database changes on `make:entity` ManyToMany relation

### ISSUE THREAD

**Issue by quentint** [symfony/maker-bundle#504]
Hey all,  
I generated a `Purchase` entity and a `Game` one with `make:entity`. I then added a `games` ManyToMany relation on Purchase (also using `make:entity`).

I then ran `make:migration` but got a surprising
> [WARNING] No database changes were detected.

I tried adding a `@ORM\JoinTable` annotation on `private $games;` but the result remained the same.

Not sure what to do next, and how to generate a migration class. Anyone also experienced this?

**Comment by deivid11** [comment]
I'm having a similar problem after updating symfony to 4.3.8, have you tried removing cache?

**Comment by quentint** [comment]
I have, yes. I didn't mention it, but I'm using Symfony 5.0.

**Comment by deivid11** [comment]
@quentint It looks like this is a doctrine bug https://github.com/symfony/recipes/issues/688

**Comment by dmaicher** [comment]
Yes this is currently an issue with wrongly configured caches on DoctrineBundle. We are working on a fix.

See https://github.com/doctrine/DoctrineBundle/pull/1073

**Comment by quentint** [comment]
Oh great, thanks for letting me know!

**Comment by quentint** [comment]
I can confirm that calling `doctrine:cache:clear-metadata` before `make:migration` fixes the issue. But oddly enough, it displays that message:

> [ERROR] No cache entries were deleted.

Working anyway 👍
