### ISSUE TITLE
No changes detected when regenerating entity

### ISSUE THREAD

**Issue by deivid11** [symfony/maker-bundle#505]
After updating symfony to version 4.4 maker is not detecting changes in my entities, I have to clean cache and execute php bin/console make:entity App\\Entity\\MyEntity --regenerate. The issue is happening in a clean symfony 5 installation.
I have configured "dev" environment.

**Comment by nicolas-grekas** [comment]
Correct, see https://github.com/doctrine/DoctrineBundle/issues/1069 for similar report and https://github.com/doctrine/DoctrineBundle/pull/1073 for progress.

**Comment by deivid11** [comment]
@nicolas-grekas thanks
