### ISSUE TITLE
Support configuration file when making migrations

### ISSUE THREAD

**Issue by yifei3212** [symfony/maker-bundle#508]
The current project I'm working on has two sets of migration systems which have completely different migration files for different tables. 

The doctrine commands accept parameters, such as --em, --connection, --configuration, which makes it possible to support multiple sets of migration systems.

When using maker to make migrations, I also want to change the configurations such as 'migrations_directory' or 'migrations_namespace'. Is that possible by using the maker command?

**Comment by LeJeanbono** [comment]
Do you try with a doctrine configuration file ?
https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/configuration.html

**Comment by yifei3212** [comment]
Hi, @LeJeanbono , that's what I want to know. We are using two different doctrine configuration files for different sets of migration files. I wonder if it's possible to choose which configuration file to use when doing make:migration.

**Comment by LeJeanbono** [comment]
Ok @yifei3212, what is the doctrine command that you use actualy to switch doctrine config ?

**Comment by yifei3212** [comment]
Hi, @LeJeanbono, for example, when running the doctrine commands, I would do something like `bin/console doctrine:migrations:migrate --em=some-entity-manager --configuration=some-migrations.yml`

In some-migrations.yml, I can set migrations_namespace, migrations_directory, etc. I want to do the same when making a migration file.

**Comment by LeJeanbono** [comment]
Ok, `--configuration` is not implemented for maker.
I will make a PR this week ;)

**Comment by yifei3212** [comment]
@LeJeanbono Thank you so much!

**Comment by yifei3212** [comment]
Hi, @LeJeanbono, can I ask when could this be merged?

**Comment by LeJeanbono** [comment]
@weaverryan @romaricdrigon can we make a release ? :)
