### ISSUE TITLE
Crash in windows powerhsell

### ISSUE THREAD

**Issue by t0mspace** [symfony/maker-bundle#510]
Hello,
the symfony console crash when write for exemple :

symfony console make:entity Property:

http://tof.cx/image/qFWDlC

The issue seems become from the file QuestionHelper.php line 137 :

http://tof.cx/image/qFW3qi

Environnement: windows 10 build 19025.vb_release.191112-1414
shell: powershell and cmd (same problem),
PHP version: tested with : php 7.4 /7.3/7.2.13  (nts, 64 bit)
Symfony cli : 4.11.2

 but it works with ubuntu shell (WSL2)

Thanks for help !

**Comment by xabbuh** [comment]
That's a known issue in PHP 7.4 that needs to be fixed there.

**Comment by t0mspace** [comment]
> That's a known issue in PHP 7.4 that needs to be fixed there.

Ok but I 've the same probleme with other version of PHP too

**Comment by bbuehrle** [comment]
@weaverryan Given the windows environment and the fact that QuestionHelper would definitely be "interactive", could this be the same underlying issue as #506?

**Comment by jrushlow** [comment]
I'm going to close this issue as the links in the original description are broken. Based on @xabbuh's comment, this appeared to be a PHP issue. If you are still experiencing this problem, please feel free to reopen/create a issue with additional details. Thanks!
