### ISSUE TITLE
make:migration doesn't work properly with self referencing

### ISSUE THREAD

**Issue by xaoseric** [symfony/maker-bundle#512]
Self referencing seems to not work properly with self referencing ManyToOne entities, it doesn't add the proper sql or the `parent_id` relation, have tried it with the JoinTable annotation as well.

**Comment by LeJeanbono** [comment]
Hi !
Can you provide us your entities and the result ?
Thanks :)

**Comment by jrushlow** [comment]
Howdy @xaoseric - I'm going to close this issue for now. If you are still having problems, please feel free to reopen it and provide additional context to your situation. Thanks!
