### ISSUE TITLE
Harmless unused sprintf args in YamlSourceManipulator.php

### ISSUE THREAD

**Issue by TysonAndre** [symfony/maker-bundle#517]
https://github.com/symfony/maker-bundle/blob/56df0191a70921032554562dde0d478a15771cb9/src/Util/YamlSourceManipulator.php#L132-L136

I'd expect something like             `'Changing array type & format via updateData() (type=%s, format=%s)',` instead.

Passing too many arguments is harmless, and won't result in notices.

Detected with phan when checking for new false positives in phan (PhanPluginPrintfNoSpecifiers in PrintfCheckerPlugin)

**Comment by weaverryan** [comment]
Thanks! See #570
