### ISSUE TITLE
Generated login guard authenticator for non-doctrine user contains check, that will never pass

### ISSUE THREAD

**Issue by andrew-demb** [symfony/maker-bundle#521]
Check in authenticator will never pass, because `loadUserByUsername()` never return non-object variable.

Check in template:
https://github.com/symfony/maker-bundle/blob/09fc38cd48aa53fd1322e1f87f89fb29b37a693d/src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php#L68-L76

User provider interface:
https://github.com/symfony/symfony/blob/76c98fda989a812a5265d9d3c97f855430821e29/src/Symfony/Component/Security/Core/User/UserProviderInterface.php#L46

As alternative, we can drop this check for non-doctrine users. Or replace it with catch `UsernameNotFoundException` instead

**Comment by jrushlow** [comment]
Guard authenticators are no longer supported by maker bundle
