### ISSUE TITLE
Let's use the String component everywhere

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/maker-bundle#522]
This bundle makes lots of string manipulations. Originally we created some utils (e.g. https://github.com/symfony/maker-bundle/blob/master/src/Util/ClassNameDetails.php) and a `Str` utility class (https://github.com/symfony/maker-bundle/blob/master/src/Str.php).

The only problem for us is that `String` requires using PHP 7.2 (and this project requires *the legacy and unmaintained* PHP 7.0). Can we update the PHP requirement in the next stable version?

For more info:

* [New in Symfony 5.0: String Component](https://symfony.com/blog/new-in-symfony-5-0-string-component) blog post
* [String component docs](https://symfony.com/doc/current/components/string.html)
* [Migration to String component in Symfony Demo app](https://github.com/symfony/demo/pull/1055/files)

**Comment by stof** [comment]
ClassNameDetails will still need to exist. And the one call to `str_replace` in it won't become more readable when using the String component.

And in the `Str` util, the String component could replace the implementation of `asCamelCase` and `asSnakeCase` (well, here, the weird thing is that the main implementation is in `asTwigVariable` for the conversion to snake case, while the rule is that Twig variables are using snake-cased, not that snake-case is following the Twig rules, so we might want to swap the implementation).
Most other helpers will still be needed:

- some of there are simple aliases of the `asSnakeCase` method, but they have a domain meaning (they encode in a single place that route names are using snake case for instance). Removing them would not simplify the bundle but would duplicate the domain rule of what a route name uses.
- some of them are too specific to be moved to the String component itself (`getShortClassName` or `singularCamelCaseToPluralCamelCase` for instance)

**Comment by javiereguiluz** [comment]
You are right @stof but I just want to replace the implementation details, not the methods used in the bundle. As you said, they have "domain meaning" so we must keep them. Let's just replace all `str*` or `mb_*` calls (if possible and if it makes sense). Thanks!

**Comment by LeJeanbono** [comment]
Min version is now 7.1, I think we can begin to work on it :)

**Comment by javiereguiluz** [comment]
Closing this old issue because it's already being tackled in PRs like #1100. Thanks.
