### ISSUE TITLE
make:fixtures : Doctrine\Persistence\ObjectManager is deprecated

### ISSUE THREAD

**Issue by HanXHX** [symfony/maker-bundle#528]
Hi,

When i use the command "make:fixtures", it creates files with deprecated interfaces

See: https://github.com/symfony/maker-bundle/blob/master/src/Resources/skeleton/doctrine/Fixtures.tpl.php#L6

"Doctrine\Common\Persistence\ObjectManager" must me replaced by "Doctrine\Persistence\ObjectManager"

See this commit: https://github.com/doctrine/persistence/commit/132709c42a98472eadde6d5df4d0a2cc925f00ee

Cheers,

HanXHX

**Comment by Pheetbag** [comment]
Hi, there is some anwers about this? I'm still getting this problem as of today

**Comment by weaverryan** [comment]
Fully fixed in #570 :). Thanks!
