### ISSUE TITLE
Wrong namespace for ObjectManager in new DataFixtures

### ISSUE THREAD

**Issue by CloudMaker97** [symfony/maker-bundle#530]
**Symfony version(s) affected**: 5.0.2

**Description**  
Not sure if it's a concrete bug of Symfony but on creation of fixtures with the _orm-bundle_, deprecated ObjectManager namepace path is used. (Moved from Doctrine\Common\Persistence to Doctrine\Persistence). Either i'm not sure if that is a desired path cause of older doctrine versions.

**How to reproduce**  

1. "composer require orm-fixtures"
2. "php bin/console make:fixture TestFixture"
3. Check generated file

**Possible Solution**  

Change the use-namespace from
`use Doctrine\Common\Persistence\ObjectManager;`
to
`use Doctrine\Persistence\ObjectManager;`

**Comment by xabbuh** [comment]
@CloudMaker97 FYI, I have moved your issue as the MakerBundle has its own repository.

**Comment by LeJeanbono** [comment]
Thanks @xabbuh 
A related PR is in progress : https://github.com/symfony/maker-bundle/pull/518 for Doctrine

**Comment by CloudMaker97** [comment]
Thanks @xabbuh and @LeJeanbono 
I'll close this one.

**Comment by LeJeanbono** [comment]
Your welcome @CloudMaker97 , thanks for the issue
