### ISSUE TITLE
ENTITY : Type declarations for parameters with @Assert form validation is not correct

### ISSUE THREAD

**Issue by Ghostaunt** [symfony/maker-bundle#540]
**Symfony version(s) affected**: 5.0

**Description**  
When using php bin/console make:entity entities files are generated with type declarations for parameters (int, string...)
Imagine this Entity class 

```php
namespace App\Entity;
class Package {
     /**
     * @ORM\Column(type="int")
     *
     * @Assert\Positive
     */
    private $weight;

    public function setWeight(int $weight): self
    {
        $this->weight= $weight;

        return $this;
    }
}
```
As you can see before, weight must be positive (by the @Assert\Positive) so my form handle Request must check that. 

Imagine this route in a controller
```php
use App\Entity\Package as PackageEntity;
use App\Form\PackageType;
/**
* @Route("/send-data", name="send-data", methods={"POST"})
*/
public function sendData(Request $request)
{
    $form = $this->createForm(PackageType::class, new PackageEntity());
    $form->handleRequest($request);
}
```

As you know, every data sent by a simple html form are string, and in this case, the form handleRequest can't do his job because he can't set weight in the Package Entity cause of type declaration (int) in the parameter.

Here the PHP ERROR
> Expected argument of type "integer", "string" given at property path "weight"

I think, Symfony shouldn't add type parameters in methods when using php bin/console make:entity. Because here, the form can't handle the request if data can't be set in the Entity.

The simple solution here is to remove every type declaration in every setters method. And now, the form can do his job and use @Assert and return back errors if exists.

I hope my remark is understandable. 
Sorry in advance if my explaining are not good

**Comment by xabbuh** [comment]
FYI, I have moved the issue as the MakerBundle has its own repository.

**Comment by LeJeanbono** [comment]
Hi !
Can you give us the `PackageType` class ?
Thanks

**Comment by Ghostaunt** [comment]
You can close this ticket. I understand now why you ask me the FormType.
I thought FormType was only for view generation, when I change the weight input text to NumberType or IntergerType, whatever I send, it works.

Thanks!
