### ISSUE TITLE
Verification system after registration

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#542]
Hi,

It would be great to have an email address verification system after registering a user.

Thanks :)

**Comment by LeJeanbono** [comment]
Hi !
You mean connection with email ?

**Comment by seb-jean** [comment]
Hi :),

Laravel set up this system : https://laravel.com/docs/master/verification

**Comment by LeJeanbono** [comment]
You have to do it by yourself during registration.
Then during authentication, you can check if the email is validated with : https://symfony.com/doc/4.4/security/user_checkers.html

**Comment by jrushlow** [comment]
The concept of verification after registration falls inline with a component that @weaverryan & I are putting together now.. It will take a moment or so before I have a PR set to go, but I can definitely start getting some pieces of the puzzle together based on the work we're doing with the other project.. I'll keep ya posted on the progress..

**Comment by jrushlow** [comment]
@seb-jean  just a quick update, haven't forgotten about this. I've actually got the bulk of the groundwork taken care of. Unfortunately with all of the COVID-19 stuff happening, the ramifications outside the front door have also had an affect here at the keyboard as well.  

Hopefully I'll be able to shed some more light on this feature shortly.. In the meantime, I hope all is well & happy coding!

**Comment by seb-jean** [comment]
Good Luck @jrushlow

**Comment by jrushlow** [comment]
Just another quick update - we are progressing on the feature. I'm somewhat reluctant to point this out as it's still a WIP, not ready for use, and design philosophies are subject to change... Having said that - https://github.com/symfonycasts/verify-email-bundle 

As I've yet to write up any sort of documentation, anyone that feels like reading the code and providing feedback on use cases we haven't covered, please open up an issue in that repo. This may help address some edge cases that we haven't thought of yet while we are still early on in development. 

I'm working on the maker implementation/PR that will use this bundle in parallel.. 

To reiterate, the bundle is not yet ready for use in a production application.
