### ISSUE TITLE
Could not find package symfony/maker-bundle

### ISSUE THREAD

**Issue by kironet** [symfony/maker-bundle#56]
Symfony 3.3 Flex

`composer require maker
`

=>

> [InvalidArgumentException]                                                                                                                            
>   Could not find package symfony/maker-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
>

**Comment by nicolas-grekas** [comment]
correct, the bundle is not released yet, you need to "require maker:dev-master"
