### ISSUE TITLE
[Question] targetEntity syntax

### ISSUE THREAD

**Issue by rogeriolino** [symfony/maker-bundle#561]
Hi, I've a question about the generated relationship annotation, that is using the fqcn as string instead of `Target::class` (forcing the import of the class).

The maker-bundle is able to receive an PR with this changes or have some reason to keep the string?

**Example:**

Generated annotation:

```php
/**
 * @ORM\ManyToOne(targetEntity="App\Entity\User")
 * @ORM\JoinColumn(nullable=false)
 */
private $user;
```

Instead of force to import target class:

```php
/**
 * @ORM\ManyToOne(targetEntity=User::class)
 * @ORM\JoinColumn(nullable=false)
 */
private $user;
```

ps: Currently the maker already use import statement to reference the class in setter/getter methods.

**Comment by weaverryan** [comment]
Hi!

To be honest, I didn't realize the `User::class` syntax works. Yes, I would be open to a PR to change this.

Thanks!
