### ISSUE TITLE
Support for 3.3

### ISSUE THREAD

**Issue by kironet** [symfony/maker-bundle#57]
Maybe add support for Symfony 3.3 + Flex? Right now old generator is not working with flex and this one is for SF3.4+

**Comment by fabpot** [comment]
Even if Flex is somewhat supported on 3.3, I would really recommend you to use 3.4. There is no guarantee that all the ecosystem will work well with Flex and 3.3.

**Comment by javiereguiluz** [comment]
I agree. And upgrading from 3.3 to 3.4 should be trivial (3.x to 4.x can take some time). So let's close this as "won't fix". Thanks!
