### ISSUE TITLE
make:auth and security.yaml path

### ISSUE THREAD

**Issue by aelfannir** [symfony/maker-bundle#576]
* **maker.yaml**
```
maker:
    root_namespace: 'App\Admin
```
In my project this command ```php bin/console make:auth --kernel=admin``` should update **security.yaml**, exist in path **config/Admin/packages/** not **config/packages/**

I've tested ```make:enitity/controller --kernel=admin```, and they're working fine, but ```make:auth --kernel=admin```, throws an exception;
**[ERROR] The file "config/packages/security.yaml" does not exist. This command requires that file to exist so that it  can be updated.**

https://github.com/symfony/maker-bundle/blob/3585a2fad7c93159a35455361ab35ac224f258c0/src/Maker/MakeAuthenticator.php#L81

EDIT:
symfony/maker-bundle:  v1.14.6

**Comment by weaverryan** [comment]
Hi @aelfannir!

Hmm. There actually is no `--kernel=` option on any of the commands. Is it possible you're in a project that is doing some custom stuff?

Cheers!

**Comment by aelfannir** [comment]
@weaverryan yes, multiple kernels
https://symfony.com/doc/current/configuration/multiple_kernels.html

**Comment by aelfannir** [comment]
```--kernel``` is a custom option, i use it to chose which kernel to instantiate.

**Comment by weaverryan** [comment]
Got it! If you're adding a custom option somehow to the maker, then it's up to you to tweak MakerBundle to work for your situation. There's no way that MakerBundle can anticipate your directory structure if you have multiple kernels. If you need a "hook point" to make such a customization, you can definitely create a pull request for that :).

Cheers!

**Comment by aelfannir** [comment]
Alright, thank you!
