### ISSUE TITLE
[RFC] Add a make:action command

### ISSUE THREAD

**Issue by webda2l** [symfony/maker-bundle#58]
In the same spirit of make:controller but for those who prefers ADR action instead controller

By example:

```
<?php

namespace App\Action;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

class ShowCategory
{
    /**
     * @Route("/category", name="category")
     */
    public function __invoke()
    {
        return new Response('Welcome to your new action !');
    }
}

```

I have time to add a PR tomorrow I think

**Comment by Simperfit** [comment]
+1

**Comment by fabpot** [comment]
I'm actually :-1: on this one. It's exactly the same as the current `make:controller` command except that the method name would be `__invoke()`. I don't think it deserves another command. Generators creates files with code you own, which should be modified anyway.

**Comment by yceruto** [comment]
If an overriding template mechanism is approved for this bundle (https://github.com/symfony/maker-bundle/issues/33) then this kind of need may be easier to achieve (e.g. https://github.com/symfony/maker-bundle/pull/50/files#diff-7d25cf7d5e19ace152dd9df61498d519).

Many companies could adapt the bundle templates to their own conventions, but still the promise of BC is a pending topic in this sense.

**Comment by webda2l** [comment]
Ok I don't go further with a PR for now and let you decide if you want close this issue or not.

**Comment by codedmonkey** [comment]
I don't see a reason not to do it unless we want to limit the number of commands in the bundle.

**Comment by javiereguiluz** [comment]
I don't want to keep issues open for months, so I propose to close this one. The first reason is that in Symfony most people use controller or action indifferently, so `make:action` can be understood as creating an entire controller and also, adding a new method to an existing controller.

The second reason is that we're not 100% convinced yet about promoting the ADR philosophy (see this pending PR in the Symfony Docs for example: https://github.com/symfony/symfony-docs/pull/8153). We are not saying that ADR is wrong. We just don't want (yet) to promote a whole new way of doing things.
