### ISSUE TITLE
[ANSI & Maker-Bundle] make:entity recognizes an entity when it does not exist

### ISSUE THREAD

**Issue by Alphamplyer** [symfony/maker-bundle#583]
**My Symfony version(s) affected**: 5.0.2
![version](https://user-images.githubusercontent.com/42153930/71781429-209b3600-2fcf-11ea-8844-e852331209f9.png)
**Friend Symfony version(s) non affected**: 5.0.2
![version2](https://user-images.githubusercontent.com/42153930/71781936-b2f20880-2fd4-11ea-8749-53833c0356e2.png)
We have the exact same configuration with the command `composer show symfony/console`
And I'm not sure it's a link, but ANSI colors don't work for me.
I've reinstall php, composer, symfony, and delete all configuration. Nothing work.

**Description**  
When I want to create an entity with `make:entity` and another with a name that is a "prefix" of it, Symfony tells me that the entity already exist. But it works on another PC. Don't know why.
In my case : the 'Contestant' entity already exist, and I want to create the 'Contest entity'. The 'Contest' entity does not exist but symfony tells me the opposite, recognizing 'Contest' as 'Contestant' .

![Image 1](https://user-images.githubusercontent.com/42153930/71781579-abc8fb80-2fd0-11ea-9cdd-078fda48a6cb.png)
![Image 2](https://user-images.githubusercontent.com/42153930/71781580-af5c8280-2fd0-11ea-8b47-eeda598273eb.png)
Friend Screen shot :
![Image 4](https://user-images.githubusercontent.com/42153930/71781910-673f5f00-2fd4-11ea-8048-15061aed5158.png)

**How to reproduce**  
To reproduce the bug, i've start a new project with the following command :
`symfony new project-test --full`
I've create an entity named 'Contestant' with a 'name' property.
And when I've created an entity named 'Contest', I have had this issue.
![Image 3](https://user-images.githubusercontent.com/42153930/71781806-1d09ae00-2fd3-11ea-93e6-2edd268a47cc.png)

**Comment by javiereguiluz** [comment]
@Alphamplyer thanks for reporting this issue and for providing all these details. Since it looks closely related to the MakerBundle I've transferred the issue from symfony/symfony to symfony/maker-bundle.

**Comment by LeJeanbono** [comment]
Any link ? #451

**Comment by monkeyArms** [comment]
I have this same problem on Windows 10 using git bash via [ansicon](https://github.com/adoxa/ansicon).  My shell path for the terminal is "C:\bin\ansi160\x64\ansicon.exe" -p C:\Program Files\Git\bin\bash.exe.

ANSI encoding for the output is also wonky:

![image](https://user-images.githubusercontent.com/1403262/84549328-586c7f00-accd-11ea-9e94-b52b4aa6b6ff.png)
