### ISSUE TITLE
Impossible to install maker-bundle then orm-pack

### ISSUE THREAD

**Issue by sarramegnag** [symfony/maker-bundle#609]
Hi everyone,

I'm not sure this is an issue, but I started a new project today and realized that adding support to doctrine/inflector:^2.0 8 days ago is breaking the install of symfony/orm-pack.

To reproduce :
```
composer create-project symfony/skeleton symfony
cd symfony
composer req maker --dev
composer req orm
```

If done in the other order, installation looks ok :
```
composer create-project symfony/skeleton symfony
cd symfony
composer req orm
composer req maker --dev
```

I guess the solution would be to downgrade doctrine/inflector version installed after maker requirement in order to install orm-pack, but not sure that's the expected behavior.

What do you think ?

**Comment by weaverryan** [comment]
Hi @sarramegnag!

Excellent report - I can repeat it. And you're right about the cause - it's that your `composer.lock` file gets locked at `doctrine/inflector` 2.0. I'm... trying to think of a decent solution ;) 

Cheers!

**Comment by sarramegnag** [comment]
Yes, finally I fixed it by running composer req doctrine/inflector "^1.4". But I think you should do something so it works out of the box without having to manually downgrade the version.

Good luck, I have no idea about how to do it 😓
