### ISSUE TITLE
make:entity command changes the group of the file

### ISSUE THREAD

**Issue by Cartman34** [symfony/maker-bundle#622]
**Symfony version(s) affected**: 5.0.8
maker-bundle version is v1.17.0

**Description**  
Command **make:entity** changes the group of the file.

**How to reproduce**  
On existing entity class file, set user of you entity file to **youruser**:www-data and permission to 750.
Use `php bin/console make:entity` to add one field with **youruser**.
The file's group is now **youruser**.

**Comment by jrushlow** [comment]
Howdy @Cartman34 I'm tried duplicating this locally to no success. Going through the code, in `make:entity` I do not see anyplace where we are taking user input to append / set / change file permissions on the entity file that is being manipulated. 

I'm going to close this issue for now, If you still are having issues with this problem, please feel free to re-open it and provide additional details about your development environment. 

Side note: I would not suggest setting execute (`7`) permissions on any file that does not explicitly need to be executed. E.g. a bash script would need `07xx` where as an entity class only needs to be readable / writable (`0664`) by the owner and possibly the group. Allowing others to read (`4`) would not hurt anything depending on your specific setup.
