### ISSUE TITLE
interactivity doesn't work

### ISSUE THREAD

**Issue by Jhontejada13** [symfony/maker-bundle#623]
In none of the make options interactivity works, when creating an entity does not give me the option to create from the terminal the fields that I require in it, it does not allow me to execute the make: auth command because the first value is null. , then abort the auth creation.

If anyone can help me I will be very grateful

**Comment by LeJeanbono** [comment]
Can you provide some informations on your environment ?
Which OS / shell type ?

**Comment by jrushlow** [comment]
I'm closing this issue for now, if you're still having problems, please let us know! Thanks..
