### ISSUE TITLE
Documenting code

### ISSUE THREAD

**Issue by Droutin** [symfony/maker-bundle#631]
Hi,

Is there option to enable automatic code documenting?
Like this.
/**
     * @param integer $team_id
     * @return $this
     */

Symfony 3.4 maker was generating with documentation.

**Comment by ckrack** [comment]
These kind of DocBlocks provide no value in PHP7 - the information is present as type hints and a proper code editor will show them.
If you find makers that do not generate code with typehints in all places, feel free to point them out.

**Comment by jrushlow** [comment]
> Is there option to enable automatic code documenting?

No - as @ckrack pointed out, there is no real value is docBlocks that declare repetitive context. As we are slowly shifting the code generated MakerBundle to utilize PHP's type system, I do not think there would be any additional value you in this. However, if there is anything in particular where docBlocks would prove better suited than type hints, please let us know!  Thanks @Droutin
