### ISSUE TITLE
Symfony CLI prompt bug

### ISSUE THREAD

**Issue by slykikz** [symfony/maker-bundle#651]
After i started my project with full, i wanted to create an user with the command php bin/console make:user and the CLI doesn't asks me for any confirmation, it makes choices itself.

OS : Windows 10

Symfony Version : 4.4.* 

PHP Version : 7.4.0 (cli) (built: Nov 27 2019 10:14:18)

Any solutions for this problem ?

**Comment by slykikz** [comment]
fggfgfgfg

**Comment by azarual** [comment]
i got tha same probleme here there is not interactions it is a wired behavior

**Comment by azarual** [comment]
@fabpot you transfered the issue here but i think it's related to cli not to maker and here is why:
i have the same project on two pc's with diffient version of cli 
is working fine on one but not on the other
