### ISSUE TITLE
make:entity generates string getter/setter instead of float

### ISSUE THREAD

**Issue by thomas2411** [symfony/maker-bundle#655]
If I run 

> php bin/console make:entity

 like this:

    New property name (press <return> to stop adding fields):
    > amount

    Field type (enter ? to see all types) [string]:
    > decimal

    Precision (total number of digits stored: 100.00 would be 5) [10]:
     > 

     Scale (number of decimals to store: 100.00 would be 2) [0]:
     > 2

     Can this field be null in the database (nullable) (yes/no) [no]:
     > 

I get 

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $amount;

which is OK

but the getter and setter look like this:

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

while I think it should look like this:

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

**Comment by noniagriconomie** [comment]
@thomas2411 according to https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html#decimal
it is a string that is returned

so maybe you should override yourself the code generated to have proper/desired typehint

**Comment by thomas2411** [comment]
Yes, I do the override. I just thought it is a better solution. I read the docs now and the comment about "_For compatibility reasons (...)_" is probably more important here. Although probably 99% of cases is better to use float while in 1% string to keep the precision. 
Thank you.
