### ISSUE TITLE
make:entity ability to auto-add php 7.4 typing

### ISSUE THREAD

**Issue by rbaarsma** [symfony/maker-bundle#669]
I love this bundle. Thank you guys for making it :+1: 

Now I'm sure most of us are upgrading to php 7.4 and the ability to either regenerate your entities with proper typing, or at least create new entities with typing, would be awesome. I'm well aware this should be a flag or question, because it's not for everyone (yet). Potentially it could also be the default of a new major version.

I've been trying for a couple of hours to see if I can simply extend the maker bundle to make this possible, but all the MakeXXX classes are final and many of their dependencies are internal. Not sure why? Makes it hard to implement this for our project.. so would be great if it can be a general feature. Would not mind to contribute :+1:

**Comment by rbaarsma** [comment]
I just noticed https://github.com/symfony/maker-bundle/issues/478 and https://github.com/symfony/maker-bundle/issues/575, but both are closed and I think this is becoming more and more relevant. Not sure why we can't at least have a flag. Symfony is far from against typing your own code base and maker bundle generates code for the codebase, not for Symfony framework

**Comment by weaverryan** [comment]
I am "pro" this issue. I would implement it as a configuration option for now.

**Comment by DuboisS** [comment]
#689

**Comment by Superkooka** [comment]
#773

**Comment by jrushlow** [comment]
Typed properties have been added as of `v1.44.0`
