### ISSUE TITLE
[BUG][Controller] getParameter is not available

### ISSUE THREAD

**Issue by sescandell** [symfony/maker-bundle#67]
Hi,

When we generate a controller from the `make:controller` command and Twig is available, the template generated is invalid: it uses the `getParameter` method which is not available on a `AbstractController`.

**Comment by yceruto** [comment]
related to https://github.com/symfony/maker-bundle/pull/64

**Comment by javiereguiluz** [comment]
Closing as fixed because we removed the `getParameter()` call in #64.
