### ISSUE TITLE
make:unit-test in wrong directory

### ISSUE THREAD

**Issue by rbaarsma** [symfony/maker-bundle#670]
When running make:unit-test, the test is created under `src/Tests`. Symfony standard is to create tests under `tests`. Is there any way to fix this?

**Comment by BatsaxIV** [comment]
Hi @rbaarsma,

I've checked with the last version of the bundle (v1.21.1) and the test file is generated under the `tests` directory (at root level).  
Could you check again or try updating your library?

**Comment by jrushlow** [comment]
@rbaarsma can you confirm you are still having this issue?

**Comment by rbaarsma** [comment]
@BatsaxIV @jrushlow 

I've updated to v1.25.0 in my Symfony 5.1 project.
Still facing the same issue.

```
rein@swc:~/develop/myproject$ bin/console -vvv make:unit-test

 The name of the unit test class (e.g. UtilTest):
 > UtilTest

 created: src/Tests/UtilTest.php

           
  Success! 
```

I checked for specific config, but can't find anything for maker or related to "tests" directory

**Comment by BatsaxIV** [comment]
Hi @rbaarsma,

I've checked again (sf 5.2 and maker 1.25) : 

``` 
sf-last git:(master) ✗ bin/console -vvv make:unit-test

 The name of the unit test class (e.g. UtilTest):
 > UtilTest

 created: tests/UtilTest.php


  Success!
```

Could you check your composer.json file for this?

```
"autoload-dev": {
    "psr-4": {
        "App\\Tests\\": "tests/"
    }
},
```

**Comment by jrushlow** [comment]
I believe this has been resolved. Please let us know if you're still experiencing the problem and we'll re-open the issue. Thanks!

**Comment by hoang-danny05** [comment]
Hi, I have version ^1.67 required in my composer and it is still creating tests in `src/Tests`. I'm using PHP 8.3 with symfony v7.4. 

I did install this manually, so I'm not sure if this is an issue on my end.
