### ISSUE TITLE
When using make:entity, why does it take so long before asking for the entity name?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/maker-bundle#677]
It's always seemed a little odd to me that it should take (on my VM) at least a second before it asks the name of the entity. Is this expected?

**Comment by jrushlow** [comment]
I'm not quite sure I'm following you. Can you provide the steps you are taking to get to the point where you suspect an issue?

**Comment by ChangePlaces** [comment]
a simple `make:entity` command doesn't appear instantly as I thought it would.

**Comment by jrushlow** [comment]
I believe this is related to you VM and not MakerBundle
