### ISSUE TITLE
Collection getters generated as not nullable by default

### ISSUE THREAD

**Issue by ilya-realforce** [symfony/maker-bundle#682]
**Problem:** when generating an entity with collection fields (e.g. `OneToMany` relationship), the generated getter has no `null` as possible return value, which causes problems, because per Doctrine official doc, entity constructor **is not being called** when Doctrine creates entities itself (e.g. by calling `find` method of a repository).

Quote: `The constructor of an entity is only ever invoked when you construct a new instance with the new keyword. Doctrine never calls entity constructors, thus you are free to use them as you wish and even have it require arguments of any type.`
Link: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/architecture.html

Therefore, maker bundle should **not** use entity constructor as a place of initializing fields, and all getters should allow `null` as a return value. Or, some kind of lifecycle events should be used to initialize collection objects.

Example of a generated entity that causes problem:
```
class Contact {
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Email", mappedBy="contact")
     */
    private $emails;

    public function __construct()
    {
        $this->emails = new ArrayCollection();
    }

    /**
     * @return Collection|Email[]
     */
    public function getEmails(): Collection
    {
        return $this->emails;
    }

    ...
}
```

Example of an error:
```
                "code": 0,
                "message": "Return value of App\\Entity\\Contact::getEmails() must implement interface Doctrine\\Common\\Collections\\Collection, null returned",
                "trace": [
                    {
                        "file": "/var/www/html/var/cache/dev/doctrine/orm/Proxies/__CG__AppEntityContact.php",
                        "line": 1357,
                        "function": "getEmails",
                        "class": "App\\Entity\\Contact",
                        "type": "->",
                        "args": []
                    },
...
```

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
