### ISSUE TITLE
Make entity error on Symfony 5.2

### ISSUE THREAD

**Issue by FlrgFlorent** [symfony/maker-bundle#683]
When i want to add a field to my entity, i write the name of my new field and i have this error :

```
In Validator.php line 158:
Argument 2 passed to Symfony\Bundle\MakerBundle\Validator::validateDoctrineFieldName() 
must be an instance of Doctrine\Common\Persistence\ManagerRegistry, 
instance of Doctrine\Bundle\DoctrineBundle\Registry given, 
called in /application/vendor/symfony/maker-bundle/src/Maker/MakeEntity.php on line 303
```

**Comment by jrushlow** [comment]
What version of Maker Bundle & Symfony are you using? Have you tried composer update?

**Comment by mahono** [comment]
I have the same issue with Symfony 5.2-RC1 and MakerBundle 1.17.0

**Comment by mahono** [comment]
Strange that composer installed 1.17 while 1.23 is the current one.

I just updated to 1.23 and make:entity now works. :o)

**Comment by thedomeffm** [comment]
I had exactly the same problem!
Update the bundle to 1.24 fixed the issue.

**Comment by maksimovichd** [comment]
> 
> 
> I had exactly the same problem!
> Update the bundle to 1.24 fixed the issue.

how did you update?

**Comment by thedomeffm** [comment]
@maksimovichd 
Update the Version in your composer.json file

**Comment by maksimovichd** [comment]
> 
> 
> @maksimovichd
> Update the Version in your composer.json file

it didn't help me or I did it wrong, show an example

**Comment by fd6130** [comment]
> Strange that composer installed 1.17 while 1.23 is the current one.
> 
> I just updated to 1.23 and make:entity now works. :o)

I think it is because of the `doctrine/inflector 2`, install version 1.4 and update your `maker-bundle` to latest version.

**Comment by jrushlow** [comment]
@FlrgFlorent or anyone else experiencing this problem - would it be possible for you to provide your `composer.json`, `composer.lock`, & the output of `composer outdated`? Thanks in advance!

**Comment by FlrgFlorent** [comment]
It's ok with an update for me :)
