### ISSUE TITLE
Skip php-cs-fixer check on php 8 for now

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#713]
The php 8 tests fails mostly because dependencies we need aren't compatible yet.

But others that *might* pass are failing because php-cs-fixer doesn't support php 8, so the php-cs check on the generated code fails. 

To make it more clear which tests are *truly* failing, we should (for now) disable the php-cs-fixer check in the test for php 8. We can re-enable it later when php-cs-fixer supporst php8.

**Comment by OskarStark** [comment]
This is already fixed in https://github.com/symfony/maker-bundle/pull/715
