### ISSUE TITLE
Docs vs. repo code style

### ISSUE THREAD

**Issue by piotrgradzinski** [symfony/maker-bundle#72]
Maybe this is something obvious but wondering... 

Within the repo code we use short array syntax `[]` but in docs (https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html) we are using older one - `array()`. 

Shouldn't this be unified?

**Comment by weaverryan** [comment]
Good catch :). We should use the short syntax for consistency.

**Comment by piotrgradzinski** [comment]
@weaverryan - fix on the way :)

**Comment by javiereguiluz** [comment]
Fixed by #73.
