### ISSUE TITLE
Suggestion for `make:entity`: Wizard for the `nullable` question

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/maker-bundle#721]
After https://github.com/symfony/maker-bundle/issues/685 and https://github.com/symfony/maker-bundle/issues/687 this is my third issue about the `nullable` topic :-)

The fact that after XY years of Symfony/Doctrine development there has no consensus been reached in this "simple" question, shows me: It is not as simple as it looks ;-)

So what about a wizard? Like the (IMO excellent) relationship wizard.

Sketch:

1: Do you want to include this property in a form (incl. EasyAdmin)?
Yes => nullable
No => 2

2: Can this property be blank/empty when persisting an entity to the database?
Yes => nullable
No => non-nullable

Or separate the database layer from the PHP (i.e. setter/getter) layer?:

1: Do you want to include this property in a form (incl. EasyAdmin)?
Yes => 2
No => 3

2: Do you allow users to leave this field blank?
Yes => nullable setter/getter, nullable database field
No => nullable setter/getter, `Assert\NotBlank`, non-nullable database field

3: Can this property be blank/empty when persisting an entity to the database?
Yes => nullable
No => non-nullable (or question 4?)

4: Do you allow this property to be empty *before* persisting to the database? (Answering NO means you always need to set this property immediately when creating a new entity)
Yes => nullable setter/getter, `Assert\NotBlank` (?), non-nullable database field
No => non-nullable setter/getter, non-nullable database field

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
