### ISSUE TITLE
ResetPassword : error tokenLifetime display

### ISSUE THREAD

**Issue by louismariegaborit** [symfony/maker-bundle#727]
Hi,

Display of tokenLifetime value is incorrect.
Example: when lifetime = 7200, tokenLifetime display 3 hours in the email instead of 2 hours.

https://github.com/symfony/maker-bundle/blob/f1093e98de2ac9816ec336fba68367da377b2677/src/Resources/skeleton/resetPassword/twig_check_email.tpl.php#L6

https://github.com/symfony/maker-bundle/blob/f1093e98de2ac9816ec336fba68367da377b2677/src/Resources/skeleton/resetPassword/twig_email.tpl.php#L7

**Comment by jrushlow** [comment]
I have a PR to address #632 but have not had the free time in weeks past to wrap this fix up. We should have it buttoned up and good to go shortly..

**Comment by jrushlow** [comment]
For reference, we have an issue open in `ResetPasswordBundle` as well https://github.com/SymfonyCasts/reset-password-bundle/issues/119

**Comment by louismariegaborit** [comment]
The best solution is tokenLifetime/3600.
When tokenLifetime is over 12 hours, your solution doesn't work.
