### ISSUE TITLE
Problem with documentation: you cannot install with --dev on Symfony 5

### ISSUE THREAD

**Issue by gesior** [symfony/maker-bundle#729]
Installation following this guide:
https://github.com/symfony/maker-bundle/blob/master/src/Resources/doc/index.rst
( https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html )
```
composer require symfony/maker-bundle --dev
```
make it not possible to deploy project to production environment.

It should be changed to:
```
composer require symfony/maker-bundle
```

All prod and dev bundles must be installed via composer.
You can skip external libraries in composer (ex. php-stan), but not Symfony bundles which are added in **config/bundles.php**

How to reproduce:
```
symfony new test
cd test
composer require symfony/maker-bundle --dev

// make it like on production
rm -rf vendor
composer install --no-dev
```
result:
```
(... packages install without problem ...)
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#71
!!    #message: """
!!      Attempted to load class "MakerBundle" from namespace "Symfony\Bundle\MakerBundle".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
!!    #line: 74

```

**Comment by wouterj** [comment]
You shouldn't enable the MakerBundle in production, only in dev. This is also the default configuration if you're using symfony flex:

```php
// config/bundles.php

return [
    // ...
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];
```

Once you have this, it's perfectly fine not to have maker bundle installed on your production server. See e.g. https://3v4l.org/kD1ID

**Comment by jrushlow** [comment]
@gesior Can you confirm @wouterj solution solves your problem?

**Comment by gesior** [comment]
> @gesior Can you confirm @wouterj solution solves your problem?
It does not work for one obvious reason. There is:
```
Symfony\Bundle\MakerBundle\MakerBundle::class
```
Code is trying to get `class` on class X\X\X\X and it's not in vendor, so app report error.

Setting it there to default value:
```
Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
```
make Symfony load that bundle only in `dev` env, but class must be in vendor anyway.
That's what I'm reporting in this issue.

**Comment by wouterj** [comment]
See the snippet I referenced: https://3v4l.org/kD1ID A class is not loaded (and does not have to exists) in order to be able to call `::class` on it.

**Comment by oleg-andreyev** [comment]
while it's late for an answer, the reason why Symfony is searching for MakerBundle is because "cache:clear"  command is executed in development mode, see `composer.json auto-scripts`. You need to execute "cache:clear -e prod --no-debug" to avoid searching for MakerBundle

**Comment by Vin57** [comment]
The documentation specify what should be done in this case

https://symfony.com/doc/current/deployment.html#c-install-update-your-vendors
> If you get a "class not found" error during this step, you may need to run export APP_ENV=prod (or export SYMFONY_ENV=prod if you're not using [Symfony Flex](https://symfony.com/doc/current/setup.html#symfony-flex)) before running this command so that the post-install-cmd scripts run in the prod environment.

It worked for me
