### ISSUE TITLE
Fix typo in make:docker:database driver for postgres

### ISSUE THREAD

**Issue by delyro** [symfony/maker-bundle#748]
See line:
https://github.com/symfony/maker-bundle/blob/40b49abf01810453f73e3e239759f1736607f029/src/Docker/DockerDatabaseServices.php#L92

Driver name for postgres is "pdo_pgsql" not "pdo_pdsql". Because of this, selecting postgres throws error:

![image](https://user-images.githubusercontent.com/39466319/100379199-c656f980-3014-11eb-83d8-447b9b07f247.png)

**Comment by jrushlow** [comment]
thanks @delyro for the heads up! We have a fix ready to go on this and should be merged soon.
