### ISSUE TITLE
make controller generates controller with attributes but symfony does not support it yet

### ISSUE THREAD

**Issue by Nek-** [symfony/maker-bundle#750]
Symfony 5.2 will support attributes for routes, but it's not the case for Symfony 5.1. I just made a fresh install and used the maker, the generated route was the following:

```php
#[Route('/main', name: 'main')]
public function index(): Response
{
       
}
```

This doesn't work. It seems critical but I didn't see any issue in that way so here it is.

- PHP version: 8.0
- Bundle version: 1.24.2

**Comment by jrushlow** [comment]
Note to self: PRs #725 & #728 introduced attributes in maker

It appears we're checking for the correct PHP version in the `PhpCompatUtil::class` but never verify what version of Symfony is being used.

@Nek- Thanks for opening an issue on this!
