### ISSUE TITLE
Doctrine inflector 2 revisit

### ISSUE THREAD

**Issue by mmarton** [symfony/maker-bundle#756]
Since the today released doctrine orm 2.8, maker-bundle is the last pacakage that stuck on doctrine inflector 1. (in my proejects)

> $ composer why-not doctrine/inflector:2
symfony/maker-bundle  v1.24.2  requires  doctrine/inflector (^1.2)  

As said in this PR: https://github.com/symfony/maker-bundle/pull/611

> Dropping support for v2 isn't really a fix, but will make it more
compatible with the ecosystem at the current time. Later, especially
when doctrine/orm allows 2, we can again.

**Comment by jrushlow** [comment]
thanks @mmarton for the heads up! I've created a PR to reintroduce support, I don't see a problem with this as long as our tests pass. stay tuned!
