### ISSUE TITLE
Update security.yaml when running make:auth

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#76]
This is a small first step towards my bold plan of having the MakerBundle completely reinvent the experience of working with Symfony security :).

When you run `make:auth`, I would like to also update the user's `security.yaml` file. In future commands (like `make:user`) I would like to make even more changes to this file. But, there are some complications:

* We must update the file without changing *anything* else - like spacing or comments. That means `Yaml::dump()` is out of the question

* We must be able to smartly detect that there is only 1 firewall and update it (i.e. we need to be smart enough to detect and ignore any `dev` firewall)

* Before writing the new `security.yaml` file, we should validate that our new YAML is valid YAML.

* If we cannot figure out how to patch their `security.yaml`, then we should not do it and print a clear message and what they need to do at the bottom.

**Comment by javiereguiluz** [comment]
I love this idea ... but I'm strongly *against* implementing it. The bad experiences of SensioGeneratorBundle trying to edit YAML files is a big red flag for not attempting this.

A viable solution is what you said in your last bullet: show a clear message explaining the needed changes.

**Comment by wouterj** [comment]
As far as I understand things, this issue has been fixed by https://github.com/symfony/maker-bundle/pull/250
