### ISSUE TITLE
Entity class generation (php bin/console make:entity EntityClassName ) failed in Symfony 4.4

### ISSUE THREAD

**Issue by maksimovichd** [symfony/maker-bundle#762]
**What ?**

Failed to generate entity class with php bin/console make:entity

**Error**

Argument 2 passed to Symfony\Bundle\MakerBundle\Validator::validateDoctrineFieldName() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of D
  octrine\Bundle\DoctrineBundle\Registry given, called in D:\projects\logistics-light\vendor\symfony\maker-bundle\src\Maker\MakeEntity.php on line 303

**Comment by fd6130** [comment]
See #683 .

**Comment by jrushlow** [comment]
@maksimovichd can you provide the output of `composer outdated`

**Comment by weaverryan** [comment]
Closing - please let us know if `composer update` doesn't fix the problem. Cheers!
