### ISSUE TITLE
Missing package: to use the make:registration-form command, run: composer require form

### ISSUE THREAD

**Issue by FintinaM** [symfony/maker-bundle#763]
I am trying to use the make:registration-form and i get the following error:
Missing package: to use the make:registration-form command, run: composer require form

I want to point out that this is a fresh instalation of symfony 5.2
I also tried the following:
 - composer update

Below you have the details of composer.json and composer diagnose

composer.json:
`{
type: "project",
license: "proprietary",
require: {
php: ">=7.4.7",
ext-ctype: "*",
ext-iconv: "*",
doctrine/orm: "^2.7",
symfony/console: "5.1.*",
symfony/dotenv: "5.1.*",
symfony/filesystem: "5.1.*",
symfony/flex: "^1.3.1",
symfony/form: "5.2.*",
symfony/framework-bundle: "5.1.*",
symfony/mailer: "5.1.*",
symfony/maker-bundle: "^1.20",
symfony/messenger: "5.1.*",
symfony/security-bundle: "5.1.*",
symfony/twig-bundle: "5.1.*",
symfony/yaml: "5.1.*",
symfonycasts/verify-email-bundle: "^1.0",
twig/extra-bundle: "^2.12|^3.0",
twig/twig: "^2.12|^3.0"
},
config: {
optimize-autoloader: true,
preferred-install: {
*: "dist"
},
sort-packages: true
},
autoload: {
psr-4: {
App\: "src/"
}
},
autoload-dev: {
psr-4: {
App\Tests\: "tests/"
}
},
replace: {
paragonie/random_compat: "2.*",
symfony/polyfill-ctype: "*",
symfony/polyfill-iconv: "*",
symfony/polyfill-php72: "*",
symfony/polyfill-php71: "*",
symfony/polyfill-php70: "*",
symfony/polyfill-php56: "*"
},
scripts: {
auto-scripts: {
cache:clear: "symfony-cmd",
assets:install %PUBLIC_DIR%: "symfony-cmd"
},
post-install-cmd: [
"@auto-scripts"
],
post-update-cmd: [
"@auto-scripts"
]
},
conflict: {
symfony/symfony: "*"
},
extra: {
symfony: {
allow-contrib: false,
require: "5.2.*",
docker: true
}
},
require-dev: {
doctrine/doctrine-fixtures-bundle: "^3.3",
symfony/stopwatch: "^5.1",
symfony/web-profiler-bundle: "^5.1"
}
}
`

composer diagnose:
`Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.17 => 2.0.8)
Composer version: 1.10.17
PHP version: 7.4.11
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020`

**Comment by sadikoff** [comment]
Hey @FintinaM 

Your `composer.json` looks a little weird. You said that you use Symfony 5.2 but most of your packages are locked with `5.1.*` constraint and only `symfony/form` uses `5.2.*`. I guess your project is misconfigured, and something was installed not correctly! If it's a clean project try to completely re-create it, otherwise, fix all `symfony/` constraints to point to 5.2 version and run `composer update` also check installed recipes with `composer recipes` command and update or reinstall if needed!

**Comment by FintinaM** [comment]
Thank you! Problem was solved by changing the constraints in the composer.json. I have no ideea how i didn`t see it. 
Thank you!
