### ISSUE TITLE
[QUESTION] Update for email verify after new user registration

### ISSUE THREAD

**Issue by SmashScharrer** [symfony/maker-bundle#767]
Hello,

I have discovered last week an update with MakerBundle when we create a new registration form. We can send an email with link. But, I don't understand how to use this new feat.
Do you have a tutoriel or a video/topic to explain this ?

Thanks ^^

**Comment by jrushlow** [comment]
Howdy @SmashScharrer - I believe you are referring to the email verification functionality that was introduced a while back. This of course is an optional feature, but if you add the `symfonycasts/verify-email-bundle` as a dependency and run `make:registration-form`; MakerBundle will set you up to provide email verification for users. Check out https://github.com/symfonycasts/verify-email-bundle for more information and feel free to ask any questions you may have!

**Comment by jrushlow** [comment]
@SmashScharrer I'm going to close this issue for now, but feel free to re-open it if you have anymore questions!
