### ISSUE TITLE
variable $user not affected in RegistrationController verifyUserEmail()

### ISSUE THREAD

**Issue by Ronan-Lenor** [symfony/maker-bundle#789]
Hello,
afterr using `symfony console make:registration-form` i registered a new user and click on the link provided by the mail.
But bacck to my website ive got this error :

ErrorException
HTTP 500 Internal Server Error
Notice: Undefined variable: user

myproject\src\Controller\RegistrationController.php (line 80) 
method : verifyUserEmail()

```
  $userRepository->find($id);

  if (null === $user) {
      return $this->redirectToRoute('app_home');
  }
```

i didn't see any $user variable affected near `$userRepository->find($id);`

something went wrong in the code generation i guess, maybe a bug from the CLI ? =/

here is the step i used:
symfony console make:registration-form
	@UniqueEntity : y
	send an email to verify : y
	include the user id in the verification link : y
	anaddressfortesting@gmail.com
	Hello There
	automatically authenticate the user after registration : n

**Comment by jrushlow** [comment]
Howdy @Ronan-Lenor - we pushed out a fix for this with `v1.28.0`  https://github.com/symfony/maker-bundle/releases/tag/v1.28.0
Running `composer upgrade maker-bundle` should take care of that.. To fix in existing generated templates:

```diff
// src/Controller/ResetPasswordController.php

    public function verifyUserEmail(Request $request, UserRepository $userRepository): Response
    {
        ...
        if (null === $id) {
            return $this->redirectToRoute('app_register');
        }

-       $userRepository->find($id);
+       $user = $userRepository->find($id);

        if (null === $user) {
            return $this->redirectToRoute('app_register');
        }
        ...
```

If you get stuck or need additional help, please dont hesitate to ask! Thank you.
