### ISSUE TITLE
make:message do not find key when setting transport

### ISSUE THREAD

**Issue by jmeyo** [symfony/maker-bundle#796]
When creating new message with make:message and choosing a transport, I got a 

Symfony\Bundle\MakerBundle\Util\YamlManipulationFailedException

It seems the yaml parser doesn't like keys surrounded by quotes as used in the documentation.

```
$ bin/console m:message

 The name of the message class (e.g. SendEmailMessage):
 > SendEmailMessage

 Which transport do you want to route your message to? [[no transport]]:
  [0] [no transport]
  [1] async_priority_high
  [2] async
  [3] async_ad
  [4] failed
 > 2

14:12:41 ERROR     [console] Error thrown while running command "'m:message'". Message: "Cannot find the key "App\Message\OtherExistingMessage" ["exception" => Symfony\Bundle\MakerBundle\Util\YamlManipulationFailedException^ { …},"command" => "'m:message'","message" => "Cannot find the ksey "App\Message\OtherExistingMessage""]

In YamlSourceManipulator.php line 581:
                                                                 
  Cannot find the ksey "App\Message\OtherExistingMessage"  
                                                                 

make:message [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]


```

**Comment by jmeyo** [comment]
Easy workaround is to comment all your message routing, use the maker, and then uncomment.

**Comment by jmeyo** [comment]
The getkeyregex could be improved
https://github.com/symfony/maker-bundle/blob/01a9058c7f10b4cda859fc0a99e28629b927604a/src/Util/YamlSourceManipulator.php#L685-L688

 to something like 
```php
   private function getKeyRegex($key)
    {
        return sprintf('#%s( )*\'?:#', preg_quote($key));
    }```

https://github.com/jmeyo/maker-bundle

But then generated keys should also be surrounded by quotes in end result when transport is chosen, and there might be some side effects

**Comment by OskarStark** [comment]
Can you send a PR and add a testcase?

**Comment by Yonninout** [comment]
I was on the same case today. 

In my messenger.yaml config files the rounting array was written with simple quoted class name like this : 

```yaml
        routing:
            'App\Message\NewEnrichmentFile': async
            'App\Message\UpdateEnrichmentFile': async
            'App\Message\ExportEnrichmentFile': async
            'App\Message\NewPackaging': async
            'App\Message\NewReporting': async
            'App\Message\SendISRA': async
            'App\Message\TestMessage': async
```

I was getting exactly the same error and used the workaround of @jmeyo and found that the new key created was without quote.

```yaml
        routing:
            App\Message\NpaiExportMessage: async
```

I remove all the quote and try to generate an other message class and everything worked just fine.

**Comment by webmasterMeyers** [comment]
Just ran into this same problem today, I can confirm removing the single quotes (as is show to do by the docs) solves the error.  This is with Symfony 4.4.18, just updated messenger to 4.4.21 from 4.4.18

**Comment by webmasterMeyers** [comment]
> Upgrading symfony/maker-bundle (1.27.0 => v1.30.2)
The issue is still present

**Comment by OskarStark** [comment]
![image](https://user-images.githubusercontent.com/995707/121767306-bab5c500-cb57-11eb-918a-d3fee0728eeb.jpeg)

ksey looks like a typo -> key
