### ISSUE TITLE
[RFC] Generate classes with declare(strict_types=1);

### ISSUE THREAD

**Issue by enumag** [symfony/maker-bundle#80]
I tried this bundle today and was quite surprised to find that the generated PHP files do not contain `declare(strict_types=1);`. I can't see any reason for that since this bundle itself requires PHP 7 anyway. Is there some other reason? Or should I send a PR?

**Comment by javiereguiluz** [comment]
We didn't include it because the generated code follows the same rules as Symfony's own code. We don't use `declare(strict_types=1);` anywhere in our code ... and if I'm right, most of the popular PHP projects don't use it yet either.

**Comment by enumag** [comment]
Yeah that's most probably the case. However the projects that are most likely to use this bundle are the brand new symfony-based applications which will most likely use PHP7 and strict types.

Anyway thanks for the explanations.
