### ISSUE TITLE
make:crud better new method proposition

### ISSUE THREAD

**Issue by OrioPrisco** [symfony/maker-bundle#802]
Why does the generated new method use almost the same code as the edit method?
Why not reuse the edit method, isn't it better to not repeat yourself?
I tried it on my controller and it works fine, I just had to ommit the delete form in the `edit.html.twig` when the id wasn't set.

**Comment by jrushlow** [comment]
> Why does the generated new method use almost the same code as the edit method?
The code generated is meant to be used as a base for your specific implementation and designed to be flexible enough for simple and complex use cases. The routes / controller design generated also allows for a somewhat RESTful implementation without a lot of heavy modification.

> Why not reuse the edit method, isn't it better to not repeat yourself?
We very well could do that, but that would take away from the flexibility mentioned above. I find myself refactoring the generated code sometimes when I reach for `make:crud` to consolidate the methods for very simple operations. But then there are other times when I need to keep the `new` & `edit` business logic completely separate. 

Ideas and PR's are certainly welcome for improved / alternative implementations of `make:crud` and all of our other makers.

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
