### ISSUE TITLE
The file "config/packages/security.yaml" does not exist. This command requires that file to exist so that it can be updated.

### ISSUE THREAD

**Issue by Giuscar** [symfony/maker-bundle#803]
Hello everyone, 

I have the issue described in the tiltle everytime I execute the command "php bin/console make:auth". 
The file security.yaml is located in the folder app/config/packages/security.yaml (default location for the configuration). 

Can you help me with this issue, please? Maybe it can be related to the fact that the config folder is under app?

Regards, 
Giuseppe.

**Comment by jrushlow** [comment]
Howdy @Giuscar - What version of `Symfony` are you using? the contents of `composer outdated` would also be helpful. Thanks!

**Comment by jrushlow** [comment]
Stale
