### ISSUE TITLE
RFC: annotation to skip a field in entity

### ISSUE THREAD

**Issue by andrewtch** [symfony/maker-bundle#813]
Can we add an annotation like `@Maker\Skip` to entity fields so getters / setters are not regenerated with --regenerate --overwrite command?

The use case applies to Gedmo PersonalTranslations, for example. If you use it you have a field in your entities, $object, which is defined like so:

```
/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="translations")
     * @ORM\JoinColumn(name="object_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $object;
```

there are getters / setters without type in mapped superclass, so when maker bundle generates `setObject(Product $object)`, it breaks inheritance.

Another option would be skipping getter / setter generation if there is one in parent class.

What do you think?

Edit: Oh, it seems like I've have had a similar issue with Traits couple years ago https://github.com/symfony/maker-bundle/pull/181

**Comment by jrushlow** [comment]
Howdy @andrewtch - not a bad idea and I can envision a use case for this. I don't foresee us shooting down a PR for this new functionality. Although, I do favor `@Maker\Skip` or some variation along those lines instead of skipping inherited methods / properties.

**Comment by andrewtch** [comment]
@jrushlow - the only drawback in @Maker\Skip is that Maker does not use any annotation :) introducing a single annotation with a pretty edge use case may be a bit too much.

The problem actually is not about the skipping fields, but about the incorrect typehint for inherited methods.

I'll take a look at this next week, hopefully.

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!

Note - MakerBundle is moving towards only using attributes.
