### ISSUE TITLE
Using CLI to create services 

### ISSUE THREAD

**Issue by asma1402** [symfony/maker-bundle#814]
**Description**  
it would be nice to create a command line to generate services, we can use CLI to create almost everything but not services.

**Example**  
we can use it this way : 
make:service

**Comment by jrushlow** [comment]
Howdy @asma1402  - Do you have any particular services in mind that are common among Symfony projects?

**Comment by fabpot** [comment]
What would the command do? Nowadays, creating a service is "just" a matter of creating a regular PHP class, nothing more.

**Comment by asma1402** [comment]
to respect the way symfony CLI works creating a skeleton class and adding configs in services.yaml

**Comment by fabpot** [comment]
But you don't need to add anything in services.yaml since Symfony 4.0. I think this can be closed.

**Comment by jrushlow** [comment]
@asma1402 I'm going to close this for now. If you have any specific use cases where having a `make:service` command could add value to MakerBundle, please feel free to share! We love new ideas!

Thank you!

In the meantime, just for reference:
https://symfonycasts.com/screencast/symfony-fundamentals/create-service
https://symfony.com/doc/current/service_container.html
