### ISSUE TITLE
Autocomplete html tags

### ISSUE THREAD

**Issue by duboiss** [symfony/maker-bundle#823]
What do you think about adding the autocomplete tag in forms related to security?

- Google recommendation ([chromium.org/developers/design-documents/create-amazing-password-form](https://www.chromium.org/developers/design-documents/create-amazing-password-forms#TOC-Use-autocomplete-attributes))
- Help for browsers / password managers

So, in login template:
```twig
<label for="inputPassword">Password</label>
<input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
```

Related :
[Making password managers play ball with your login form](https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form)
[Credential Management Level 1](https://w3c.github.io/webappsec-credential-management/)

**Comment by jrushlow** [comment]
I think its a great idea! PR's welcome..

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by David-Baron** [comment]
For the autocomplete security it's here: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

**Comment by duboiss** [comment]
Hey @David-Baron, I'm not sure to understand.

On MDN (your link):
> many modern browsers do not support autocomplete="off" for login fields

On [chromium](https://www.chromium.org/developers/design-documents/create-amazing-password-forms#TOC-Use-autocomplete-attributes):
> Autocomplete attributes help password managers to infer the purpose of a field in a form, saving them from accidentally saving or autofilling the wrong data.

So why do you want to use the "off" value ?

**Comment by Barcha17** [comment]
@duboiss  If you are making an application for a company where multiple users can log in on the same computer, this is useful so that one user does not log in with someone else's account.
So for me the autocomplete="autocomplete_password" is a very bad idea.

**Comment by duboiss** [comment]
Thanks @Barcha17 for your comment
> where multiple users can log in on the same computer

With the passwords stored browser side? What's the behavior? First account stored is automatically used ?

**Comment by Barcha17** [comment]
@duboiss If the credentials are stored on the client side, it suffices to know the username and the passeword is automatically set if the autocomplete is active. So anyone can use any account.
