### ISSUE TITLE
Maker Bundle does not generate column with constraint that has {{ }}

### ISSUE THREAD

**Issue by Guervyl** [symfony/maker-bundle#827]
Hi, running `php bin\console make:migration -e dev` does not add the column in the database when `{{ }}` exists in the annotations. Try with this code you will see it ignores the column.

```
/**
     * @ORM\Column(name="non", type="string", length=50 )
     * @Assert\Length(max="50", maxMessage="Ou ka ajoute jiska {{ limit }} karaktè.", )
     */
    private $non;
```

**Comment by jrushlow** [comment]
Hi @Guervyl - I've tried duplicating the problem you're experiencing to no success. Can you provide more details about your project? e.g. Version of Symfony, PHP, database, & MakerBundle.

An example Symfony App with a committed `composer.lock` & `symfony.lock` file would be even more helpful. 

Thanks!

**Comment by Guervyl** [comment]
Hi, I just created a new project with the same composer.json file and the maker-bundle works fine. But it does not work on the original project. I guest it's an encoding problem. I upload the dummy generated test project [here](https://github.com/Guervyl/symfony-migration-failed). 

Then, run `php bin\console make:entity App\Entity\Moun --regenerate -e dev` and check the Moun entity. The property `non` should not have getter and setter.

Then, run `php bin\console make:migration -e dev` should not include the field `non` in the database.

**Comment by jrushlow** [comment]
> Hi, I just created a new project with the same composer.json file and the maker-bundle works fine. But it does not work on the original project.

I would ensure your dependencies are up to date in the original project first and foremost. 

Its a bit difficult to figure out what the problem could be based on the example project with 20 entities. A simple reproducer app would be just fine. But based off of the [`non` property](https://github.com/Guervyl/symfony-migration-failed/blob/38dd7eb1a771759dc6aa9533ac496328bdab7bf3/src/Entity/Moun.php#L33) that has `@ORM\Column(name="non", type="string", length=50 )`; why should it not be generated with `make:migration`?

**Comment by Guervyl** [comment]
The `non` property should be generated and added to the database. But when I run `make:migration` it does not generate the getter and setter. So I guess if you run `make:migration` it should not generate it on your side.

**Comment by David-Baron** [comment]
The migration maker generate the getter and setters? .... not sure of this ... The entity maker can doing this.

**Comment by Guervyl** [comment]
The problem was there were some bad entity relation mapping on some entities. I don't know why the maker bundle was ignoring those simple `column` fields. I just fixed the relation mappings and it generate the getters and setters properly.
