### ISSUE TITLE
Audit the `annotations` dependency for PHP 8

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#833]
Hi!

I believe that we have now updated all of MakerBundle to generate the `Route` PHP 8 attribute instead of the `@Route` annotation if the user is using PHP 8 and has a high enough version of Symfony (where the `Route` attribute exists).

But, I don't think we have reflected this in the "requirements" for the makers. For example, in `make:registration-form`, we *always* require annotations -  https://github.com/symfony/maker-bundle/blob/af91f0190a6d02d03d456610f8cd41a8528f896e/src/Maker/MakeRegistrationForm.php#L447-L450 - but I think (? I could be wrong) that they are only used for the controller's route... and so this should NOT be required if you're on PHP 8.

There are also other makers that have this hard requirement (`make:crud`, `make:reset-password`) but those need to stay for now I believe... as they use other features `make:crud` installs `annotations` to get `SensioFrameworkExtraBundle`'s param converter and `make:reset-password` uses Doctrine annotations).

Cheers!

**Comment by alh4810** [comment]
I agree. Just came here to research this. I do not want to install doctrine/annotations. Here's an error I get when attempting to make a Controller:

`% php bin/console make:controller ApplicationController

                                                                                
 [ERROR] Missing package: to use the make:controller command, run:              
                                                                                
         composer require doctrine/annotations `

I'm on PHP8. I do not want to install doctrine/annotations. So, for now, I've settled on the following "workaround":

`composer require doctrine/annotations --dev`

Now, I've "only" required doctrine/annotations in the development environment, and the "bloat" does not get pushed up to the server.

**Comment by jrushlow** [comment]
This has been fixed in #1262 & #1264 among others.
