### ISSUE TITLE
How to use maker bundle to generate entity inside bundles

### ISSUE THREAD

**Issue by Guervyl** [symfony/maker-bundle#834]
Hi,
I created a symfony 5 project with 2 bundles. When I create an entity with the maker bundle it generate the enity in `src/Entity/bundle-namespace` instead of `src/bundle-namespace/entity`.

**Comment by Guervyl** [comment]
I'm disappointed no one answered. But I just make the maker bundle works m=with my bundle by adding my bundle namespace  in the maker.yaml config file:

```
maker:
  root_namespace: MyName\MyBunlde
```

But my project has two bundles in it. If I want to generate entity in the other bundle, it does not work properly.

When I run `php bin\console make:entity \MyName\MyOtherBundle\Entity\User  -e dev`

It prints:
```
created: src/MyName/MyOtherBundle/Entity/User.php
 created: src/MyName/MyBunlde/Repository/MyOtherBundle/Entity/UserRepository.php
```

As you can see, it creates the file `User.php` in the right place. But the file `UserRepository.php`  is in the wrong place.

**Comment by jrushlow** [comment]
Howdy @Guervyl 

> I created a symfony 5 project with 2 bundles

I don't quite understand what you mean by that. https://symfony.com/doc/current/bundles.html explains how to use bundles with Symfony. As a side note:

>In Symfony versions prior to 4.0, it was recommended to organize your own application code using bundles. This is no longer recommended and bundles should only be used to share code and features between multiple applications.

> When I create an entity with the maker bundle it generate the enity in src/Entity/bundle-namespace instead of src/bundle-namespace/entity.

`make:entity` generates entities by default in the `App\Entity` namespace as this Symfony's standard practice. If you're trying to use MakerBundle to generate classes for distribution with a bundle, this is not supported. 

> I'm disappointed no one answered.

Unfortunately for many of us, we are only able to contribute to Symfony and many other open source projects after we have fulfilled our obligations to our families and full time jobs. I understand it can be frustrating when you're trying to solve a problem and need some help right away whenno one is available to triage `maker-bundle/issues`. 

Fortunately - for those times when no one is available to help on the issues board, Symfony has a large community that participates in Symfony's official slack channel https://symfony.com/community 

Please let me know if there is anything else I can help you with. Thanks!

**Comment by Guervyl** [comment]
Hi.
Thanks for your reply. I have read the whole bundle documentation. And I understand it clearly. The problem was the fact the was a Symfony 3 project and I migrated it to Symfony 5 by creating a new Symfony application and copy the `src` folder to this new project. And from the Symfony 3 project the bundles depended on each other using services and templates or views. So it is a bit faster for me to keep using bundles in the same project instead of creating separate projects and dependency injections.

But I'll spend some time reorganizing the bundles.

Thanks.

**Comment by jrushlow** [comment]
I gotcha - ya, that scenario is definitely not supported. You may be able to take advantage of https://symfony.com/doc/current/service_container.html#explicitly-configuring-services-and-arguments but honestly, so much has changed from `3.x` to `5.x` - trying to do a copy and paste of the `src` directory is just asking for trouble. Good luck!
