### ISSUE TITLE
Make:entity abort still adds field

### ISSUE THREAD

**Issue by excitedbox** [symfony/maker-bundle#839]
I just noticed when aborting the make entity halfway through adding a field it still adds that field. When aborting in the middle of a field it is usually because you don't need that field or made a mistake. 

In this case I aborted before adding the length to a string field because I realized I wanted a OneToOne relationship instead. When I tried to use the entity command to add the field again it had created the field with the default settings even though the CLI said it had aborted. If I hadn't tried to use the same name I wouldn't even have noticed that the field got created at all.

This creates confusion on how to fix the field to complete it and it no longer allows adding that field in the console. Removing that field requires removing multiple methods which can get missed and cause errors. A simple fix would be to only add a field once all the questions have been answered.

**Comment by jrushlow** [comment]
This behavior is as expected due to how `make:entity` first must create the entity or use an existing entity then ask the question(s) regarding entity properties. Skimming through the entity maker's command - it would take a considerable amount of work to refactor the maker to ask all questions first, then generate / update an entities properties.

I'm not opposed to the idea - PR's are welcome.

**Comment by David-Baron** [comment]
Before removing the field from your entity, did you clear the console?

**Comment by excitedbox** [comment]
Wouldn't it be possible to store the commands to be executed in an array and on the final question for adding that field execute all the commands? Then start the loop over.

Or very similar: The create entity action could be written so that if no entity arguments are submitted with the command, it loops that all the questions and in the end executes the create command again with arguments. This would only require adding a loop instead of rewriting anything. It could even be added as a custom make command pretty easily.

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
