### ISSUE TITLE
This condition will never be met, an object is returned

### ISSUE THREAD

**Issue by iva3682** [symfony/maker-bundle#857]
https://github.com/symfony/maker-bundle/blob/006577909ded549ee48fd69aa4da1a75ff9a2b55/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L80

**Comment by jrushlow** [comment]
`getTokenObjectFromSession` returns `?ResetPasswordToken` - If you access `/check-email` directly without having requested a password reset, it is possible that the token would not exist in the session.
