### ISSUE TITLE
[make:entity] Add a way to set $include_example_comments to false 

### ISSUE THREAD

**Issue by MrYamous** [symfony/maker-bundle#861]
Hi, 

When make:entity command is used, two example functions are added to the related repository
In the repository template, there is a $include_example_comments variable, this variable is set to true by default, but there seems to be no way to change its value (or I haven't found it, sorry about that)

What would you think of adding a way to set this value to false? With a `no-example` option maybe? I don't know if this could be a good name

**Comment by bernard-ng** [comment]
Hello @MrYamous I thought about it too, it would be a good idea indeed

**Comment by jrushlow** [comment]
I'm not opposed to the idea.. I often find myself removed all of the commented code samples from the repo classes after using `make:entity`.

I think the simplest approach would be to ask "Do you want to generate code examples..." that defaults to `true` or something along those lines. `$include_example_comments` could then be set accordingly.

PR's welcome!

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
