### ISSUE TITLE
Use AbstractController as the base controller class

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#88]
This has been something we've debated. I just had a long conversation with @nicolas-grekas about it, who feels pretty strongly about pushing this best practice now. I don't feel too strongly, and certainly we need to do this at some point. Since MakerBundle is for Symfony 4 (so new projects, or people who have upgraded and are fully using the new features), this is a great place to push the best practice.

**Comment by codedmonkey** [comment]
Agreed, pretty torn on this one. I think it's a good idea if it means we push developers to create cleaner code, if they don't like it, it's a very simple edit to revert back to the old class. `ServiceSubscriberInterface` could use some more documentation though.

**Comment by wouterj** [comment]
Closing as this has been fixed by 2e6403b346cfedeabe030ad6fe5e500346fd9323
