### ISSUE TITLE
Suggestion for ClassSourceManipulator

### ISSUE THREAD

**Issue by Kelows** [symfony/maker-bundle#886]
Would it be possible to make 'addStatementToConstructor' public ? there:
https://github.com/symfony/maker-bundle/blob/5da43406df3692b6b82a0f5a848bc9f851c25e84/src/Util/ClassSourceManipulator.php#L733

I think it would be usefull (ex. to add a new ArrayCollection or another node easily in our class constructor without creating a whole new relation field like 'addCollectionRelation' does) but maybe I'm missing something

**Comment by jrushlow** [comment]
We know know plans for this at the moment as CSM is an `internal` tool.
