### ISSUE TITLE
Add support for PHP 8 Attributes to make:entity

### ISSUE THREAD

**Issue by markwatney2016** [symfony/maker-bundle#892]
With https://github.com/doctrine/DoctrineBundle/releases/tag/2.4.0 the Doctrine Bundle added support for the ORM 2.9 AttributeDriver. It would now be great to also have support for those PHP 8 Attributes in the Maker Bundle.

Current situation:

```
 [ERROR] Only annotation mapping is supported by make:entity, but the App\Entity\User class
         uses a different format. If you would like this command to generate the properties &
         getter/setter methods, add your mapping configuration, and then re-run this command
         with the --regenerate flag.  
```

**Comment by bastien70** [comment]
Hello, when this PR will be released ?

**Comment by karaka200** [comment]
When will this problem be solved?

**Comment by devnix** [comment]
I would stop making "When X will be solved/released", as it will probably result in a locked conversation.
