### ISSUE TITLE
Error when DoctrineOrmMappingsPass::createAnnotationMappingDriver() is used in a third-party bundle.

### ISSUE THREAD

**Issue by ajgarlag** [symfony/maker-bundle#897]
Related to #845 and #847

I have created a reproducer in https://github.com/ajgarlag/maker-bundle-bug.

Steps to reproduce:
```sh
git clone https://github.com/ajgarlag/maker-bundle-bug
cd maker-bundle-bug
composer install
composer require --dev symfony/maker-bundle
```

Error:
```
!!  TypeError {#5749
!!    #message: "Symfony\Component\DependencyInjection\Definition::addMethodCall(): Argument #2 ($arguments) must be of type array, string given, called in /tmp/lala/maker-bundle-bug/vendor/symfony/dependency-injection/Definition.php on line 356"
!!    #code: 0
!!    #file: "./vendor/symfony/dependency-injection/Definition.php"
!!    #line: 373
!!    trace: {
!!      ./vendor/symfony/dependency-injection/Definition.php:373 { …}
!!      ./vendor/symfony/dependency-injection/Definition.php:356 { …}
!!      ./vendor/symfony/maker-bundle/src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php:69 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:94 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:762 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:596 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:136 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:169 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:75 { …}
!!      ./vendor/symfony/console/Application.php:149 { …}
!!      ./bin/console:42 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!      }
!!    }
!!  }
!!  2021-06-14T13:41:51+02:00 [critical] Uncaught Error: Symfony\Component\DependencyInjection\Definition::addMethodCall(): Argument #2 ($arguments) must be of type array, string given, called in /tmp/lala/maker-bundle-bug/vendor/symfony/dependency-injection/Definition.php on line 356
!!  

```

**Comment by ajgarlag** [comment]
Friendly ping for @nicolas-grekas. As you fixed #845 with #847, could you try my reproducer and give me a hint about how to fix it. I'd like to send the fix as a PR, but I'm completely lost with this issue.

**Comment by ajgarlag** [comment]
Friendly ping for @weaverryan. I'd like to work in a PR to fix this issue. Could you give me a hint?

**Comment by weaverryan** [comment]
Yea.. I don't really understand the cause yet. It appears that, for some reason, in your situation, on this line https://github.com/symfony/maker-bundle/blob/285e8537fe019c07dc85d30ac9f02a2b67deb358/src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php#L69, that `$methodCalls` argument contains some bad structure. Each item in that array, I believe, should have the structure:

```
0 => 'stringMethodName'
1 -> ['array', 'of', 'arguments']
```

But it seems that this `1` index might be a string in some cases. 

The problem might be this line - https://github.com/symfony/maker-bundle/blob/285e8537fe019c07dc85d30ac9f02a2b67deb358/src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php#L59 - if I'm reading things correctly, that should actually be:

```php
$methodCalls[$i] = [$method, $arguments];
```

**Comment by ajgarlag** [comment]
Thanks @weaverryan. Your suggestion has fixed the problem. PR open
