### ISSUE TITLE
[make:registration] No Guard authenticators found - New Authenticator

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#900]
Hi,
I have Symfony 5.3.2.
I do : `php bin/console make:registration-form`.

I answered question 'yes' for this question `Do you want to automatically authenticate the user after registration? (yes/no) [yes]:`.

And I have ` ! [NOTE] No Guard authenticators found - so your user won't be automatically authenticated after registering.`.

**Comment by jrushlow** [comment]
Did you run `make:auth` to create the Authentication skeleton before running `make:registration-form`? In lieu of `make:auth`, you are able to manually implement your authentication system by following https://symfony.com/doc/current/security.html

**Comment by seb-jean** [comment]
Yes, I ran `make:auth`.

**Comment by jrushlow** [comment]
can you create a simple reproducer app in a public repo?

**Comment by seb-jean** [comment]
Sure : https://github.com/seb-jean/sftest

**Comment by apphancer** [comment]
I am using Symfony 5.3.2 and have also received the same error `! [NOTE] No Guard authenticators found - so your user won't be automatically authenticated after registering..`

After adding `symfony/security-guard` I am no longer getting that error. However, the logic that gets created with `make:registration-form` doesn't contain anything to authenticate the user after registration.

**Comment by apphancer** [comment]
The `symfony/security-guard` does fix the error message when running the command. However, this package is actually not required as it contains deprecated methods not compatible with Symfony's new Authenticator. 

I believe the missing logic is the following:

```
use App\Security\AppAuthenticator;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;
...

public function register(Request $request, AppAuthenticator $appAuthenticator, UserAuthenticatorInterface $userAuthenticator) {
...
if ($form->isSubmitted() && $form->isValid()) {
...
return $userAuthenticator->authenticateUser($user, $appAuthenticator, $request);
}
....
}
```

Where AppAuthenticator is the class compatible with AuthenticatorInterface.

**Comment by 537mfb** [comment]
I can conforme this happens when make:auth creates am authenticator using the new system - every time
tryed it several times on newly created projects of symfony 5.4

```
 Do you want to automatically authenticate the user after registration? (yes/no) [yes]:
 > 

 ! [NOTE] No Guard authenticators found - so your user won't be automatically authenticated after registering.          
```

**Comment by 537mfb** [comment]
It also uses `UserPasswordEncoderInterface` which appears to have been marked deprecated as of `Symfony 5.3`

**Comment by 537mfb** [comment]
small correction to what @apphancer posted:

```
use App\Security\AppAuthenticator;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;
...
public function register(Request $request, AppAuthenticator $appAuthenticator, UserAuthenticatorInterface $userAuthenticator, UserPasswordHasherInterface $passwordHasher): Response
{
...
if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
...
return $userAuthenticator->authenticateUser($user, $appAuthenticator, $request);
}
....
}
```
And remove the `use` for the old `PasswordEncoder`

**Comment by sovetski** [comment]
I have the same issue with Symfony 8

Edit: In Symfony 8 `make:auth` is deprecated:

`[CAUTION] "make:auth" is deprecated, use any of the "make:security" commands instead.`

So you have to use `make:security:form-login` or `make:security:custom`
