### ISSUE TITLE
Update make:auth to use the new security system, update docs.

### ISSUE THREAD

**Issue by tacman** [symfony/maker-bundle#919]
**Description**

Anyone trying to heed the deprecation warnings about using the new security system risks frustration, as there's no documentation or examples of how to actually implement it.

**Example**

bin/console make:auth

generates the old security

https://symfony.com/doc/current/security/form_login_setup.html

describes the old security.

It'd be great if make:auth and the documentation gave a full example of how to implement the new security system.

Thanks.

**Comment by weaverryan** [comment]
Yes, we need to get this going ASAP - new versions of symfony keep us busy :). @jrushlow i thought there was a Pr with this in progress but I can’t find anything. Or have we just talked about this?

**Comment by jrushlow** [comment]
Yes we've had this implemented for a while now. Before running `make:auth` ensure that you have 
```yaml
# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    # ...
```
Then `make:auth` will generate the new security templates, otherwise it falls back to the old security system.

**Comment by wouterj** [comment]
> the documentation gave a full example of how to implement the new security system.

And work on this btw also started. I guess I'm at 80% of rewriting the docs to use the new system.

**Comment by tacman** [comment]
Yep, that works.  Thanks!
