### ISSUE TITLE
[RFC] Introduce an `override` command

### ISSUE THREAD

**Issue by maidmaid** [symfony/maker-bundle#92]
Always with the aim of making our developments faster, would it be interesting to introduce some `override:*` commands for overriding all what is possible to override from core and third-party bundle? For instance:

- `override:template`
- `override:error-pages`
- `override:route`
- `override:entity`

**Comment by javiereguiluz** [comment]
We appreciate your proposal to improve this bundle ... but I'm afraid I must close it as "won't fix". The two main reasons are:

* The problem solved is not common enough. Except error pages, it's uncommon to have to override third-party bundle elements.
* It's a bit out of the scope of this bundle. Even the prefix (`override:` vs `make:`) shows it.

I hope you understand it. Thanks!
