### ISSUE TITLE
Commands for register and login

### ISSUE THREAD

**Issue by fiher** [symfony/maker-bundle#93]
Hello, I have opened this issue on the main symfony repository and I was told to do it on this one. Here is the main issue if you want to read it - https://github.com/symfony/symfony/issues/25406#event-1380344140

Here is the idea - a command to create register and login form by providing an entity which implements `UserInterface` (I have seen that some think that this is a bad practice so if you really dislike `UserInterface` that much we can think of another requirement) and has some base options.

The command will generate `SecurityController` if it doesnt exist as well as login and register forms and views. It will change the `route.yml` and `security.yml` files to basically make everything needed for a login and register to work properly.

This way the user doesn't need to repeat everything mentioned in the documentation or download FOSUserBundle and then follow the documentation again. It saves a lot of time for people like me who make lots of demo projects to try new stuff (expecially after 4.0 is out).

If this command generates everything needed there is no need for any kind of magic. currently if you follow the documentation for register and login or if you download FOSUserBundle there is a lot of magic going on and you don't see the code (unless you dig into `vendor` folder a lot). 

With that command the code generated can be dependency free (everything used by it is generated by it) and with no magic involved so that if a new user wants to use it and understand how it works he can do so very easily without having to write anything.

The command might be separated into two commands 

- `make:security:register`
      - `-algorithm={algorithm name}` (default is bcrypt)
      - `--withsalt`  determines if the user wants the encryption to use salt( default is `yes`)
      - `-entity={entity name}` (default looks for `User`)
      - `-path={path for register}` (default is `/register`)

- `make:security:login` if possible to use the options provided to `make:security:register` if not - repeat the same options
      - `checkpath={path for check}` (default is `/login`)
      - `loginpath={path for login}` (default is `/login`)
    

As you can see the two commands are under `make:security` which might have other commands.

I would love to participate in the development of these commands or anything to help Symfony, but I have never been part of such big repository so I would love it if there is someone willing to help me and answer my questions as I try to contribute to Symfony! If there is none - hope you guys will like the idea so that I can use it!

**Comment by ro0NL** [comment]
@fiher  see https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9 :)

**Comment by weaverryan** [comment]
This has been done for awhile - just missed closing this issue!

**Comment by fiher** [comment]
Nice, @weaverryan mind telling me in which update it got introduced as this proposal was quite a while ago?
