### ISSUE TITLE
Make:Auth shows misleading message

### ISSUE THREAD

**Issue by 537mfb** [symfony/maker-bundle#937]
When using `bin/console make:auth` so that it creates an `AppAuthenticator` based on the new `authenticator-based` system instead of the old `GuardAuthenticator`, we get the bog standard:

```
 Next:
 - Customize your new authenticator.
 - Finish the redirect "TODO" in the App\Security\AppAuthenticator::onAuthenticationSuccess() method.
 - Check the user's password in App\Security\AppAuthenticator::checkCredentials().
 - Review & adapt the login template: templates/security/login.html.twig.
```

However, the new `AppAuthenticator` doesn't have a `checkCredentials` method anymore - so that message is misleading

Also, the new `AppAuthenticator` returns a `PassportInterface` from it's `authenticate` method - which has been marked as deprecated as of `Symfony 5.4`

**Comment by jrushlow** [comment]
I believe this has already been corrected. Thanks for the heads up
