### ISSUE TITLE
[make:entity] Add const types

### ISSUE THREAD

**Issue by seb-jean** [symfony/maker-bundle#980]
Hi,

I just tested using make: entity to generate code using PHP 8 attributes. It's awesome !
I think it would be nice to put constants in the types like it's done for:

https://github.com/SymfonyCasts/reset-password-bundle/blob/main/src/Model/ResetPasswordRequestTrait.php#L24

and also here:

https://www.doctrine-project.org/2021/05/24/orm2.9.html

For instance:

```php
 #[ORM\Column(type: Types::STRING, length: 255)]
```

instead of:

```php
 #[ORM\Column(type: 'string', length: 255)]
```

Thanks :)

**Comment by weaverryan** [comment]
That's a good idea :)

**Comment by SimonMarx** [comment]
That would intersect with the issue https://github.com/symfony/maker-bundle/issues/982, right?
