### ISSUE TITLE
Undefined Type::JSON_ARRAY 

### ISSUE THREAD

**Issue by Gulivertx** [symfony/maker-bundle#995]
Hello,

I faced to an issue to add properties to entities with the following error :

`Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY`

Downgrading doctrine/orm and doctrine/dbal fix the issue.

  - Downgrading doctrine/dbal (3.1.3 => 2.13.4)
  - Downgrading doctrine/orm (2.10.1 => 2.9.6)

**Comment by wouterj** [comment]
Hi there! Thanks for reporting the issue.

This has been reported several times already and a fix has been merged (but not yet released) in https://github.com/symfony/maker-bundle/pull/991 It's often a great idea to check the recently reported issues before opening a new one - that saves you and us some time :)
