### ISSUE TITLE
Undefined class constant 'JSON_ARRAY'

### ISSUE THREAD

**Issue by HysteriaKa** [symfony/maker-bundle#999]
Hello,
We needed to remove our Bdd test, and now we got this error. We don't understand what's wrong, we saw an issue that kinda looked the same and tried what it says, but it does not change anything !
Can someone help us, we were supposed to show our work to our boss tomorrow !!!!

![image](https://user-images.githubusercontent.com/55787048/139018739-bb2611d5-ecef-412d-9b99-86c99d6f3673.png)

**Comment by ericjacolin** [comment]
Same issue here, after a 5.2 patch-level update:
Symfony 5.2.12
doctrine/orm                         2.10.2
symfony/doctrine-bridge      5.2.12

**Comment by ZoeBercy** [comment]
I created a RegistrationController with Symfony 5.2.14 and I have the same problem. In my case, It seems to come from :
`$form = $this->createForm(TaskType::class, $task);` and `$form->handleRequest($request);`.

I have these methods in an another Controller, which works correctly, so I don't understand why it doesn't work in my RegistrationController.

**Comment by weaverryan** [comment]
This is not related to MakerBundle. But to help, it looks like you need this change: https://github.com/symfony/symfony/commit/6faae75102751b9550ed767b7afe5a544e35d5ee

That should be included in 5.3.8 and higher - I do not think that "fix" exists in Symfony 5.2. The reason it started failing all of a sudden is that you probably updated to `doctrine/dbal` 3 where I believe that constant is now gone.

Cheers!

**Comment by ZoeBercy** [comment]
Thank you for your answer weaverryan.
I resolved my issue with this :
https://symfony.com/doc/current/setup/upgrade_minor.html

**Comment by FatihGucuko** [comment]
Hi, i also got this error just today, and found the solution.
but from php bin/console make:registration-form
And then you go to /register page


It seems that the issue comes from doctrine/dbal 3.2
I have symfony 5.2.14
So i've manually installed with  => composer doctrine/dbal:2.13.6


And it fixed the issue !

**Comment by Marouankl** [comment]
case Types::ARRAY:
            case Types::SIMPLE_ARRAY:
            case 'json_array': #just changer cette line et marche très bien 
                return Type::BUILTIN_TYPE_ARRAY;
        }

**Comment by E-Bousk** [comment]
I had this issue when upgrade from Symfony 5.1.11 to 5.2.14
(doctrine/dbal": "^3.3)
Just insert this line :
`public const JSON_ARRAY           = 'json_array';` with other constants
on _D:\__DEV\____symfony\sym-blog_5.2.14\vendor\doctrine\dbal\src\Types\Types.php_ file

**Comment by HAMDIAmenAllah** [comment]
> I had this issue when upgrade from Symfony 5.1.11 to 5.2.14 (doctrine/dbal : 3.3.2 --- symfony/doctrine-bridge 5.2.12) Just insert this line : `public const JSON_ARRAY = 'json_array';` with other constants on `\vendor\doctrine\dbal\src\Types\Types.php` file

It was fixed on " public const JSON_ARRAY = 'json_array'; " . Confirmed!
